// ============================================================
// WordGuard - Enemy Definitions (30 types)
// ============================================================

import { EnemyType } from '@/shared/types/game';

export interface EnemyDefinition {
  type: string;
  name: string;
  nameKr: string;
  baseHp: number;
  baseSpeed: number;
  traits: string[];
  resistances: Record<string, number>;
  isBoss: boolean;
  isFlying: boolean;
  minWave: number;
  goldReward: number;
  expReward: number;
  color: string;
  icon: string;
  specialAbility?: string;
}

export const ENEMY_DEFINITIONS: Record<EnemyType, EnemyDefinition> = {
  // ── Basic Enemies ──────────────────────────────────────────

  [EnemyType.SLIME]: {
    type: EnemyType.SLIME,
    name: 'Slime',
    nameKr: '슬라임',
    baseHp: 50,
    baseSpeed: 1.0,
    traits: ['basic'],
    resistances: { fire: 1.5, ice: 1.0, lightning: 1.0, wind: 1.0, earth: 0.5, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 1,
    goldReward: 5,
    expReward: 2,
    color: '#22C55E',
    icon: '🟢',
  },

  [EnemyType.GOBLIN]: {
    type: EnemyType.GOBLIN,
    name: 'Goblin',
    nameKr: '고블린',
    baseHp: 70,
    baseSpeed: 1.2,
    traits: ['basic', 'agile'],
    resistances: { fire: 1.0, ice: 1.0, lightning: 1.0, wind: 1.0, earth: 1.0, light: 1.0, dark: 0.8 },
    isBoss: false,
    isFlying: false,
    minWave: 1,
    goldReward: 7,
    expReward: 3,
    color: '#4ADE80',
    icon: '👺',
  },

  [EnemyType.SKELETON]: {
    type: EnemyType.SKELETON,
    name: 'Skeleton',
    nameKr: '스켈레톤',
    baseHp: 80,
    baseSpeed: 0.9,
    traits: ['basic', 'undead'],
    resistances: { fire: 1.5, ice: 1.0, lightning: 1.0, wind: 1.0, earth: 0.5, light: 1.5, dark: 0.5 },
    isBoss: false,
    isFlying: false,
    minWave: 2,
    goldReward: 8,
    expReward: 4,
    color: '#D4D4D8',
    icon: '💀',
  },

  [EnemyType.BAT]: {
    type: EnemyType.BAT,
    name: 'Bat',
    nameKr: '박쥐',
    baseHp: 40,
    baseSpeed: 1.5,
    traits: ['basic', 'fast'],
    resistances: { fire: 1.0, ice: 1.0, lightning: 1.5, wind: 0.5, earth: 1.0, light: 1.5, dark: 0.5 },
    isBoss: false,
    isFlying: true,
    minWave: 2,
    goldReward: 6,
    expReward: 3,
    color: '#71717A',
    icon: '🦇',
  },

  [EnemyType.WOLF]: {
    type: EnemyType.WOLF,
    name: 'Wolf',
    nameKr: '늑대',
    baseHp: 90,
    baseSpeed: 1.3,
    traits: ['basic', 'pack'],
    resistances: { fire: 1.5, ice: 1.0, lightning: 1.0, wind: 1.0, earth: 1.0, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 3,
    goldReward: 9,
    expReward: 5,
    color: '#78716C',
    icon: '🐺',
    specialAbility: 'packSpeed: 무리가 3마리 이상이면 이동속도 +20%',
  },

  // ── Armored Enemies ────────────────────────────────────────

  [EnemyType.KNIGHT]: {
    type: EnemyType.KNIGHT,
    name: 'Knight',
    nameKr: '기사',
    baseHp: 200,
    baseSpeed: 0.7,
    traits: ['armored'],
    resistances: { fire: 0.8, ice: 1.0, lightning: 1.0, wind: 0.8, earth: 0.5, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 5,
    goldReward: 15,
    expReward: 8,
    color: '#A8A29E',
    icon: '🛡️',
    specialAbility: 'armorBlock: 물리 피해 20% 감소',
  },

  [EnemyType.GOLEM]: {
    type: EnemyType.GOLEM,
    name: 'Golem',
    nameKr: '골렘',
    baseHp: 400,
    baseSpeed: 0.4,
    traits: ['armored', 'slow', 'heavy'],
    resistances: { fire: 0.5, ice: 0.5, lightning: 1.5, wind: 0.5, earth: 0, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 8,
    goldReward: 25,
    expReward: 15,
    color: '#78716C',
    icon: '🗿',
    specialAbility: 'earthImmune: 대지 속성 면역',
  },

  [EnemyType.SHIELD_BEARER]: {
    type: EnemyType.SHIELD_BEARER,
    name: 'Shield Bearer',
    nameKr: '방패병',
    baseHp: 180,
    baseSpeed: 0.8,
    traits: ['armored', 'shield'],
    resistances: { fire: 0.8, ice: 0.8, lightning: 1.0, wind: 0.8, earth: 0.8, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 6,
    goldReward: 14,
    expReward: 7,
    color: '#A3A3A3',
    icon: '🛡️',
    specialAbility: 'shieldBlock: 첫 3회 공격 피해 완전 흡수',
  },

  [EnemyType.IRON_TURTLE]: {
    type: EnemyType.IRON_TURTLE,
    name: 'Iron Turtle',
    nameKr: '철갑거북',
    baseHp: 350,
    baseSpeed: 0.3,
    traits: ['armored', 'slow', 'regen'],
    resistances: { fire: 0.5, ice: 0.5, lightning: 1.5, wind: 0.5, earth: 0.5, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 10,
    goldReward: 22,
    expReward: 12,
    color: '#525252',
    icon: '🐢',
    specialAbility: 'regen: 초당 HP 2% 회복',
  },

  [EnemyType.ARMORED_ORC]: {
    type: EnemyType.ARMORED_ORC,
    name: 'Armored Orc',
    nameKr: '중장갑 오크',
    baseHp: 280,
    baseSpeed: 0.6,
    traits: ['armored', 'berserk'],
    resistances: { fire: 0.8, ice: 1.0, lightning: 1.0, wind: 0.8, earth: 0.8, light: 1.0, dark: 0.8 },
    isBoss: false,
    isFlying: false,
    minWave: 12,
    goldReward: 20,
    expReward: 10,
    color: '#84CC16',
    icon: '👹',
    specialAbility: 'berserk: HP 30% 이하 시 이동속도 2배',
  },

  // ── Fast Enemies ───────────────────────────────────────────

  [EnemyType.THIEF]: {
    type: EnemyType.THIEF,
    name: 'Thief',
    nameKr: '도적',
    baseHp: 60,
    baseSpeed: 2.0,
    traits: ['fast', 'dodge'],
    resistances: { fire: 1.0, ice: 1.5, lightning: 1.0, wind: 0.5, earth: 1.0, light: 1.0, dark: 0.8 },
    isBoss: false,
    isFlying: false,
    minWave: 4,
    goldReward: 12,
    expReward: 6,
    color: '#6366F1',
    icon: '🗡️',
    specialAbility: 'dodge: 20% 확률로 공격 회피',
  },

  [EnemyType.SHADOW]: {
    type: EnemyType.SHADOW,
    name: 'Shadow',
    nameKr: '그림자',
    baseHp: 45,
    baseSpeed: 2.2,
    traits: ['fast', 'stealth'],
    resistances: { fire: 1.0, ice: 1.0, lightning: 1.0, wind: 1.0, earth: 1.0, light: 1.5, dark: 0 },
    isBoss: false,
    isFlying: false,
    minWave: 7,
    goldReward: 15,
    expReward: 8,
    color: '#1E1B4B',
    icon: '👤',
    specialAbility: 'stealth: 사거리 2 이내에서만 타겟팅 가능',
  },

  [EnemyType.NINJA]: {
    type: EnemyType.NINJA,
    name: 'Ninja',
    nameKr: '닌자',
    baseHp: 70,
    baseSpeed: 2.5,
    traits: ['fast', 'dodge', 'stealth'],
    resistances: { fire: 1.0, ice: 1.5, lightning: 1.0, wind: 0.5, earth: 1.0, light: 1.5, dark: 0.5 },
    isBoss: false,
    isFlying: false,
    minWave: 15,
    goldReward: 20,
    expReward: 12,
    color: '#312E81',
    icon: '🥷',
    specialAbility: 'smokeBomb: 피격 시 30% 확률로 은신 2초',
  },

  [EnemyType.WIND_SPRITE]: {
    type: EnemyType.WIND_SPRITE,
    name: 'Wind Sprite',
    nameKr: '바람 정령',
    baseHp: 55,
    baseSpeed: 2.8,
    traits: ['fast', 'elemental'],
    resistances: { fire: 1.0, ice: 1.5, lightning: 1.0, wind: 0, earth: 1.5, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: true,
    minWave: 10,
    goldReward: 16,
    expReward: 9,
    color: '#67E8F9',
    icon: '🌬️',
    specialAbility: 'windImmune: 바람 속성 면역',
  },

  [EnemyType.HASTE_IMP]: {
    type: EnemyType.HASTE_IMP,
    name: 'Haste Imp',
    nameKr: '신속 임프',
    baseHp: 50,
    baseSpeed: 3.0,
    traits: ['fast', 'haste'],
    resistances: { fire: 1.0, ice: 1.5, lightning: 1.0, wind: 1.0, earth: 1.0, light: 1.0, dark: 0.8 },
    isBoss: false,
    isFlying: false,
    minWave: 14,
    goldReward: 18,
    expReward: 10,
    color: '#C084FC',
    icon: '😈',
    specialAbility: 'hasteAura: 주변 적 이동속도 +15%',
  },

  // ── Magic Enemies ──────────────────────────────────────────

  [EnemyType.WIZARD]: {
    type: EnemyType.WIZARD,
    name: 'Wizard',
    nameKr: '마법사',
    baseHp: 100,
    baseSpeed: 0.8,
    traits: ['magic', 'spellcaster'],
    resistances: { fire: 0.5, ice: 0.5, lightning: 0.5, wind: 0.5, earth: 1.0, light: 0.5, dark: 0.5 },
    isBoss: false,
    isFlying: false,
    minWave: 6,
    goldReward: 14,
    expReward: 8,
    color: '#7C3AED',
    icon: '🧙',
    specialAbility: 'magicShield: 마법 피해 50% 감소',
  },

  [EnemyType.DARK_MAGE]: {
    type: EnemyType.DARK_MAGE,
    name: 'Dark Mage',
    nameKr: '암흑 마법사',
    baseHp: 120,
    baseSpeed: 0.7,
    traits: ['magic', 'debuff'],
    resistances: { fire: 0.8, ice: 0.8, lightning: 0.8, wind: 0.8, earth: 1.0, light: 1.5, dark: 0 },
    isBoss: false,
    isFlying: false,
    minWave: 12,
    goldReward: 18,
    expReward: 10,
    color: '#581C87',
    icon: '🧛',
    specialAbility: 'curse: 공격한 타워의 공격속도 20% 감소 5초',
  },

  [EnemyType.SPIRIT]: {
    type: EnemyType.SPIRIT,
    name: 'Spirit',
    nameKr: '영혼',
    baseHp: 60,
    baseSpeed: 1.0,
    traits: ['magic', 'ethereal'],
    resistances: { fire: 0.5, ice: 0.5, lightning: 0.5, wind: 0.5, earth: 0, light: 1.5, dark: 0.5 },
    isBoss: false,
    isFlying: true,
    minWave: 8,
    goldReward: 13,
    expReward: 7,
    color: '#C4B5FD',
    icon: '👻',
    specialAbility: 'ethereal: 물리 공격 피해 50% 감소',
  },

  [EnemyType.ENCHANTRESS]: {
    type: EnemyType.ENCHANTRESS,
    name: 'Enchantress',
    nameKr: '요술사',
    baseHp: 90,
    baseSpeed: 0.9,
    traits: ['magic', 'heal'],
    resistances: { fire: 0.8, ice: 0.8, lightning: 0.8, wind: 0.8, earth: 1.0, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: false,
    minWave: 10,
    goldReward: 16,
    expReward: 9,
    color: '#E879F9',
    icon: '🧝',
    specialAbility: 'healAura: 주변 적 초당 HP 3% 회복',
  },

  [EnemyType.PHANTOM]: {
    type: EnemyType.PHANTOM,
    name: 'Phantom',
    nameKr: '팬텀',
    baseHp: 75,
    baseSpeed: 1.5,
    traits: ['magic', 'phasing'],
    resistances: { fire: 0.5, ice: 0.5, lightning: 0.5, wind: 0.5, earth: 0, light: 1.5, dark: 0 },
    isBoss: false,
    isFlying: true,
    minWave: 16,
    goldReward: 22,
    expReward: 12,
    color: '#A78BFA',
    icon: '🌀',
    specialAbility: 'phase: 5초마다 짧은 거리 텔레포트',
  },

  // ── Flying Enemies ─────────────────────────────────────────

  [EnemyType.HARPY]: {
    type: EnemyType.HARPY,
    name: 'Harpy',
    nameKr: '하피',
    baseHp: 80,
    baseSpeed: 1.4,
    traits: ['flying'],
    resistances: { fire: 1.0, ice: 1.0, lightning: 1.5, wind: 0.5, earth: 0, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: true,
    minWave: 5,
    goldReward: 12,
    expReward: 7,
    color: '#FB923C',
    icon: '🦅',
  },

  [EnemyType.DRAGON_WHELP]: {
    type: EnemyType.DRAGON_WHELP,
    name: 'Dragon Whelp',
    nameKr: '아기 드래곤',
    baseHp: 120,
    baseSpeed: 1.2,
    traits: ['flying', 'fire'],
    resistances: { fire: 0, ice: 1.5, lightning: 1.0, wind: 1.0, earth: 0, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: true,
    minWave: 10,
    goldReward: 18,
    expReward: 10,
    color: '#F97316',
    icon: '🐉',
    specialAbility: 'fireBreath: 바리케이드에 2배 피해',
  },

  [EnemyType.GARGOYLE]: {
    type: EnemyType.GARGOYLE,
    name: 'Gargoyle',
    nameKr: '가고일',
    baseHp: 160,
    baseSpeed: 0.8,
    traits: ['flying', 'armored'],
    resistances: { fire: 0.8, ice: 0.8, lightning: 1.5, wind: 0.8, earth: 0, light: 1.5, dark: 0.8 },
    isBoss: false,
    isFlying: true,
    minWave: 14,
    goldReward: 20,
    expReward: 12,
    color: '#6B7280',
    icon: '🦇',
    specialAbility: 'stoneForm: HP 25% 이하 시 방어력 2배, 이동속도 절반',
  },

  [EnemyType.PHOENIX_CHICK]: {
    type: EnemyType.PHOENIX_CHICK,
    name: 'Phoenix Chick',
    nameKr: '아기 불사조',
    baseHp: 100,
    baseSpeed: 1.3,
    traits: ['flying', 'fire', 'rebirth'],
    resistances: { fire: 0, ice: 1.5, lightning: 1.0, wind: 1.0, earth: 0, light: 1.0, dark: 1.5 },
    isBoss: false,
    isFlying: true,
    minWave: 18,
    goldReward: 25,
    expReward: 15,
    color: '#F43F5E',
    icon: '🔥',
    specialAbility: 'rebirth: 처음 사망 시 HP 50%로 부활',
  },

  [EnemyType.WYVERN]: {
    type: EnemyType.WYVERN,
    name: 'Wyvern',
    nameKr: '와이번',
    baseHp: 200,
    baseSpeed: 1.6,
    traits: ['flying', 'fast'],
    resistances: { fire: 0.8, ice: 1.5, lightning: 1.0, wind: 0.5, earth: 0, light: 1.0, dark: 1.0 },
    isBoss: false,
    isFlying: true,
    minWave: 20,
    goldReward: 30,
    expReward: 18,
    color: '#0EA5E9',
    icon: '🐲',
    specialAbility: 'diveBomb: 도착 직전 이동속도 3배',
  },

  // ── Boss Enemies ───────────────────────────────────────────

  [EnemyType.DRAGON]: {
    type: EnemyType.DRAGON,
    name: 'Dragon',
    nameKr: '드래곤',
    baseHp: 2000,
    baseSpeed: 0.5,
    traits: ['boss', 'flying', 'fire'],
    resistances: { fire: 0, ice: 1.5, lightning: 0.8, wind: 0.8, earth: 0, light: 1.0, dark: 0.8 },
    isBoss: true,
    isFlying: true,
    minWave: 10,
    goldReward: 100,
    expReward: 50,
    color: '#DC2626',
    icon: '🐉',
    specialAbility: 'fireStorm: 10초마다 모든 타워에 소량 피해',
  },

  [EnemyType.LICH_KING]: {
    type: EnemyType.LICH_KING,
    name: 'Lich King',
    nameKr: '리치킹',
    baseHp: 2500,
    baseSpeed: 0.4,
    traits: ['boss', 'magic', 'undead', 'summon'],
    resistances: { fire: 1.0, ice: 0.5, lightning: 1.0, wind: 1.0, earth: 1.0, light: 1.5, dark: 0 },
    isBoss: true,
    isFlying: false,
    minWave: 20,
    goldReward: 150,
    expReward: 75,
    color: '#4C1D95',
    icon: '👑',
    specialAbility: 'summonUndead: 15초마다 스켈레톤 3마리 소환',
  },

  [EnemyType.DEMON_LORD]: {
    type: EnemyType.DEMON_LORD,
    name: 'Demon Lord',
    nameKr: '마왕',
    baseHp: 3000,
    baseSpeed: 0.6,
    traits: ['boss', 'berserk', 'aura'],
    resistances: { fire: 0.5, ice: 0.5, lightning: 0.5, wind: 0.5, earth: 0.5, light: 1.5, dark: 0 },
    isBoss: true,
    isFlying: false,
    minWave: 30,
    goldReward: 200,
    expReward: 100,
    color: '#7F1D1D',
    icon: '😈',
    specialAbility: 'demonAura: 주변 적 공격력 +30%, HP 30% 이하 시 전 저항 0.3으로 변경',
  },

  [EnemyType.HYDRA]: {
    type: EnemyType.HYDRA,
    name: 'Hydra',
    nameKr: '히드라',
    baseHp: 3500,
    baseSpeed: 0.3,
    traits: ['boss', 'regen', 'multi'],
    resistances: { fire: 1.5, ice: 0.8, lightning: 0.8, wind: 1.0, earth: 0.5, light: 1.0, dark: 1.0 },
    isBoss: true,
    isFlying: false,
    minWave: 40,
    goldReward: 250,
    expReward: 125,
    color: '#166534',
    icon: '🐍',
    specialAbility: 'multiHead: 사망 시 HP 30%짜리 2마리로 분열 (1회), 초당 HP 1% 재생',
  },

  [EnemyType.WORD_DESTROYER]: {
    type: EnemyType.WORD_DESTROYER,
    name: 'Word Destroyer',
    nameKr: '워드 디스트로이어',
    baseHp: 5000,
    baseSpeed: 0.5,
    traits: ['boss', 'magic', 'anti-word'],
    resistances: { fire: 0.8, ice: 0.8, lightning: 0.8, wind: 0.8, earth: 0.8, light: 0.5, dark: 0.5 },
    isBoss: true,
    isFlying: false,
    minWave: 50,
    goldReward: 500,
    expReward: 250,
    color: '#1E1B4B',
    icon: '📕',
    specialAbility: 'wordDisrupt: 퀴즈 시간 절반, 오답 시 타워 1개 3초 비활성화. 단어 타워 피해 50% 감소',
  },
};

// ── Helper: Wave scaling formula ─────────────────────────────

/**
 * Scale enemy HP / speed for a given wave number.
 * HP scales by 1.12^wave, speed scales by 1 + wave * 0.005 (capped at 2x).
 */
export function scaleEnemyForWave(def: EnemyDefinition, wave: number) {
  return {
    hp: Math.round(def.baseHp * Math.pow(1.12, wave - 1)),
    speed: Math.min(def.baseSpeed * (1 + (wave - 1) * 0.005), def.baseSpeed * 2),
  };
}
