import type { WordData, PartOfSpeech } from '../../types/game';

type CW = [string, string, string, number, string];

function expand(words: CW[], startId: number): WordData[] {
  return words.map((w, i) => ({
    id: `g3x_${String(startId + i).padStart(4, '0')}`,
    english: w[0],
    korean: w[1],
    grade: 3 as const,
    category: w[2],
    difficulty: w[3] as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: w[4] as PartOfSpeech,
    exampleSentence: '',
    exampleKorean: '',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  }));
}

const DATA: CW[] = [
  // ── animals (extras not in existing) ──
  ['hen', '암탉', 'animals', 1, 'noun'],
  ['rooster', '수탉', 'animals', 1, 'noun'],
  ['chick', '병아리', 'animals', 1, 'noun'],
  ['puppy', '강아지', 'animals', 1, 'noun'],
  ['kitten', '아기 고양이', 'animals', 1, 'noun'],
  ['calf', '송아지', 'animals', 1, 'noun'],
  ['foal', '망아지', 'animals', 1, 'noun'],
  ['lamb', '새끼 양', 'animals', 1, 'noun'],
  ['piglet', '아기 돼지', 'animals', 1, 'noun'],
  ['cub', '새끼 곰', 'animals', 1, 'noun'],
  ['paw', '발(동물)', 'animals', 1, 'noun'],
  ['tail', '꼬리', 'animals', 1, 'noun'],
  ['wing', '날개', 'animals', 1, 'noun'],
  ['beak', '부리', 'animals', 1, 'noun'],
  ['fur', '털', 'animals', 1, 'noun'],
  ['feather', '깃털', 'animals', 1, 'noun'],
  ['shell', '껍데기', 'animals', 1, 'noun'],
  ['horn', '뿔', 'animals', 1, 'noun'],
  ['claw', '발톱', 'animals', 1, 'noun'],
  ['fin', '지느러미', 'animals', 1, 'noun'],
  ['toad', '두꺼비', 'animals', 1, 'noun'],
  ['lizard', '도마뱀', 'animals', 1, 'noun'],
  ['mole', '두더지', 'animals', 1, 'noun'],
  ['mouse', '생쥐', 'animals', 1, 'noun'],
  ['rat', '쥐', 'animals', 1, 'noun'],
  ['robin', '울새', 'animals', 1, 'noun'],
  ['dove', '비둘기', 'animals', 1, 'noun'],
  ['crow', '까마귀', 'animals', 1, 'noun'],
  ['stork', '황새', 'animals', 1, 'noun'],
  ['crane', '학', 'animals', 1, 'noun'],
  ['heron', '왜가리', 'animals', 1, 'noun'],
  ['seagull', '갈매기', 'animals', 1, 'noun'],
  ['pelican', '펠리컨', 'animals', 1, 'noun'],
  ['toucan', '큰부리새', 'animals', 1, 'noun'],
  ['woodpecker', '딱따구리', 'animals', 2, 'noun'],
  ['swallow', '제비', 'animals', 1, 'noun'],
  ['magpie', '까치', 'animals', 1, 'noun'],
  ['jay', '어치', 'animals', 1, 'noun'],
  ['finch', '되새', 'animals', 1, 'noun'],
  ['wren', '굴뚝새', 'animals', 1, 'noun'],
  ['clam', '조개', 'animals', 1, 'noun'],
  ['oyster', '굴', 'animals', 1, 'noun'],
  ['shrimp', '새우', 'animals', 1, 'noun'],
  ['lobster', '바닷가재', 'animals', 2, 'noun'],
  ['squid', '오징어', 'animals', 1, 'noun'],
  ['jellyfish', '해파리', 'animals', 1, 'noun'],
  ['ray', '가오리', 'animals', 1, 'noun'],
  ['eel', '뱀장어', 'animals', 1, 'noun'],
  ['tuna', '참치', 'animals', 1, 'noun'],
  ['salmon', '연어', 'animals', 1, 'noun'],
  ['trout', '송어', 'animals', 1, 'noun'],
  ['pike', '창꼬치', 'animals', 1, 'noun'],
  ['bass', '농어', 'animals', 1, 'noun'],
  ['moth', '나방', 'animals', 1, 'noun'],
  ['cricket', '귀뚜라미', 'animals', 1, 'noun'],
  ['grasshopper', '메뚜기', 'animals', 2, 'noun'],
  ['dragonfly', '잠자리', 'animals', 1, 'noun'],
  ['firefly', '반딧불이', 'animals', 1, 'noun'],
  ['wasp', '말벌', 'animals', 1, 'noun'],
  ['hornet', '장수말벌', 'animals', 1, 'noun'],
  ['scorpion', '전갈', 'animals', 2, 'noun'],
  ['centipede', '지네', 'animals', 2, 'noun'],
  ['tick', '진드기', 'animals', 1, 'noun'],
  ['flea', '벼룩', 'animals', 1, 'noun'],
  ['louse', '이', 'animals', 1, 'noun'],
  ['porcupine', '호저', 'animals', 2, 'noun'],
  ['badger', '오소리', 'animals', 1, 'noun'],
  ['beaver', '비버', 'animals', 1, 'noun'],
  ['chipmunk', '다람쥐', 'animals', 2, 'noun'],
  ['gopher', '땅다람쥐', 'animals', 2, 'noun'],
  ['skunk', '스컹크', 'animals', 1, 'noun'],
  ['weasel', '족제비', 'animals', 1, 'noun'],
  ['ferret', '흰족제비', 'animals', 1, 'noun'],
  ['mink', '밍크', 'animals', 1, 'noun'],
  ['moose', '큰사슴', 'animals', 1, 'noun'],
  ['elk', '엘크', 'animals', 1, 'noun'],
  ['reindeer', '순록', 'animals', 2, 'noun'],
  ['bison', '들소', 'animals', 1, 'noun'],
  ['buffalo', '물소', 'animals', 2, 'noun'],
  ['yak', '야크', 'animals', 1, 'noun'],
  ['llama', '라마', 'animals', 1, 'noun'],
  ['alpaca', '알파카', 'animals', 2, 'noun'],
  ['jaguar', '재규어', 'animals', 2, 'noun'],
  ['panther', '표범', 'animals', 2, 'noun'],
  ['cougar', '퓨마', 'animals', 2, 'noun'],
  ['lynx', '스라소니', 'animals', 1, 'noun'],
  ['bobcat', '붉은스라소니', 'animals', 2, 'noun'],
  ['hyena', '하이에나', 'animals', 2, 'noun'],
  ['jackal', '자칼', 'animals', 2, 'noun'],
  ['coyote', '코요테', 'animals', 2, 'noun'],
  ['vulture', '독수리', 'animals', 2, 'noun'],
  ['falcon', '매', 'animals', 2, 'noun'],
  ['osprey', '물수리', 'animals', 2, 'noun'],
  ['condor', '콘도르', 'animals', 2, 'noun'],
  ['albatross', '알바트로스', 'animals', 2, 'noun'],
  ['puffin', '퍼핀', 'animals', 2, 'noun'],
  ['iguana', '이구아나', 'animals', 2, 'noun'],
  ['chameleon', '카멜레온', 'animals', 2, 'noun'],
  ['gecko', '도마뱀붙이', 'animals', 2, 'noun'],
  ['cobra', '코브라', 'animals', 2, 'noun'],
  ['viper', '독사', 'animals', 2, 'noun'],
  ['python', '비단뱀', 'animals', 2, 'noun'],
  ['boa', '보아뱀', 'animals', 1, 'noun'],
  ['alligator', '악어', 'animals', 2, 'noun'],
  ['tortoise', '육지거북', 'animals', 2, 'noun'],
  ['newt', '영원', 'animals', 1, 'noun'],
  ['salamander', '도롱뇽', 'animals', 2, 'noun'],
  ['manatee', '매너티', 'animals', 2, 'noun'],
  ['walrus', '바다코끼리', 'animals', 2, 'noun'],
  ['narwhal', '일각고래', 'animals', 2, 'noun'],
  ['orca', '범고래', 'animals', 2, 'noun'],
  ['porpoise', '쇠돌고래', 'animals', 2, 'noun'],
  ['stingray', '가오리', 'animals', 2, 'noun'],
  ['swordfish', '황새치', 'animals', 2, 'noun'],
  ['seahorse', '해마', 'animals', 2, 'noun'],
  ['starfish', '불가사리', 'animals', 2, 'noun'],
  ['sea urchin', '성게', 'animals', 2, 'noun'],
  ['coral', '산호', 'animals', 1, 'noun'],
  ['sponge', '해면', 'animals', 1, 'noun'],
  ['slug', '민달팽이', 'animals', 1, 'noun'],
  ['leech', '거머리', 'animals', 1, 'noun'],
  ['earthworm', '지렁이', 'animals', 2, 'noun'],
  ['silkworm', '누에', 'animals', 2, 'noun'],
  ['cocoon', '고치', 'animals', 2, 'noun'],
  ['larva', '유충', 'animals', 2, 'noun'],
  ['pupa', '번데기', 'animals', 1, 'noun'],
  ['termite', '흰개미', 'animals', 2, 'noun'],
  ['cockroach', '바퀴벌레', 'animals', 2, 'noun'],
  ['mantis', '사마귀', 'animals', 2, 'noun'],
  ['cicada', '매미', 'animals', 2, 'noun'],
  ['locust', '메뚜기떼', 'animals', 2, 'noun'],
  ['aphid', '진딧물', 'animals', 2, 'noun'],

  // ── food (extras) ──
  ['rice', '쌀', 'food', 1, 'noun'],
  ['bread', '빵', 'food', 1, 'noun'],
  ['milk', '우유', 'food', 1, 'noun'],
  ['egg', '달걀', 'food', 1, 'noun'],
  ['soup', '수프', 'food', 1, 'noun'],
  ['salad', '샐러드', 'food', 1, 'noun'],
  ['pizza', '피자', 'food', 1, 'noun'],
  ['pasta', '파스타', 'food', 1, 'noun'],
  ['burger', '버거', 'food', 1, 'noun'],
  ['sandwich', '샌드위치', 'food', 1, 'noun'],
  ['pie', '파이', 'food', 1, 'noun'],
  ['jam', '잼', 'food', 1, 'noun'],
  ['juice', '주스', 'food', 1, 'noun'],
  ['tea', '차', 'food', 1, 'noun'],
  ['water', '물', 'food', 1, 'noun'],
  ['grape', '포도', 'food', 1, 'noun'],
  ['peach', '복숭아', 'food', 1, 'noun'],
  ['pear', '배', 'food', 1, 'noun'],
  ['cherry', '체리', 'food', 1, 'noun'],
  ['plum', '자두', 'food', 1, 'noun'],
  ['coconut', '코코넛', 'food', 1, 'noun'],
  ['corn', '옥수수', 'food', 1, 'noun'],
  ['potato', '감자', 'food', 1, 'noun'],
  ['tomato', '토마토', 'food', 1, 'noun'],
  ['carrot', '당근', 'food', 1, 'noun'],
  ['onion', '양파', 'food', 1, 'noun'],
  ['cucumber', '오이', 'food', 1, 'noun'],
  ['lettuce', '상추', 'food', 1, 'noun'],
  ['pepper', '후추', 'food', 1, 'noun'],
  ['mushroom', '버섯', 'food', 1, 'noun'],
  ['garlic', '마늘', 'food', 1, 'noun'],
  ['pea', '완두콩', 'food', 1, 'noun'],
  ['nut', '견과류', 'food', 1, 'noun'],
  ['honey', '꿀', 'food', 1, 'noun'],
  ['sugar', '설탕', 'food', 1, 'noun'],
  ['salt', '소금', 'food', 1, 'noun'],
  ['meat', '고기', 'food', 1, 'noun'],
  ['chicken', '닭고기', 'food', 1, 'noun'],
  ['pork', '돼지고기', 'food', 1, 'noun'],
  ['beef', '쇠고기', 'food', 1, 'noun'],
  ['ham', '햄', 'food', 1, 'noun'],
  ['sausage', '소시지', 'food', 1, 'noun'],
  ['noodle', '국수', 'food', 1, 'noun'],
  ['dumpling', '만두', 'food', 1, 'noun'],
  ['tofu', '두부', 'food', 1, 'noun'],
  ['flour', '밀가루', 'food', 1, 'noun'],
  ['dough', '반죽', 'food', 1, 'noun'],
  ['syrup', '시럽', 'food', 1, 'noun'],
  ['vinegar', '식초', 'food', 2, 'noun'],
  ['sauce', '소스', 'food', 1, 'noun'],
  ['ketchup', '케첩', 'food', 1, 'noun'],
  ['mustard', '겨자', 'food', 2, 'noun'],
  ['mayo', '마요네즈', 'food', 1, 'noun'],
  ['gravy', '고기즙 소스', 'food', 2, 'noun'],
  ['broth', '육수', 'food', 1, 'noun'],
  ['stew', '스튜', 'food', 1, 'noun'],
  ['roast', '구이', 'food', 1, 'noun'],
  ['grill', '그릴', 'food', 1, 'noun'],
  ['fry', '튀기다', 'food', 1, 'verb'],
  ['boil', '끓이다', 'food', 1, 'verb'],
  ['bake', '굽다', 'food', 1, 'verb'],
  ['chop', '썰다', 'food', 1, 'verb'],
  ['peel', '껍질을 벗기다', 'food', 1, 'verb'],
  ['slice', '얇게 썰다', 'food', 1, 'verb'],
  ['mix', '섞다', 'food', 1, 'verb'],
  ['stir', '젓다', 'food', 1, 'verb'],
  ['pour', '따르다', 'food', 1, 'verb'],
  ['spread', '바르다', 'food', 1, 'verb'],
  ['sip', '홀짝이다', 'food', 1, 'verb'],
  ['chew', '씹다', 'food', 1, 'verb'],
  ['swallow', '삼키다', 'food', 1, 'verb'],
  ['bite', '물다', 'food', 1, 'verb'],
  ['lick', '핥다', 'food', 1, 'verb'],
  ['feast', '잔치', 'food', 1, 'noun'],
  ['snack', '간식', 'food', 1, 'noun'],
  ['meal', '식사', 'food', 1, 'noun'],
  ['dish', '요리', 'food', 1, 'noun'],
  ['plate', '접시', 'food', 1, 'noun'],
  ['bowl', '그릇', 'food', 1, 'noun'],
  ['cup', '컵', 'food', 1, 'noun'],
  ['glass', '유리잔', 'food', 1, 'noun'],
  ['fork', '포크', 'food', 1, 'noun'],
  ['spoon', '숟가락', 'food', 1, 'noun'],
  ['knife', '칼', 'food', 1, 'noun'],
  ['chopsticks', '젓가락', 'food', 2, 'noun'],
  ['napkin', '냅킨', 'food', 1, 'noun'],
  ['recipe', '조리법', 'food', 2, 'noun'],
  ['menu', '메뉴', 'food', 1, 'noun'],
  ['order', '주문', 'food', 1, 'noun'],
  ['tip', '팁', 'food', 1, 'noun'],
  ['buffet', '뷔페', 'food', 2, 'noun'],
  ['dessert', '디저트', 'food', 2, 'noun'],
  ['snack bar', '분식점', 'food', 2, 'noun'],
  ['cafeteria', '구내식당', 'food', 2, 'noun'],

  // ── colors (extras) ──
  ['red', '빨간색', 'colors', 1, 'noun'],
  ['blue', '파란색', 'colors', 1, 'noun'],
  ['green', '초록색', 'colors', 1, 'noun'],
  ['yellow', '노란색', 'colors', 1, 'noun'],
  ['white', '하얀색', 'colors', 1, 'noun'],
  ['black', '검은색', 'colors', 1, 'noun'],
  ['pink', '분홍색', 'colors', 1, 'noun'],
  ['purple', '보라색', 'colors', 1, 'noun'],
  ['brown', '갈색', 'colors', 1, 'noun'],
  ['gray', '회색', 'colors', 1, 'noun'],
  ['tan', '황갈색', 'colors', 1, 'noun'],
  ['peach', '복숭아색', 'colors', 1, 'noun'],
  ['coral', '산호색', 'colors', 1, 'noun'],
  ['salmon', '연어색', 'colors', 2, 'noun'],
  ['rust', '녹색(붉은)', 'colors', 1, 'noun'],
  ['bronze', '청동색', 'colors', 2, 'noun'],
  ['copper', '구리색', 'colors', 2, 'noun'],
  ['cream', '크림색', 'colors', 1, 'noun'],
  ['khaki', '카키색', 'colors', 2, 'noun'],
  ['lime', '라임색', 'colors', 1, 'noun'],
  ['mint', '민트색', 'colors', 1, 'noun'],
  ['olive', '올리브색', 'colors', 2, 'noun'],
  ['plum', '자두색', 'colors', 1, 'noun'],
  ['lilac', '라일락색', 'colors', 2, 'noun'],
  ['lavender', '라벤더색', 'colors', 2, 'noun'],
  ['ruby', '루비색', 'colors', 2, 'noun'],
  ['jade', '옥색', 'colors', 2, 'noun'],
  ['amber', '호박색', 'colors', 2, 'noun'],
  ['charcoal', '숯색', 'colors', 2, 'noun'],
  ['pearl', '진주색', 'colors', 2, 'noun'],

  // ── numbers ──
  ['one', '하나', 'numbers', 1, 'noun'],
  ['two', '둘', 'numbers', 1, 'noun'],
  ['three', '셋', 'numbers', 1, 'noun'],
  ['four', '넷', 'numbers', 1, 'noun'],
  ['five', '다섯', 'numbers', 1, 'noun'],
  ['six', '여섯', 'numbers', 1, 'noun'],
  ['seven', '일곱', 'numbers', 1, 'noun'],
  ['eight', '여덟', 'numbers', 1, 'noun'],
  ['nine', '아홉', 'numbers', 1, 'noun'],
  ['ten', '열', 'numbers', 1, 'noun'],
  ['eleven', '열하나', 'numbers', 1, 'noun'],
  ['twelve', '열둘', 'numbers', 1, 'noun'],
  ['thirteen', '열셋', 'numbers', 1, 'noun'],
  ['fourteen', '열넷', 'numbers', 1, 'noun'],
  ['fifteen', '열다섯', 'numbers', 1, 'noun'],
  ['sixteen', '열여섯', 'numbers', 1, 'noun'],
  ['seventeen', '열일곱', 'numbers', 1, 'noun'],
  ['eighteen', '열여덟', 'numbers', 1, 'noun'],
  ['nineteen', '열아홉', 'numbers', 1, 'noun'],
  ['twenty', '스물', 'numbers', 1, 'noun'],
  ['thirty', '서른', 'numbers', 1, 'noun'],
  ['forty', '마흔', 'numbers', 1, 'noun'],
  ['fifty', '쉰', 'numbers', 1, 'noun'],
  ['sixty', '예순', 'numbers', 1, 'noun'],
  ['seventy', '일흔', 'numbers', 1, 'noun'],
  ['eighty', '여든', 'numbers', 1, 'noun'],
  ['ninety', '아흔', 'numbers', 1, 'noun'],
  ['hundred', '백', 'numbers', 1, 'noun'],
  ['thousand', '천', 'numbers', 1, 'noun'],
  ['million', '백만', 'numbers', 2, 'noun'],
  ['billion', '십억', 'numbers', 2, 'noun'],
  ['dozen', '열두 개', 'numbers', 2, 'noun'],
  ['pair', '한 쌍', 'numbers', 1, 'noun'],
  ['half', '반', 'numbers', 1, 'noun'],
  ['quarter', '사분의 일', 'numbers', 2, 'noun'],
  ['double', '두 배', 'numbers', 1, 'adjective'],
  ['triple', '세 배', 'numbers', 2, 'adjective'],
  ['single', '하나의', 'numbers', 1, 'adjective'],
  ['once', '한 번', 'numbers', 1, 'adverb'],
  ['twice', '두 번', 'numbers', 1, 'adverb'],

  // ── family ──
  ['mother', '어머니', 'family', 1, 'noun'],
  ['father', '아버지', 'family', 1, 'noun'],
  ['sister', '언니/누나/여동생', 'family', 1, 'noun'],
  ['brother', '형/오빠/남동생', 'family', 1, 'noun'],
  ['baby', '아기', 'family', 1, 'noun'],
  ['grandma', '할머니', 'family', 1, 'noun'],
  ['grandpa', '할아버지', 'family', 1, 'noun'],
  ['aunt', '이모/고모', 'family', 1, 'noun'],
  ['uncle', '삼촌/외삼촌', 'family', 1, 'noun'],
  ['cousin', '사촌', 'family', 1, 'noun'],
  ['son', '아들', 'family', 1, 'noun'],
  ['daughter', '딸', 'family', 1, 'noun'],
  ['husband', '남편', 'family', 1, 'noun'],
  ['wife', '아내', 'family', 1, 'noun'],
  ['parent', '부모', 'family', 1, 'noun'],
  ['child', '아이', 'family', 1, 'noun'],
  ['friend', '친구', 'family', 1, 'noun'],
  ['neighbor', '이웃', 'family', 2, 'noun'],
  ['pet', '반려동물', 'family', 1, 'noun'],
  ['nephew', '조카(남)', 'family', 2, 'noun'],
  ['niece', '조카(여)', 'family', 2, 'noun'],
  ['twin', '쌍둥이', 'family', 1, 'noun'],
  ['bride', '신부', 'family', 2, 'noun'],
  ['groom', '신랑', 'family', 2, 'noun'],
  ['wedding', '결혼식', 'family', 2, 'noun'],
  ['couple', '부부', 'family', 2, 'noun'],
  ['relative', '친척', 'family', 2, 'noun'],
  ['ancestor', '조상', 'family', 2, 'noun'],
  ['generation', '세대', 'family', 2, 'noun'],
  ['orphan', '고아', 'family', 2, 'noun'],

  // ── body ──
  ['head', '머리', 'body', 1, 'noun'],
  ['face', '얼굴', 'body', 1, 'noun'],
  ['eye', '눈', 'body', 1, 'noun'],
  ['nose', '코', 'body', 1, 'noun'],
  ['mouth', '입', 'body', 1, 'noun'],
  ['ear', '귀', 'body', 1, 'noun'],
  ['hair', '머리카락', 'body', 1, 'noun'],
  ['hand', '손', 'body', 1, 'noun'],
  ['finger', '손가락', 'body', 1, 'noun'],
  ['arm', '팔', 'body', 1, 'noun'],
  ['leg', '다리', 'body', 1, 'noun'],
  ['foot', '발', 'body', 1, 'noun'],
  ['toe', '발가락', 'body', 1, 'noun'],
  ['neck', '목', 'body', 1, 'noun'],
  ['shoulder', '어깨', 'body', 1, 'noun'],
  ['back', '등', 'body', 1, 'noun'],
  ['stomach', '배', 'body', 1, 'noun'],
  ['knee', '무릎', 'body', 1, 'noun'],
  ['tooth', '이', 'body', 1, 'noun'],
  ['tongue', '혀', 'body', 1, 'noun'],
  ['lip', '입술', 'body', 1, 'noun'],
  ['chin', '턱', 'body', 1, 'noun'],
  ['elbow', '팔꿈치', 'body', 1, 'noun'],
  ['wrist', '손목', 'body', 1, 'noun'],
  ['ankle', '발목', 'body', 1, 'noun'],
  ['thumb', '엄지', 'body', 1, 'noun'],
  ['heart', '심장', 'body', 1, 'noun'],
  ['bone', '뼈', 'body', 1, 'noun'],
  ['skin', '피부', 'body', 1, 'noun'],
  ['blood', '피', 'body', 1, 'noun'],
  ['brain', '뇌', 'body', 1, 'noun'],
  ['muscle', '근육', 'body', 1, 'noun'],
  ['lung', '폐', 'body', 1, 'noun'],
  ['liver', '간', 'body', 2, 'noun'],
  ['kidney', '콩팥', 'body', 2, 'noun'],
  ['rib', '갈비뼈', 'body', 2, 'noun'],
  ['spine', '척추', 'body', 2, 'noun'],
  ['skull', '두개골', 'body', 2, 'noun'],
  ['jaw', '턱뼈', 'body', 2, 'noun'],
  ['palm', '손바닥', 'body', 1, 'noun'],
  ['heel', '발뒤꿈치', 'body', 1, 'noun'],
  ['forehead', '이마', 'body', 1, 'noun'],
  ['eyebrow', '눈썹', 'body', 1, 'noun'],
  ['eyelash', '속눈썹', 'body', 2, 'noun'],
  ['cheek', '볼', 'body', 1, 'noun'],
  ['nostril', '콧구멍', 'body', 2, 'noun'],
  ['vein', '정맥', 'body', 2, 'noun'],
  ['nerve', '신경', 'body', 2, 'noun'],
  ['joint', '관절', 'body', 2, 'noun'],
  ['tendon', '힘줄', 'body', 2, 'noun'],

  // ── school ──
  ['book', '책', 'school', 1, 'noun'],
  ['pen', '펜', 'school', 1, 'noun'],
  ['pencil', '연필', 'school', 1, 'noun'],
  ['eraser', '지우개', 'school', 1, 'noun'],
  ['ruler', '자', 'school', 1, 'noun'],
  ['desk', '책상', 'school', 1, 'noun'],
  ['chair', '의자', 'school', 1, 'noun'],
  ['board', '칠판', 'school', 1, 'noun'],
  ['class', '수업', 'school', 1, 'noun'],
  ['teacher', '선생님', 'school', 1, 'noun'],
  ['student', '학생', 'school', 1, 'noun'],
  ['school', '학교', 'school', 1, 'noun'],
  ['bag', '가방', 'school', 1, 'noun'],
  ['notebook', '공책', 'school', 1, 'noun'],
  ['crayon', '크레용', 'school', 1, 'noun'],
  ['paper', '종이', 'school', 1, 'noun'],
  ['scissors', '가위', 'school', 1, 'noun'],
  ['glue', '풀', 'school', 1, 'noun'],
  ['tape', '테이프', 'school', 1, 'noun'],
  ['clock', '시계', 'school', 1, 'noun'],
  ['calendar', '달력', 'school', 1, 'noun'],
  ['map', '지도', 'school', 1, 'noun'],
  ['test', '시험', 'school', 1, 'noun'],
  ['grade', '학년', 'school', 1, 'noun'],
  ['homework', '숙제', 'school', 1, 'noun'],
  ['lesson', '수업', 'school', 1, 'noun'],
  ['math', '수학', 'school', 1, 'noun'],
  ['science', '과학', 'school', 1, 'noun'],
  ['art', '미술', 'school', 1, 'noun'],
  ['music', '음악', 'school', 1, 'noun'],
  ['gym', '체육관', 'school', 1, 'noun'],
  ['lunch', '점심', 'school', 1, 'noun'],
  ['recess', '쉬는 시간', 'school', 1, 'noun'],
  ['library', '도서관', 'school', 1, 'noun'],
  ['classroom', '교실', 'school', 1, 'noun'],
  ['hallway', '복도', 'school', 1, 'noun'],
  ['playground', '운동장', 'school', 1, 'noun'],
  ['bell', '종', 'school', 1, 'noun'],
  ['quiz', '퀴즈', 'school', 1, 'noun'],
  ['exam', '시험', 'school', 1, 'noun'],
  ['report', '보고서', 'school', 2, 'noun'],
  ['project', '프로젝트', 'school', 2, 'noun'],
  ['textbook', '교과서', 'school', 1, 'noun'],
  ['dictionary', '사전', 'school', 2, 'noun'],
  ['alphabet', '알파벳', 'school', 2, 'noun'],
  ['sentence', '문장', 'school', 2, 'noun'],
  ['paragraph', '문단', 'school', 2, 'noun'],
  ['spelling', '맞춤법', 'school', 2, 'noun'],
  ['reading', '읽기', 'school', 1, 'noun'],
  ['writing', '쓰기', 'school', 1, 'noun'],
  ['counting', '세기', 'school', 1, 'noun'],
  ['addition', '덧셈', 'school', 1, 'noun'],
  ['subtraction', '뺄셈', 'school', 1, 'noun'],
  ['multiplication', '곱셈', 'school', 2, 'noun'],
  ['division', '나눗셈', 'school', 2, 'noun'],
  ['answer', '답', 'school', 1, 'noun'],
  ['question', '질문', 'school', 1, 'noun'],
  ['problem', '문제', 'school', 1, 'noun'],
  ['solve', '풀다', 'school', 1, 'verb'],
  ['study', '공부하다', 'school', 1, 'verb'],
  ['learn', '배우다', 'school', 1, 'verb'],
  ['teach', '가르치다', 'school', 1, 'verb'],
  ['read', '읽다', 'school', 1, 'verb'],
  ['write', '쓰다', 'school', 1, 'verb'],
  ['draw', '그리다', 'school', 1, 'verb'],
  ['count', '세다', 'school', 1, 'verb'],
  ['color', '색칠하다', 'school', 1, 'verb'],
  ['paste', '붙이다', 'school', 1, 'verb'],
  ['copy', '베끼다', 'school', 1, 'verb'],
  ['erase', '지우다', 'school', 1, 'verb'],
  ['sharpen', '깎다', 'school', 2, 'verb'],
  ['practice', '연습하다', 'school', 2, 'verb'],
  ['present', '발표하다', 'school', 2, 'verb'],
  ['absent', '결석한', 'school', 2, 'adjective'],

  // ── clothes ──
  ['shirt', '셔츠', 'clothes', 1, 'noun'],
  ['pants', '바지', 'clothes', 1, 'noun'],
  ['dress', '드레스', 'clothes', 1, 'noun'],
  ['skirt', '치마', 'clothes', 1, 'noun'],
  ['shoes', '신발', 'clothes', 1, 'noun'],
  ['socks', '양말', 'clothes', 1, 'noun'],
  ['hat', '모자', 'clothes', 1, 'noun'],
  ['coat', '외투', 'clothes', 1, 'noun'],
  ['jacket', '재킷', 'clothes', 1, 'noun'],
  ['scarf', '목도리', 'clothes', 1, 'noun'],
  ['glove', '장갑', 'clothes', 1, 'noun'],
  ['belt', '벨트', 'clothes', 1, 'noun'],
  ['tie', '넥타이', 'clothes', 1, 'noun'],
  ['uniform', '교복', 'clothes', 1, 'noun'],
  ['sweater', '스웨터', 'clothes', 1, 'noun'],
  ['jeans', '청바지', 'clothes', 1, 'noun'],
  ['shorts', '반바지', 'clothes', 1, 'noun'],
  ['boots', '부츠', 'clothes', 1, 'noun'],
  ['sandals', '샌들', 'clothes', 1, 'noun'],
  ['pajamas', '잠옷', 'clothes', 1, 'noun'],
  ['raincoat', '비옷', 'clothes', 1, 'noun'],
  ['pocket', '주머니', 'clothes', 1, 'noun'],
  ['button', '단추', 'clothes', 1, 'noun'],
  ['zipper', '지퍼', 'clothes', 1, 'noun'],
  ['collar', '칼라', 'clothes', 1, 'noun'],
  ['sleeve', '소매', 'clothes', 1, 'noun'],
  ['hood', '후드', 'clothes', 1, 'noun'],
  ['apron', '앞치마', 'clothes', 1, 'noun'],
  ['vest', '조끼', 'clothes', 1, 'noun'],
  ['robe', '가운', 'clothes', 1, 'noun'],
  ['costume', '의상', 'clothes', 2, 'noun'],
  ['helmet', '헬멧', 'clothes', 2, 'noun'],
  ['mask', '마스크', 'clothes', 1, 'noun'],
  ['ribbon', '리본', 'clothes', 1, 'noun'],
  ['lace', '레이스', 'clothes', 2, 'noun'],
  ['fabric', '천', 'clothes', 2, 'noun'],
  ['thread', '실', 'clothes', 1, 'noun'],
  ['needle', '바늘', 'clothes', 1, 'noun'],
  ['sew', '바느질하다', 'clothes', 1, 'verb'],
  ['knit', '뜨개질하다', 'clothes', 2, 'verb'],
  ['wear', '입다', 'clothes', 1, 'verb'],
  ['put on', '입다/신다', 'clothes', 1, 'verb'],
  ['take off', '벗다', 'clothes', 1, 'verb'],
  ['try on', '입어보다', 'clothes', 1, 'verb'],
  ['iron', '다림질하다', 'clothes', 2, 'verb'],
  ['fold', '접다', 'clothes', 1, 'verb'],
  ['hang up', '걸다', 'clothes', 1, 'verb'],

  // ── nature ──
  ['tree', '나무', 'nature', 1, 'noun'],
  ['flower', '꽃', 'nature', 1, 'noun'],
  ['grass', '잔디', 'nature', 1, 'noun'],
  ['leaf', '잎', 'nature', 1, 'noun'],
  ['sun', '태양', 'nature', 1, 'noun'],
  ['moon', '달', 'nature', 1, 'noun'],
  ['star', '별', 'nature', 1, 'noun'],
  ['sky', '하늘', 'nature', 1, 'noun'],
  ['cloud', '구름', 'nature', 1, 'noun'],
  ['rain', '비', 'nature', 1, 'noun'],
  ['snow', '눈', 'nature', 1, 'noun'],
  ['wind', '바람', 'nature', 1, 'noun'],
  ['river', '강', 'nature', 1, 'noun'],
  ['lake', '호수', 'nature', 1, 'noun'],
  ['sea', '바다', 'nature', 1, 'noun'],
  ['mountain', '산', 'nature', 1, 'noun'],
  ['hill', '언덕', 'nature', 1, 'noun'],
  ['forest', '숲', 'nature', 1, 'noun'],
  ['garden', '정원', 'nature', 1, 'noun'],
  ['rock', '바위', 'nature', 1, 'noun'],
  ['sand', '모래', 'nature', 1, 'noun'],
  ['mud', '진흙', 'nature', 1, 'noun'],
  ['island', '섬', 'nature', 1, 'noun'],
  ['cave', '동굴', 'nature', 1, 'noun'],
  ['waterfall', '폭포', 'nature', 1, 'noun'],
  ['pond', '연못', 'nature', 1, 'noun'],
  ['stream', '시내', 'nature', 1, 'noun'],
  ['spring', '샘', 'nature', 1, 'noun'],
  ['valley', '골짜기', 'nature', 1, 'noun'],
  ['cliff', '절벽', 'nature', 1, 'noun'],
  ['shore', '해변', 'nature', 1, 'noun'],
  ['tide', '조수', 'nature', 2, 'noun'],
  ['wave', '파도', 'nature', 1, 'noun'],
  ['current', '해류', 'nature', 2, 'noun'],
  ['bush', '덤불', 'nature', 1, 'noun'],
  ['vine', '덩굴', 'nature', 1, 'noun'],
  ['root', '뿌리', 'nature', 1, 'noun'],
  ['branch', '가지', 'nature', 1, 'noun'],
  ['trunk', '줄기', 'nature', 1, 'noun'],
  ['bark', '나무껍질', 'nature', 1, 'noun'],
  ['seed', '씨앗', 'nature', 1, 'noun'],
  ['bud', '꽃봉오리', 'nature', 1, 'noun'],
  ['petal', '꽃잎', 'nature', 2, 'noun'],
  ['stem', '줄기', 'nature', 1, 'noun'],
  ['thorn', '가시', 'nature', 1, 'noun'],
  ['moss', '이끼', 'nature', 1, 'noun'],
  ['fern', '고사리', 'nature', 2, 'noun'],
  ['pine', '소나무', 'nature', 1, 'noun'],
  ['oak', '떡갈나무', 'nature', 1, 'noun'],
  ['maple', '단풍나무', 'nature', 2, 'noun'],
  ['willow', '버드나무', 'nature', 2, 'noun'],
  ['palm', '야자나무', 'nature', 1, 'noun'],
  ['bamboo', '대나무', 'nature', 2, 'noun'],
  ['cactus', '선인장', 'nature', 2, 'noun'],
  ['rose', '장미', 'nature', 1, 'noun'],
  ['daisy', '데이지', 'nature', 1, 'noun'],
  ['tulip', '튤립', 'nature', 1, 'noun'],
  ['lily', '백합', 'nature', 1, 'noun'],
  ['sunflower', '해바라기', 'nature', 2, 'noun'],
  ['orchid', '난초', 'nature', 2, 'noun'],
  ['violet', '제비꽃', 'nature', 1, 'noun'],
  ['dandelion', '민들레', 'nature', 2, 'noun'],
  ['clover', '클로버', 'nature', 2, 'noun'],
  ['ivy', '담쟁이', 'nature', 1, 'noun'],
  ['weed', '잡초', 'nature', 1, 'noun'],
  ['herb', '허브', 'nature', 1, 'noun'],

  // ── weather ──
  ['hot', '더운', 'weather', 1, 'adjective'],
  ['cold', '추운', 'weather', 1, 'adjective'],
  ['warm', '따뜻한', 'weather', 1, 'adjective'],
  ['cool', '시원한', 'weather', 1, 'adjective'],
  ['sunny', '맑은', 'weather', 1, 'adjective'],
  ['rainy', '비 오는', 'weather', 1, 'adjective'],
  ['cloudy', '흐린', 'weather', 1, 'adjective'],
  ['windy', '바람 부는', 'weather', 1, 'adjective'],
  ['snowy', '눈 오는', 'weather', 1, 'adjective'],
  ['foggy', '안개 낀', 'weather', 1, 'adjective'],
  ['stormy', '폭풍우의', 'weather', 2, 'adjective'],
  ['rainbow', '무지개', 'weather', 1, 'noun'],
  ['thunder', '천둥', 'weather', 1, 'noun'],
  ['lightning', '번개', 'weather', 1, 'noun'],
  ['ice', '얼음', 'weather', 1, 'noun'],
  ['frost', '서리', 'weather', 1, 'noun'],
  ['hail', '우박', 'weather', 2, 'noun'],
  ['sleet', '진눈깨비', 'weather', 2, 'noun'],
  ['drizzle', '이슬비', 'weather', 2, 'noun'],
  ['shower', '소나기', 'weather', 1, 'noun'],
  ['blizzard', '눈보라', 'weather', 2, 'noun'],
  ['hurricane', '허리케인', 'weather', 2, 'noun'],
  ['tornado', '토네이도', 'weather', 2, 'noun'],
  ['typhoon', '태풍', 'weather', 2, 'noun'],
  ['breeze', '산들바람', 'weather', 2, 'noun'],
  ['gust', '돌풍', 'weather', 2, 'noun'],
  ['drought', '가뭄', 'weather', 2, 'noun'],
  ['flood', '홍수', 'weather', 1, 'noun'],
  ['umbrella', '우산', 'weather', 1, 'noun'],
  ['temperature', '기온', 'weather', 2, 'noun'],
  ['forecast', '일기예보', 'weather', 2, 'noun'],
  ['season', '계절', 'weather', 1, 'noun'],
  ['spring', '봄', 'weather', 1, 'noun'],
  ['summer', '여름', 'weather', 1, 'noun'],
  ['autumn', '가을', 'weather', 1, 'noun'],
  ['winter', '겨울', 'weather', 1, 'noun'],
  ['humid', '습한', 'weather', 2, 'adjective'],
  ['dry', '건조한', 'weather', 1, 'adjective'],
  ['wet', '젖은', 'weather', 1, 'adjective'],
  ['freeze', '얼다', 'weather', 1, 'verb'],
  ['melt', '녹다', 'weather', 1, 'verb'],
  ['shine', '빛나다', 'weather', 1, 'verb'],
  ['blow', '불다', 'weather', 1, 'verb'],

  // ── feelings ──
  ['happy', '행복한', 'feelings', 1, 'adjective'],
  ['sad', '슬픈', 'feelings', 1, 'adjective'],
  ['angry', '화난', 'feelings', 1, 'adjective'],
  ['scared', '무서운', 'feelings', 1, 'adjective'],
  ['surprised', '놀란', 'feelings', 1, 'adjective'],
  ['excited', '신나는', 'feelings', 1, 'adjective'],
  ['tired', '피곤한', 'feelings', 1, 'adjective'],
  ['bored', '지루한', 'feelings', 1, 'adjective'],
  ['worried', '걱정하는', 'feelings', 1, 'adjective'],
  ['proud', '자랑스러운', 'feelings', 1, 'adjective'],
  ['shy', '수줍은', 'feelings', 1, 'adjective'],
  ['lonely', '외로운', 'feelings', 1, 'adjective'],
  ['jealous', '질투하는', 'feelings', 2, 'adjective'],
  ['nervous', '긴장한', 'feelings', 1, 'adjective'],
  ['confused', '혼란스러운', 'feelings', 2, 'adjective'],
  ['grateful', '감사하는', 'feelings', 2, 'adjective'],
  ['calm', '차분한', 'feelings', 1, 'adjective'],
  ['brave', '용감한', 'feelings', 1, 'adjective'],
  ['kind', '친절한', 'feelings', 1, 'adjective'],
  ['honest', '정직한', 'feelings', 2, 'adjective'],
  ['polite', '예의 바른', 'feelings', 2, 'adjective'],
  ['patient', '참을성 있는', 'feelings', 2, 'adjective'],
  ['curious', '궁금한', 'feelings', 2, 'adjective'],
  ['gentle', '부드러운', 'feelings', 1, 'adjective'],
  ['lazy', '게으른', 'feelings', 1, 'adjective'],
  ['mean', '못된', 'feelings', 1, 'adjective'],
  ['selfish', '이기적인', 'feelings', 2, 'adjective'],
  ['rude', '무례한', 'feelings', 2, 'adjective'],
  ['cheerful', '쾌활한', 'feelings', 2, 'adjective'],
  ['friendly', '다정한', 'feelings', 1, 'adjective'],
  ['funny', '재미있는', 'feelings', 1, 'adjective'],
  ['serious', '진지한', 'feelings', 2, 'adjective'],
  ['silly', '어리석은', 'feelings', 1, 'adjective'],
  ['smart', '똑똑한', 'feelings', 1, 'adjective'],
  ['strong', '강한', 'feelings', 1, 'adjective'],
  ['weak', '약한', 'feelings', 1, 'adjective'],
  ['busy', '바쁜', 'feelings', 1, 'adjective'],
  ['free', '자유로운', 'feelings', 1, 'adjective'],
  ['safe', '안전한', 'feelings', 1, 'adjective'],
  ['afraid', '두려운', 'feelings', 1, 'adjective'],
  ['glad', '기쁜', 'feelings', 1, 'adjective'],
  ['sorry', '미안한', 'feelings', 1, 'adjective'],
  ['thankful', '고마운', 'feelings', 2, 'adjective'],
  ['hopeful', '희망적인', 'feelings', 2, 'adjective'],
  ['peaceful', '평화로운', 'feelings', 2, 'adjective'],
  ['angry', '성난', 'feelings', 1, 'adjective'],
  ['grumpy', '심술궂은', 'feelings', 2, 'adjective'],
  ['cranky', '짜증나는', 'feelings', 2, 'adjective'],
  ['moody', '기분이 변하는', 'feelings', 2, 'adjective'],
  ['gloomy', '우울한', 'feelings', 2, 'adjective'],

  // ── actions ──
  ['run', '달리다', 'actions', 1, 'verb'],
  ['walk', '걷다', 'actions', 1, 'verb'],
  ['jump', '뛰다', 'actions', 1, 'verb'],
  ['swim', '수영하다', 'actions', 1, 'verb'],
  ['fly', '날다', 'actions', 1, 'verb'],
  ['sing', '노래하다', 'actions', 1, 'verb'],
  ['dance', '춤추다', 'actions', 1, 'verb'],
  ['play', '놀다', 'actions', 1, 'verb'],
  ['eat', '먹다', 'actions', 1, 'verb'],
  ['drink', '마시다', 'actions', 1, 'verb'],
  ['sleep', '자다', 'actions', 1, 'verb'],
  ['wake', '일어나다', 'actions', 1, 'verb'],
  ['sit', '앉다', 'actions', 1, 'verb'],
  ['stand', '서다', 'actions', 1, 'verb'],
  ['stop', '멈추다', 'actions', 1, 'verb'],
  ['go', '가다', 'actions', 1, 'verb'],
  ['come', '오다', 'actions', 1, 'verb'],
  ['give', '주다', 'actions', 1, 'verb'],
  ['take', '가지다', 'actions', 1, 'verb'],
  ['open', '열다', 'actions', 1, 'verb'],
  ['close', '닫다', 'actions', 1, 'verb'],
  ['push', '밀다', 'actions', 1, 'verb'],
  ['pull', '당기다', 'actions', 1, 'verb'],
  ['throw', '던지다', 'actions', 1, 'verb'],
  ['catch', '잡다', 'actions', 1, 'verb'],
  ['kick', '차다', 'actions', 1, 'verb'],
  ['hit', '치다', 'actions', 1, 'verb'],
  ['cut', '자르다', 'actions', 1, 'verb'],
  ['wash', '씻다', 'actions', 1, 'verb'],
  ['clean', '청소하다', 'actions', 1, 'verb'],
  ['cook', '요리하다', 'actions', 1, 'verb'],
  ['build', '짓다', 'actions', 1, 'verb'],
  ['fix', '고치다', 'actions', 1, 'verb'],
  ['help', '돕다', 'actions', 1, 'verb'],
  ['try', '시도하다', 'actions', 1, 'verb'],
  ['find', '찾다', 'actions', 1, 'verb'],
  ['hide', '숨다', 'actions', 1, 'verb'],
  ['show', '보여주다', 'actions', 1, 'verb'],
  ['tell', '말하다', 'actions', 1, 'verb'],
  ['ask', '묻다', 'actions', 1, 'verb'],
  ['think', '생각하다', 'actions', 1, 'verb'],
  ['know', '알다', 'actions', 1, 'verb'],
  ['like', '좋아하다', 'actions', 1, 'verb'],
  ['love', '사랑하다', 'actions', 1, 'verb'],
  ['hate', '싫어하다', 'actions', 1, 'verb'],
  ['want', '원하다', 'actions', 1, 'verb'],
  ['need', '필요하다', 'actions', 1, 'verb'],
  ['have', '가지다', 'actions', 1, 'verb'],
  ['make', '만들다', 'actions', 1, 'verb'],
  ['do', '하다', 'actions', 1, 'verb'],
  ['say', '말하다', 'actions', 1, 'verb'],
  ['see', '보다', 'actions', 1, 'verb'],
  ['hear', '듣다', 'actions', 1, 'verb'],
  ['feel', '느끼다', 'actions', 1, 'verb'],
  ['touch', '만지다', 'actions', 1, 'verb'],
  ['smell', '냄새 맡다', 'actions', 1, 'verb'],
  ['taste', '맛보다', 'actions', 1, 'verb'],
  ['cry', '울다', 'actions', 1, 'verb'],
  ['laugh', '웃다', 'actions', 1, 'verb'],
  ['smile', '미소 짓다', 'actions', 1, 'verb'],
  ['shout', '소리치다', 'actions', 1, 'verb'],
  ['whisper', '속삭이다', 'actions', 2, 'verb'],
  ['clap', '박수치다', 'actions', 1, 'verb'],
  ['wave', '손을 흔들다', 'actions', 1, 'verb'],
  ['nod', '고개를 끄덕이다', 'actions', 1, 'verb'],
  ['shake', '흔들다', 'actions', 1, 'verb'],
  ['hug', '안다', 'actions', 1, 'verb'],
  ['kiss', '키스하다', 'actions', 1, 'verb'],
  ['bow', '인사하다', 'actions', 1, 'verb'],
  ['point', '가리키다', 'actions', 1, 'verb'],
  ['hold', '잡다', 'actions', 1, 'verb'],
  ['carry', '나르다', 'actions', 1, 'verb'],
  ['drop', '떨어뜨리다', 'actions', 1, 'verb'],
  ['pick', '고르다', 'actions', 1, 'verb'],
  ['lift', '들어올리다', 'actions', 1, 'verb'],
  ['put', '놓다', 'actions', 1, 'verb'],
  ['move', '움직이다', 'actions', 1, 'verb'],
  ['turn', '돌다', 'actions', 1, 'verb'],
  ['spin', '회전하다', 'actions', 1, 'verb'],
  ['roll', '구르다', 'actions', 1, 'verb'],
  ['slide', '미끄러지다', 'actions', 1, 'verb'],
  ['climb', '오르다', 'actions', 1, 'verb'],
  ['crawl', '기어가다', 'actions', 1, 'verb'],
  ['hop', '깡충 뛰다', 'actions', 1, 'verb'],
  ['skip', '깡충깡충 뛰다', 'actions', 1, 'verb'],
  ['stretch', '스트레칭하다', 'actions', 1, 'verb'],
  ['bend', '구부리다', 'actions', 1, 'verb'],
  ['twist', '비틀다', 'actions', 1, 'verb'],
  ['squeeze', '쥐어짜다', 'actions', 2, 'verb'],
  ['press', '누르다', 'actions', 1, 'verb'],
  ['dig', '파다', 'actions', 1, 'verb'],
  ['pour', '붓다', 'actions', 1, 'verb'],
  ['fill', '채우다', 'actions', 1, 'verb'],
  ['empty', '비우다', 'actions', 1, 'verb'],
  ['pack', '싸다', 'actions', 1, 'verb'],
  ['wrap', '포장하다', 'actions', 1, 'verb'],
  ['tie', '묶다', 'actions', 1, 'verb'],
  ['untie', '풀다', 'actions', 1, 'verb'],
  ['lock', '잠그다', 'actions', 1, 'verb'],
  ['unlock', '열다', 'actions', 1, 'verb'],
  ['knock', '노크하다', 'actions', 1, 'verb'],
  ['ring', '울리다', 'actions', 1, 'verb'],
  ['blow', '불다', 'actions', 1, 'verb'],
  ['suck', '빨다', 'actions', 1, 'verb'],
  ['breathe', '숨쉬다', 'actions', 1, 'verb'],
  ['cough', '기침하다', 'actions', 1, 'verb'],
  ['sneeze', '재채기하다', 'actions', 1, 'verb'],
  ['yawn', '하품하다', 'actions', 1, 'verb'],
  ['blink', '눈을 깜빡이다', 'actions', 1, 'verb'],
  ['stare', '쳐다보다', 'actions', 1, 'verb'],
  ['peek', '엿보다', 'actions', 1, 'verb'],
  ['wink', '윙크하다', 'actions', 1, 'verb'],
  ['nap', '낮잠 자다', 'actions', 1, 'verb'],
  ['dream', '꿈꾸다', 'actions', 1, 'verb'],
  ['snore', '코골다', 'actions', 2, 'verb'],
  ['wake up', '일어나다', 'actions', 1, 'verb'],
  ['get up', '일어서다', 'actions', 1, 'verb'],
  ['lie down', '눕다', 'actions', 1, 'verb'],
  ['sit down', '앉다', 'actions', 1, 'verb'],
  ['stand up', '일어서다', 'actions', 1, 'verb'],
  ['hurry', '서두르다', 'actions', 1, 'verb'],
  ['wait', '기다리다', 'actions', 1, 'verb'],
  ['rest', '쉬다', 'actions', 1, 'verb'],
  ['relax', '편히 쉬다', 'actions', 1, 'verb'],

  // ── places ──
  ['house', '집', 'places', 1, 'noun'],
  ['home', '가정', 'places', 1, 'noun'],
  ['room', '방', 'places', 1, 'noun'],
  ['kitchen', '부엌', 'places', 1, 'noun'],
  ['bathroom', '화장실', 'places', 1, 'noun'],
  ['bedroom', '침실', 'places', 1, 'noun'],
  ['living room', '거실', 'places', 1, 'noun'],
  ['garage', '차고', 'places', 1, 'noun'],
  ['yard', '마당', 'places', 1, 'noun'],
  ['park', '공원', 'places', 1, 'noun'],
  ['store', '가게', 'places', 1, 'noun'],
  ['shop', '상점', 'places', 1, 'noun'],
  ['market', '시장', 'places', 1, 'noun'],
  ['mall', '쇼핑몰', 'places', 1, 'noun'],
  ['bank', '은행', 'places', 1, 'noun'],
  ['hospital', '병원', 'places', 1, 'noun'],
  ['church', '교회', 'places', 1, 'noun'],
  ['temple', '사원', 'places', 1, 'noun'],
  ['museum', '박물관', 'places', 1, 'noun'],
  ['zoo', '동물원', 'places', 1, 'noun'],
  ['farm', '농장', 'places', 1, 'noun'],
  ['factory', '공장', 'places', 1, 'noun'],
  ['office', '사무실', 'places', 1, 'noun'],
  ['station', '역', 'places', 1, 'noun'],
  ['airport', '공항', 'places', 1, 'noun'],
  ['port', '항구', 'places', 1, 'noun'],
  ['hotel', '호텔', 'places', 1, 'noun'],
  ['restaurant', '음식점', 'places', 1, 'noun'],
  ['cafe', '카페', 'places', 1, 'noun'],
  ['bakery', '빵집', 'places', 1, 'noun'],
  ['pharmacy', '약국', 'places', 2, 'noun'],
  ['gym', '체육관', 'places', 1, 'noun'],
  ['pool', '수영장', 'places', 1, 'noun'],
  ['stadium', '경기장', 'places', 2, 'noun'],
  ['theater', '극장', 'places', 1, 'noun'],
  ['cinema', '영화관', 'places', 1, 'noun'],
  ['castle', '성', 'places', 1, 'noun'],
  ['palace', '궁전', 'places', 1, 'noun'],
  ['tower', '탑', 'places', 1, 'noun'],
  ['bridge', '다리', 'places', 1, 'noun'],
  ['tunnel', '터널', 'places', 1, 'noun'],
  ['road', '도로', 'places', 1, 'noun'],
  ['street', '거리', 'places', 1, 'noun'],
  ['path', '길', 'places', 1, 'noun'],
  ['sidewalk', '인도', 'places', 2, 'noun'],
  ['corner', '모퉁이', 'places', 1, 'noun'],
  ['fence', '울타리', 'places', 1, 'noun'],
  ['gate', '문', 'places', 1, 'noun'],
  ['wall', '벽', 'places', 1, 'noun'],
  ['roof', '지붕', 'places', 1, 'noun'],
  ['floor', '바닥', 'places', 1, 'noun'],
  ['ceiling', '천장', 'places', 1, 'noun'],
  ['stairs', '계단', 'places', 1, 'noun'],
  ['elevator', '엘리베이터', 'places', 2, 'noun'],
  ['window', '창문', 'places', 1, 'noun'],
  ['door', '문', 'places', 1, 'noun'],
  ['attic', '다락방', 'places', 2, 'noun'],
  ['basement', '지하실', 'places', 2, 'noun'],
  ['balcony', '발코니', 'places', 2, 'noun'],
  ['porch', '현관', 'places', 2, 'noun'],
  ['driveway', '진입로', 'places', 2, 'noun'],

  // ── greetings / daily expressions ──
  ['hello', '안녕하세요', 'greetings', 1, 'interjection'],
  ['hi', '안녕', 'greetings', 1, 'interjection'],
  ['goodbye', '안녕히 가세요', 'greetings', 1, 'interjection'],
  ['bye', '잘 가', 'greetings', 1, 'interjection'],
  ['please', '제발', 'greetings', 1, 'interjection'],
  ['thanks', '고마워', 'greetings', 1, 'interjection'],
  ['sorry', '미안해', 'greetings', 1, 'interjection'],
  ['excuse me', '실례합니다', 'greetings', 1, 'interjection'],
  ['welcome', '환영합니다', 'greetings', 1, 'interjection'],
  ['yes', '네', 'greetings', 1, 'interjection'],
  ['no', '아니요', 'greetings', 1, 'interjection'],
  ['okay', '좋아요', 'greetings', 1, 'interjection'],
  ['wow', '와', 'greetings', 1, 'interjection'],
  ['oops', '이런', 'greetings', 1, 'interjection'],
  ['hooray', '만세', 'greetings', 1, 'interjection'],
  ['ouch', '아야', 'greetings', 1, 'interjection'],
  ['shh', '쉿', 'greetings', 1, 'interjection'],
  ['hey', '야', 'greetings', 1, 'interjection'],
  ['cheers', '건배', 'greetings', 2, 'interjection'],
  ['bravo', '브라보', 'greetings', 2, 'interjection'],

  // ── toys / play ──
  ['toy', '장난감', 'toys', 1, 'noun'],
  ['ball', '공', 'toys', 1, 'noun'],
  ['doll', '인형', 'toys', 1, 'noun'],
  ['block', '블록', 'toys', 1, 'noun'],
  ['puzzle', '퍼즐', 'toys', 1, 'noun'],
  ['kite', '연', 'toys', 1, 'noun'],
  ['balloon', '풍선', 'toys', 1, 'noun'],
  ['swing', '그네', 'toys', 1, 'noun'],
  ['slide', '미끄럼틀', 'toys', 1, 'noun'],
  ['seesaw', '시소', 'toys', 1, 'noun'],
  ['sandbox', '모래상자', 'toys', 2, 'noun'],
  ['teddy bear', '곰 인형', 'toys', 1, 'noun'],
  ['robot', '로봇', 'toys', 1, 'noun'],
  ['train set', '기차 세트', 'toys', 1, 'noun'],
  ['racing car', '경주용 자동차', 'toys', 1, 'noun'],
  ['top', '팽이', 'toys', 1, 'noun'],
  ['yo-yo', '요요', 'toys', 1, 'noun'],
  ['marble', '구슬', 'toys', 1, 'noun'],
  ['jump rope', '줄넘기', 'toys', 1, 'noun'],
  ['hula hoop', '훌라후프', 'toys', 2, 'noun'],
  ['drum', '북', 'toys', 1, 'noun'],
  ['whistle', '호루라기', 'toys', 1, 'noun'],
  ['sticker', '스티커', 'toys', 1, 'noun'],
  ['card', '카드', 'toys', 1, 'noun'],
  ['dice', '주사위', 'toys', 1, 'noun'],
  ['board game', '보드 게임', 'toys', 1, 'noun'],
  ['video game', '비디오 게임', 'toys', 1, 'noun'],
  ['hide and seek', '숨바꼭질', 'toys', 1, 'noun'],
  ['tag', '술래잡기', 'toys', 1, 'noun'],
  ['hopscotch', '사방치기', 'toys', 2, 'noun'],

  // ── house items ──
  ['table', '탁자', 'house', 1, 'noun'],
  ['sofa', '소파', 'house', 1, 'noun'],
  ['bed', '침대', 'house', 1, 'noun'],
  ['pillow', '베개', 'house', 1, 'noun'],
  ['blanket', '담요', 'house', 1, 'noun'],
  ['sheet', '시트', 'house', 1, 'noun'],
  ['mattress', '매트리스', 'house', 2, 'noun'],
  ['lamp', '램프', 'house', 1, 'noun'],
  ['light', '조명', 'house', 1, 'noun'],
  ['mirror', '거울', 'house', 1, 'noun'],
  ['carpet', '카펫', 'house', 1, 'noun'],
  ['curtain', '커튼', 'house', 1, 'noun'],
  ['shelf', '선반', 'house', 1, 'noun'],
  ['drawer', '서랍', 'house', 1, 'noun'],
  ['closet', '옷장', 'house', 1, 'noun'],
  ['cabinet', '캐비닛', 'house', 2, 'noun'],
  ['oven', '오븐', 'house', 1, 'noun'],
  ['stove', '가스레인지', 'house', 1, 'noun'],
  ['fridge', '냉장고', 'house', 1, 'noun'],
  ['sink', '싱크대', 'house', 1, 'noun'],
  ['toilet', '변기', 'house', 1, 'noun'],
  ['bathtub', '욕조', 'house', 1, 'noun'],
  ['shower', '샤워기', 'house', 1, 'noun'],
  ['towel', '수건', 'house', 1, 'noun'],
  ['soap', '비누', 'house', 1, 'noun'],
  ['shampoo', '샴푸', 'house', 1, 'noun'],
  ['toothbrush', '칫솔', 'house', 1, 'noun'],
  ['toothpaste', '치약', 'house', 2, 'noun'],
  ['comb', '빗', 'house', 1, 'noun'],
  ['brush', '브러시', 'house', 1, 'noun'],
  ['broom', '빗자루', 'house', 1, 'noun'],
  ['mop', '대걸레', 'house', 1, 'noun'],
  ['bucket', '양동이', 'house', 1, 'noun'],
  ['trash can', '쓰레기통', 'house', 1, 'noun'],
  ['vacuum', '진공청소기', 'house', 2, 'noun'],
  ['iron', '다리미', 'house', 1, 'noun'],
  ['washing machine', '세탁기', 'house', 2, 'noun'],
  ['dryer', '건조기', 'house', 2, 'noun'],
  ['fan', '선풍기', 'house', 1, 'noun'],
  ['heater', '히터', 'house', 1, 'noun'],
  ['air conditioner', '에어컨', 'house', 2, 'noun'],
  ['telephone', '전화기', 'house', 2, 'noun'],
  ['television', '텔레비전', 'house', 2, 'noun'],
  ['remote', '리모컨', 'house', 1, 'noun'],
  ['alarm clock', '알람 시계', 'house', 2, 'noun'],
  ['key', '열쇠', 'house', 1, 'noun'],
  ['lock', '자물쇠', 'house', 1, 'noun'],
  ['mailbox', '우편함', 'house', 1, 'noun'],
  ['chimney', '굴뚝', 'house', 2, 'noun'],
  ['fireplace', '벽난로', 'house', 2, 'noun'],

  // ── time ──
  ['day', '낮', 'time', 1, 'noun'],
  ['night', '밤', 'time', 1, 'noun'],
  ['morning', '아침', 'time', 1, 'noun'],
  ['afternoon', '오후', 'time', 1, 'noun'],
  ['evening', '저녁', 'time', 1, 'noun'],
  ['midnight', '자정', 'time', 2, 'noun'],
  ['noon', '정오', 'time', 1, 'noun'],
  ['dawn', '새벽', 'time', 2, 'noun'],
  ['dusk', '황혼', 'time', 2, 'noun'],
  ['sunrise', '일출', 'time', 2, 'noun'],
  ['sunset', '일몰', 'time', 2, 'noun'],
  ['hour', '시간', 'time', 1, 'noun'],
  ['minute', '분', 'time', 1, 'noun'],
  ['second', '초', 'time', 1, 'noun'],
  ['week', '주', 'time', 1, 'noun'],
  ['month', '달', 'time', 1, 'noun'],
  ['year', '년', 'time', 1, 'noun'],
  ['today', '오늘', 'time', 1, 'noun'],
  ['tomorrow', '내일', 'time', 1, 'noun'],
  ['yesterday', '어제', 'time', 1, 'noun'],
  ['now', '지금', 'time', 1, 'adverb'],
  ['then', '그때', 'time', 1, 'adverb'],
  ['soon', '곧', 'time', 1, 'adverb'],
  ['later', '나중에', 'time', 1, 'adverb'],
  ['early', '일찍', 'time', 1, 'adverb'],
  ['late', '늦게', 'time', 1, 'adverb'],
  ['always', '항상', 'time', 1, 'adverb'],
  ['never', '절대', 'time', 1, 'adverb'],
  ['sometimes', '가끔', 'time', 1, 'adverb'],
  ['often', '자주', 'time', 1, 'adverb'],
  ['usually', '보통', 'time', 1, 'adverb'],
  ['already', '이미', 'time', 1, 'adverb'],
  ['still', '아직', 'time', 1, 'adverb'],
  ['ago', '전에', 'time', 1, 'adverb'],
  ['before', '이전에', 'time', 1, 'adverb'],
  ['after', '이후에', 'time', 1, 'adverb'],
  ['during', '동안', 'time', 1, 'preposition'],
  ['until', '까지', 'time', 1, 'preposition'],
  ['since', '이래로', 'time', 1, 'preposition'],
  ['while', '하는 동안', 'time', 1, 'conjunction'],

  // ── shapes ──
  ['circle', '원', 'shapes', 1, 'noun'],
  ['square', '정사각형', 'shapes', 1, 'noun'],
  ['triangle', '삼각형', 'shapes', 1, 'noun'],
  ['rectangle', '직사각형', 'shapes', 2, 'noun'],
  ['oval', '타원', 'shapes', 1, 'noun'],
  ['diamond', '다이아몬드', 'shapes', 1, 'noun'],
  ['star', '별 모양', 'shapes', 1, 'noun'],
  ['heart', '하트 모양', 'shapes', 1, 'noun'],
  ['cube', '정육면체', 'shapes', 2, 'noun'],
  ['sphere', '구', 'shapes', 2, 'noun'],
  ['cone', '원뿔', 'shapes', 2, 'noun'],
  ['cylinder', '원기둥', 'shapes', 2, 'noun'],
  ['pyramid', '피라미드', 'shapes', 2, 'noun'],
  ['arrow', '화살표', 'shapes', 1, 'noun'],
  ['cross', '십자 모양', 'shapes', 1, 'noun'],
  ['crescent', '초승달 모양', 'shapes', 2, 'noun'],
  ['hexagon', '육각형', 'shapes', 2, 'noun'],
  ['pentagon', '오각형', 'shapes', 2, 'noun'],
  ['octagon', '팔각형', 'shapes', 2, 'noun'],
  ['spiral', '나선', 'shapes', 2, 'noun'],
  ['round', '둥근', 'shapes', 1, 'adjective'],
  ['flat', '평평한', 'shapes', 1, 'adjective'],
  ['straight', '곧은', 'shapes', 1, 'adjective'],
  ['curved', '곡선의', 'shapes', 2, 'adjective'],
  ['pointed', '뾰족한', 'shapes', 2, 'adjective'],

  // ── sizes / descriptors ──
  ['big', '큰', 'description', 1, 'adjective'],
  ['small', '작은', 'description', 1, 'adjective'],
  ['tall', '키 큰', 'description', 1, 'adjective'],
  ['short', '짧은', 'description', 1, 'adjective'],
  ['long', '긴', 'description', 1, 'adjective'],
  ['wide', '넓은', 'description', 1, 'adjective'],
  ['narrow', '좁은', 'description', 1, 'adjective'],
  ['thick', '두꺼운', 'description', 1, 'adjective'],
  ['thin', '얇은', 'description', 1, 'adjective'],
  ['deep', '깊은', 'description', 1, 'adjective'],
  ['shallow', '얕은', 'description', 2, 'adjective'],
  ['heavy', '무거운', 'description', 1, 'adjective'],
  ['light', '가벼운', 'description', 1, 'adjective'],
  ['fast', '빠른', 'description', 1, 'adjective'],
  ['slow', '느린', 'description', 1, 'adjective'],
  ['loud', '시끄러운', 'description', 1, 'adjective'],
  ['quiet', '조용한', 'description', 1, 'adjective'],
  ['hard', '단단한', 'description', 1, 'adjective'],
  ['soft', '부드러운', 'description', 1, 'adjective'],
  ['rough', '거친', 'description', 1, 'adjective'],
  ['smooth', '매끄러운', 'description', 1, 'adjective'],
  ['sharp', '날카로운', 'description', 1, 'adjective'],
  ['dull', '무딘', 'description', 1, 'adjective'],
  ['bright', '밝은', 'description', 1, 'adjective'],
  ['dark', '어두운', 'description', 1, 'adjective'],
  ['clean', '깨끗한', 'description', 1, 'adjective'],
  ['dirty', '더러운', 'description', 1, 'adjective'],
  ['dry', '마른', 'description', 1, 'adjective'],
  ['wet', '젖은', 'description', 1, 'adjective'],
  ['full', '가득 찬', 'description', 1, 'adjective'],
  ['empty', '빈', 'description', 1, 'adjective'],
  ['new', '새로운', 'description', 1, 'adjective'],
  ['old', '오래된', 'description', 1, 'adjective'],
  ['young', '젊은', 'description', 1, 'adjective'],
  ['good', '좋은', 'description', 1, 'adjective'],
  ['bad', '나쁜', 'description', 1, 'adjective'],
  ['nice', '좋은', 'description', 1, 'adjective'],
  ['pretty', '예쁜', 'description', 1, 'adjective'],
  ['ugly', '못생긴', 'description', 1, 'adjective'],
  ['beautiful', '아름다운', 'description', 1, 'adjective'],
  ['handsome', '잘생긴', 'description', 2, 'adjective'],
  ['cute', '귀여운', 'description', 1, 'adjective'],
  ['rich', '부유한', 'description', 1, 'adjective'],
  ['poor', '가난한', 'description', 1, 'adjective'],
  ['right', '올바른', 'description', 1, 'adjective'],
  ['wrong', '틀린', 'description', 1, 'adjective'],
  ['true', '진짜의', 'description', 1, 'adjective'],
  ['false', '거짓의', 'description', 1, 'adjective'],
  ['real', '진짜의', 'description', 1, 'adjective'],
  ['fake', '가짜의', 'description', 1, 'adjective'],
  ['same', '같은', 'description', 1, 'adjective'],
  ['different', '다른', 'description', 1, 'adjective'],
  ['easy', '쉬운', 'description', 1, 'adjective'],
  ['difficult', '어려운', 'description', 1, 'adjective'],
  ['simple', '간단한', 'description', 1, 'adjective'],
  ['special', '특별한', 'description', 1, 'adjective'],
  ['important', '중요한', 'description', 2, 'adjective'],
  ['famous', '유명한', 'description', 2, 'adjective'],
  ['popular', '인기 있는', 'description', 2, 'adjective'],
  ['lucky', '운이 좋은', 'description', 1, 'adjective'],
  ['unlucky', '불운한', 'description', 2, 'adjective'],
  ['perfect', '완벽한', 'description', 2, 'adjective'],
  ['wonderful', '멋진', 'description', 2, 'adjective'],
  ['terrible', '끔찍한', 'description', 2, 'adjective'],
  ['amazing', '놀라운', 'description', 2, 'adjective'],
  ['awesome', '멋진', 'description', 1, 'adjective'],
  ['great', '훌륭한', 'description', 1, 'adjective'],
  ['cool', '멋진', 'description', 1, 'adjective'],
  ['sweet', '달콤한', 'description', 1, 'adjective'],
  ['sour', '신', 'description', 1, 'adjective'],
  ['bitter', '쓴', 'description', 1, 'adjective'],
  ['salty', '짠', 'description', 1, 'adjective'],
  ['spicy', '매운', 'description', 1, 'adjective'],
  ['tasty', '맛있는', 'description', 1, 'adjective'],
  ['yummy', '맛있는', 'description', 1, 'adjective'],
  ['delicious', '맛있는', 'description', 2, 'adjective'],
  ['fresh', '신선한', 'description', 1, 'adjective'],
  ['stale', '상한', 'description', 2, 'adjective'],
  ['raw', '날것의', 'description', 1, 'adjective'],
  ['cooked', '요리된', 'description', 1, 'adjective'],
  ['ripe', '익은', 'description', 1, 'adjective'],
  ['frozen', '얼린', 'description', 1, 'adjective'],

  // ── directions / positions ──
  ['up', '위', 'direction', 1, 'adverb'],
  ['down', '아래', 'direction', 1, 'adverb'],
  ['left', '왼쪽', 'direction', 1, 'noun'],
  ['right', '오른쪽', 'direction', 1, 'noun'],
  ['front', '앞', 'direction', 1, 'noun'],
  ['back', '뒤', 'direction', 1, 'noun'],
  ['top', '꼭대기', 'direction', 1, 'noun'],
  ['bottom', '바닥', 'direction', 1, 'noun'],
  ['middle', '가운데', 'direction', 1, 'noun'],
  ['side', '옆', 'direction', 1, 'noun'],
  ['inside', '안쪽', 'direction', 1, 'noun'],
  ['outside', '바깥', 'direction', 1, 'noun'],
  ['near', '가까운', 'direction', 1, 'adjective'],
  ['far', '먼', 'direction', 1, 'adjective'],
  ['here', '여기', 'direction', 1, 'adverb'],
  ['there', '거기', 'direction', 1, 'adverb'],
  ['north', '북쪽', 'direction', 1, 'noun'],
  ['south', '남쪽', 'direction', 1, 'noun'],
  ['east', '동쪽', 'direction', 1, 'noun'],
  ['west', '서쪽', 'direction', 1, 'noun'],
  ['above', '위에', 'direction', 1, 'preposition'],
  ['below', '아래에', 'direction', 1, 'preposition'],
  ['between', '사이에', 'direction', 1, 'preposition'],
  ['behind', '뒤에', 'direction', 1, 'preposition'],
  ['beside', '옆에', 'direction', 1, 'preposition'],
  ['across', '건너편에', 'direction', 1, 'preposition'],
  ['through', '통해서', 'direction', 1, 'preposition'],
  ['around', '주위에', 'direction', 1, 'preposition'],
  ['along', '따라서', 'direction', 1, 'preposition'],
  ['toward', '향해서', 'direction', 1, 'preposition'],

  // ── materials / textures ──
  ['wood', '나무', 'materials', 1, 'noun'],
  ['metal', '금속', 'materials', 1, 'noun'],
  ['glass', '유리', 'materials', 1, 'noun'],
  ['plastic', '플라스틱', 'materials', 1, 'noun'],
  ['rubber', '고무', 'materials', 1, 'noun'],
  ['paper', '종이', 'materials', 1, 'noun'],
  ['cloth', '천', 'materials', 1, 'noun'],
  ['cotton', '면', 'materials', 1, 'noun'],
  ['silk', '비단', 'materials', 1, 'noun'],
  ['wool', '양모', 'materials', 1, 'noun'],
  ['leather', '가죽', 'materials', 2, 'noun'],
  ['stone', '돌', 'materials', 1, 'noun'],
  ['brick', '벽돌', 'materials', 1, 'noun'],
  ['clay', '점토', 'materials', 1, 'noun'],
  ['concrete', '콘크리트', 'materials', 2, 'noun'],
  ['steel', '강철', 'materials', 2, 'noun'],
  ['iron', '철', 'materials', 1, 'noun'],
  ['copper', '구리', 'materials', 2, 'noun'],
  ['gold', '금', 'materials', 1, 'noun'],
  ['silver', '은', 'materials', 1, 'noun'],
  ['diamond', '다이아몬드', 'materials', 2, 'noun'],
  ['pearl', '진주', 'materials', 2, 'noun'],
  ['crystal', '수정', 'materials', 2, 'noun'],
  ['wax', '밀랍', 'materials', 1, 'noun'],
  ['chalk', '분필', 'materials', 1, 'noun'],

  // ── musical instruments ──
  ['piano', '피아노', 'music', 1, 'noun'],
  ['guitar', '기타', 'music', 1, 'noun'],
  ['violin', '바이올린', 'music', 2, 'noun'],
  ['drum', '드럼', 'music', 1, 'noun'],
  ['flute', '플루트', 'music', 2, 'noun'],
  ['trumpet', '트럼펫', 'music', 2, 'noun'],
  ['harmonica', '하모니카', 'music', 2, 'noun'],
  ['xylophone', '실로폰', 'music', 2, 'noun'],
  ['tambourine', '탬버린', 'music', 2, 'noun'],
  ['recorder', '리코더', 'music', 1, 'noun'],
  ['harp', '하프', 'music', 2, 'noun'],
  ['cello', '첼로', 'music', 2, 'noun'],
  ['banjo', '밴조', 'music', 2, 'noun'],
  ['ukulele', '우쿨렐레', 'music', 2, 'noun'],
  ['accordion', '아코디언', 'music', 2, 'noun'],
  ['tuba', '튜바', 'music', 2, 'noun'],
  ['clarinet', '클라리넷', 'music', 2, 'noun'],
  ['saxophone', '색소폰', 'music', 2, 'noun'],
  ['organ', '오르간', 'music', 2, 'noun'],
  ['cymbal', '심벌즈', 'music', 2, 'noun'],

  // ── transportation ──
  ['car', '자동차', 'transportation', 1, 'noun'],
  ['bus', '버스', 'transportation', 1, 'noun'],
  ['train', '기차', 'transportation', 1, 'noun'],
  ['plane', '비행기', 'transportation', 1, 'noun'],
  ['ship', '배', 'transportation', 1, 'noun'],
  ['boat', '보트', 'transportation', 1, 'noun'],
  ['bicycle', '자전거', 'transportation', 1, 'noun'],
  ['motorcycle', '오토바이', 'transportation', 2, 'noun'],
  ['truck', '트럭', 'transportation', 1, 'noun'],
  ['taxi', '택시', 'transportation', 1, 'noun'],
  ['subway', '지하철', 'transportation', 1, 'noun'],
  ['helicopter', '헬리콥터', 'transportation', 2, 'noun'],
  ['rocket', '로켓', 'transportation', 1, 'noun'],
  ['ambulance', '구급차', 'transportation', 2, 'noun'],
  ['fire truck', '소방차', 'transportation', 1, 'noun'],
  ['police car', '경찰차', 'transportation', 1, 'noun'],
  ['scooter', '스쿠터', 'transportation', 1, 'noun'],
  ['skateboard', '스케이트보드', 'transportation', 2, 'noun'],
  ['wagon', '마차', 'transportation', 1, 'noun'],
  ['sled', '썰매', 'transportation', 1, 'noun'],
  ['canoe', '카누', 'transportation', 2, 'noun'],
  ['kayak', '카약', 'transportation', 2, 'noun'],
  ['raft', '뗏목', 'transportation', 1, 'noun'],
  ['ferry', '여객선', 'transportation', 2, 'noun'],
  ['yacht', '요트', 'transportation', 2, 'noun'],
  ['tractor', '트랙터', 'transportation', 2, 'noun'],
  ['crane', '크레인', 'transportation', 2, 'noun'],
  ['van', '밴', 'transportation', 1, 'noun'],
  ['jeep', '지프', 'transportation', 1, 'noun'],
  ['wheel', '바퀴', 'transportation', 1, 'noun'],
  ['engine', '엔진', 'transportation', 2, 'noun'],
  ['tire', '타이어', 'transportation', 1, 'noun'],
  ['seat', '좌석', 'transportation', 1, 'noun'],
  ['ticket', '표', 'transportation', 1, 'noun'],
  ['stop', '정류장', 'transportation', 1, 'noun'],
  ['lane', '차선', 'transportation', 2, 'noun'],
  ['highway', '고속도로', 'transportation', 2, 'noun'],
  ['parking', '주차', 'transportation', 2, 'noun'],
  ['speed', '속도', 'transportation', 1, 'noun'],
  ['gas', '기름', 'transportation', 1, 'noun'],

  // ── more animals (insects, sea life, farm) ──
  ['parrot', '앵무새', 'animals', 1, 'noun'],
  ['flamingo', '플라밍고', 'animals', 2, 'noun'],
  ['ostrich', '타조', 'animals', 2, 'noun'],
  ['peacock', '공작새', 'animals', 2, 'noun'],
  ['pheasant', '꿩', 'animals', 2, 'noun'],
  ['pigeon', '비둘기', 'animals', 1, 'noun'],
  ['canary', '카나리아', 'animals', 2, 'noun'],
  ['parakeet', '잉꼬', 'animals', 2, 'noun'],
  ['hamster', '햄스터', 'animals', 1, 'noun'],
  ['gerbil', '저빌', 'animals', 2, 'noun'],
  ['guinea pig', '기니피그', 'animals', 2, 'noun'],
  ['goldfish', '금붕어', 'animals', 1, 'noun'],
  ['catfish', '메기', 'animals', 2, 'noun'],
  ['angelfish', '엔젤피시', 'animals', 2, 'noun'],
  ['clownfish', '흰동가리', 'animals', 2, 'noun'],
  ['pufferfish', '복어', 'animals', 2, 'noun'],
  ['barracuda', '바라쿠다', 'animals', 2, 'noun'],
  ['sardine', '정어리', 'animals', 2, 'noun'],
  ['herring', '청어', 'animals', 2, 'noun'],
  ['mackerel', '고등어', 'animals', 2, 'noun'],
  ['cod', '대구', 'animals', 1, 'noun'],
  ['anchovy', '멸치', 'animals', 2, 'noun'],
  ['prawn', '왕새우', 'animals', 1, 'noun'],
  ['mussel', '홍합', 'animals', 2, 'noun'],
  ['scallop', '가리비', 'animals', 2, 'noun'],
  ['sea cucumber', '해삼', 'animals', 2, 'noun'],
  ['anemone', '말미잘', 'animals', 2, 'noun'],
  ['barnacle', '따개비', 'animals', 2, 'noun'],
  ['hermit crab', '소라게', 'animals', 2, 'noun'],
  ['sea lion', '바다사자', 'animals', 2, 'noun'],
  ['sea otter', '해달', 'animals', 2, 'noun'],
  ['platypus', '오리너구리', 'animals', 2, 'noun'],
  ['armadillo', '아르마딜로', 'animals', 2, 'noun'],
  ['anteater', '개미핥기', 'animals', 2, 'noun'],
  ['sloth', '나무늘보', 'animals', 2, 'noun'],
  ['opossum', '주머니쥐', 'animals', 2, 'noun'],
  ['raccoon', '너구리', 'animals', 2, 'noun'],
  ['otter', '수달', 'animals', 1, 'noun'],
  ['marmot', '마멋', 'animals', 2, 'noun'],
  ['hedgehog', '고슴도치', 'animals', 2, 'noun'],
  ['porcupine', '호저', 'animals', 2, 'noun'],
  ['tapir', '맥', 'animals', 2, 'noun'],
  ['gazelle', '가젤', 'animals', 2, 'noun'],
  ['antelope', '영양', 'animals', 2, 'noun'],
  ['impala', '임팔라', 'animals', 2, 'noun'],
  ['wildebeest', '누', 'animals', 2, 'noun'],
  ['caribou', '순록', 'animals', 2, 'noun'],
  ['mule', '노새', 'animals', 1, 'noun'],
  ['stallion', '숫말', 'animals', 2, 'noun'],
  ['mare', '암말', 'animals', 1, 'noun'],
  ['ram', '숫양', 'animals', 1, 'noun'],
  ['ewe', '암양', 'animals', 1, 'noun'],
  ['bull', '황소', 'animals', 1, 'noun'],
  ['ox', '소', 'animals', 1, 'noun'],
  ['steer', '거세한 소', 'animals', 2, 'noun'],

  // ── more food ──
  ['oatmeal', '오트밀', 'food', 1, 'noun'],
  ['cereal', '시리얼', 'food', 1, 'noun'],
  ['granola', '그래놀라', 'food', 2, 'noun'],
  ['bagel', '베이글', 'food', 1, 'noun'],
  ['muffin', '머핀', 'food', 1, 'noun'],
  ['croissant', '크루아상', 'food', 2, 'noun'],
  ['pretzel', '프레첼', 'food', 2, 'noun'],
  ['cracker', '크래커', 'food', 1, 'noun'],
  ['biscuit', '비스킷', 'food', 1, 'noun'],
  ['waffle', '와플', 'food', 1, 'noun'],
  ['pancake', '팬케이크', 'food', 1, 'noun'],
  ['crepe', '크레이프', 'food', 2, 'noun'],
  ['omelet', '오믈렛', 'food', 2, 'noun'],
  ['scrambled eggs', '스크램블에그', 'food', 2, 'noun'],
  ['fried egg', '프라이드에그', 'food', 1, 'noun'],
  ['boiled egg', '삶은 달걀', 'food', 1, 'noun'],
  ['yogurt', '요거트', 'food', 1, 'noun'],
  ['pudding', '푸딩', 'food', 1, 'noun'],
  ['jelly', '젤리', 'food', 1, 'noun'],
  ['gelatin', '젤라틴', 'food', 2, 'noun'],
  ['brownie', '브라우니', 'food', 1, 'noun'],
  ['cupcake', '컵케이크', 'food', 1, 'noun'],
  ['donut', '도넛', 'food', 1, 'noun'],
  ['pastry', '페이스트리', 'food', 2, 'noun'],
  ['tart', '타르트', 'food', 1, 'noun'],
  ['scone', '스콘', 'food', 2, 'noun'],
  ['fudge', '퍼지', 'food', 2, 'noun'],
  ['caramel', '카라멜', 'food', 2, 'noun'],
  ['marshmallow', '마시멜로', 'food', 2, 'noun'],
  ['lollipop', '막대사탕', 'food', 1, 'noun'],
  ['gum', '껌', 'food', 1, 'noun'],
  ['popcorn', '팝콘', 'food', 1, 'noun'],
  ['chips', '감자칩', 'food', 1, 'noun'],
  ['pretzel', '프레첼', 'food', 2, 'noun'],
  ['smoothie', '스무디', 'food', 1, 'noun'],
  ['milkshake', '밀크셰이크', 'food', 2, 'noun'],
  ['lemonade', '레모네이드', 'food', 1, 'noun'],
  ['soda', '탄산음료', 'food', 1, 'noun'],
  ['cocoa', '코코아', 'food', 1, 'noun'],
  ['cider', '사이다', 'food', 2, 'noun'],
  ['broccoli', '브로콜리', 'food', 2, 'noun'],
  ['celery', '셀러리', 'food', 2, 'noun'],
  ['asparagus', '아스파라거스', 'food', 2, 'noun'],
  ['artichoke', '아티초크', 'food', 2, 'noun'],
  ['eggplant', '가지', 'food', 1, 'noun'],
  ['zucchini', '주키니', 'food', 2, 'noun'],
  ['squash', '호박', 'food', 1, 'noun'],
  ['pumpkin', '호박(큰)', 'food', 1, 'noun'],
  ['beet', '비트', 'food', 1, 'noun'],
  ['turnip', '순무', 'food', 1, 'noun'],
  ['radish', '무', 'food', 1, 'noun'],
  ['parsnip', '파스닙', 'food', 2, 'noun'],
  ['yam', '참마', 'food', 1, 'noun'],
  ['sweet potato', '고구마', 'food', 1, 'noun'],
  ['avocado', '아보카도', 'food', 2, 'noun'],
  ['olive', '올리브', 'food', 1, 'noun'],
  ['cinnamon', '시나몬', 'food', 2, 'noun'],
  ['ginger', '생강', 'food', 1, 'noun'],
  ['turmeric', '강황', 'food', 2, 'noun'],
  ['vanilla', '바닐라', 'food', 2, 'noun'],
  ['basil', '바질', 'food', 2, 'noun'],
  ['oregano', '오레가노', 'food', 2, 'noun'],
  ['thyme', '타임', 'food', 2, 'noun'],
  ['rosemary', '로즈마리', 'food', 2, 'noun'],
  ['parsley', '파슬리', 'food', 2, 'noun'],
  ['dill', '딜', 'food', 2, 'noun'],
  ['clove', '정향', 'food', 2, 'noun'],
  ['nutmeg', '넛메그', 'food', 2, 'noun'],
  ['paprika', '파프리카', 'food', 2, 'noun'],
  ['chili', '고추', 'food', 1, 'noun'],
  ['sesame', '참깨', 'food', 2, 'noun'],
  ['almond', '아몬드', 'food', 2, 'noun'],
  ['walnut', '호두', 'food', 2, 'noun'],
  ['cashew', '캐슈넛', 'food', 2, 'noun'],
  ['pecan', '피칸', 'food', 2, 'noun'],
  ['pistachio', '피스타치오', 'food', 2, 'noun'],
  ['hazelnut', '헤이즐넛', 'food', 2, 'noun'],
  ['peanut', '땅콩', 'food', 1, 'noun'],
  ['chestnut', '밤', 'food', 2, 'noun'],
  ['sunflower seed', '해바라기씨', 'food', 2, 'noun'],
  ['raisin', '건포도', 'food', 1, 'noun'],
  ['prune', '자두말린것', 'food', 2, 'noun'],
  ['fig', '무화과', 'food', 2, 'noun'],
  ['date', '대추야자', 'food', 2, 'noun'],
  ['cranberry', '크랜베리', 'food', 2, 'noun'],
  ['blackberry', '블랙베리', 'food', 2, 'noun'],
  ['blueberry', '블루베리', 'food', 1, 'noun'],
  ['raspberry', '라즈베리', 'food', 2, 'noun'],
  ['gooseberry', '구스베리', 'food', 2, 'noun'],
  ['kiwi', '키위', 'food', 1, 'noun'],
  ['papaya', '파파야', 'food', 2, 'noun'],
  ['guava', '구아바', 'food', 2, 'noun'],
  ['passion fruit', '패션프루트', 'food', 2, 'noun'],
  ['dragon fruit', '용과', 'food', 2, 'noun'],
  ['lychee', '리치', 'food', 2, 'noun'],
  ['persimmon', '감', 'food', 2, 'noun'],
  ['pomegranate', '석류', 'food', 2, 'noun'],
  ['tangerine', '귤', 'food', 1, 'noun'],
  ['grapefruit', '자몽', 'food', 2, 'noun'],
  ['cantaloupe', '멜론', 'food', 2, 'noun'],
  ['honeydew', '허니듀멜론', 'food', 2, 'noun'],

  // ── more daily objects ──
  ['pen', '펜', 'objects', 1, 'noun'],
  ['pencil', '연필', 'objects', 1, 'noun'],
  ['box', '상자', 'objects', 1, 'noun'],
  ['bag', '가방', 'objects', 1, 'noun'],
  ['bottle', '병', 'objects', 1, 'noun'],
  ['jar', '단지', 'objects', 1, 'noun'],
  ['can', '캔', 'objects', 1, 'noun'],
  ['basket', '바구니', 'objects', 1, 'noun'],
  ['tray', '쟁반', 'objects', 1, 'noun'],
  ['pot', '냄비', 'objects', 1, 'noun'],
  ['pan', '프라이팬', 'objects', 1, 'noun'],
  ['lid', '뚜껑', 'objects', 1, 'noun'],
  ['handle', '손잡이', 'objects', 1, 'noun'],
  ['hook', '고리', 'objects', 1, 'noun'],
  ['rope', '밧줄', 'objects', 1, 'noun'],
  ['chain', '사슬', 'objects', 1, 'noun'],
  ['wire', '철사', 'objects', 1, 'noun'],
  ['string', '끈', 'objects', 1, 'noun'],
  ['tape', '테이프', 'objects', 1, 'noun'],
  ['glue', '풀', 'objects', 1, 'noun'],
  ['pin', '핀', 'objects', 1, 'noun'],
  ['clip', '클립', 'objects', 1, 'noun'],
  ['ring', '반지', 'objects', 1, 'noun'],
  ['necklace', '목걸이', 'objects', 2, 'noun'],
  ['bracelet', '팔찌', 'objects', 2, 'noun'],
  ['earring', '귀걸이', 'objects', 2, 'noun'],
  ['watch', '시계', 'objects', 1, 'noun'],
  ['wallet', '지갑', 'objects', 1, 'noun'],
  ['purse', '핸드백', 'objects', 1, 'noun'],
  ['umbrella', '우산', 'objects', 1, 'noun'],
  ['cane', '지팡이', 'objects', 1, 'noun'],
  ['flag', '깃발', 'objects', 1, 'noun'],
  ['sign', '표지판', 'objects', 1, 'noun'],
  ['map', '지도', 'objects', 1, 'noun'],
  ['ticket', '표', 'objects', 1, 'noun'],
  ['stamp', '우표', 'objects', 1, 'noun'],
  ['letter', '편지', 'objects', 1, 'noun'],
  ['envelope', '봉투', 'objects', 2, 'noun'],
  ['package', '소포', 'objects', 1, 'noun'],
  ['gift', '선물', 'objects', 1, 'noun'],
  ['present', '선물', 'objects', 1, 'noun'],
  ['prize', '상', 'objects', 1, 'noun'],
  ['medal', '메달', 'objects', 1, 'noun'],
  ['trophy', '트로피', 'objects', 2, 'noun'],
  ['crown', '왕관', 'objects', 1, 'noun'],
  ['sword', '검', 'objects', 1, 'noun'],
  ['shield', '방패', 'objects', 1, 'noun'],
  ['bow', '활', 'objects', 1, 'noun'],
  ['arrow', '화살', 'objects', 1, 'noun'],
  ['spear', '창', 'objects', 1, 'noun'],
  ['torch', '횃불', 'objects', 1, 'noun'],
  ['candle', '양초', 'objects', 1, 'noun'],
  ['match', '성냥', 'objects', 1, 'noun'],
  ['lighter', '라이터', 'objects', 1, 'noun'],
  ['flashlight', '손전등', 'objects', 2, 'noun'],
  ['battery', '건전지', 'objects', 2, 'noun'],
  ['magnet', '자석', 'objects', 1, 'noun'],
  ['compass', '나침반', 'objects', 2, 'noun'],
  ['binoculars', '쌍안경', 'objects', 2, 'noun'],
  ['telescope', '망원경', 'objects', 2, 'noun'],
  ['thermometer', '온도계', 'objects', 2, 'noun'],
  ['scale', '저울', 'objects', 1, 'noun'],
  ['ruler', '자', 'objects', 1, 'noun'],
  ['calculator', '계산기', 'objects', 2, 'noun'],
  ['calendar', '달력', 'objects', 1, 'noun'],
  ['alarm', '알람', 'objects', 1, 'noun'],
  ['bell', '종', 'objects', 1, 'noun'],
  ['horn', '경적', 'objects', 1, 'noun'],
  ['whistle', '호루라기', 'objects', 1, 'noun'],
  ['siren', '사이렌', 'objects', 2, 'noun'],

  // ── more verbs (daily life) ──
  ['wake up', '일어나다', 'daily_verbs', 1, 'verb'],
  ['get dressed', '옷을 입다', 'daily_verbs', 1, 'verb'],
  ['brush teeth', '양치하다', 'daily_verbs', 1, 'verb'],
  ['comb hair', '빗질하다', 'daily_verbs', 1, 'verb'],
  ['take a bath', '목욕하다', 'daily_verbs', 1, 'verb'],
  ['take a shower', '샤워하다', 'daily_verbs', 1, 'verb'],
  ['have breakfast', '아침먹다', 'daily_verbs', 1, 'verb'],
  ['go to school', '등교하다', 'daily_verbs', 1, 'verb'],
  ['go home', '귀가하다', 'daily_verbs', 1, 'verb'],
  ['do homework', '숙제하다', 'daily_verbs', 1, 'verb'],
  ['watch TV', 'TV를 보다', 'daily_verbs', 1, 'verb'],
  ['listen to music', '음악듣다', 'daily_verbs', 1, 'verb'],
  ['play outside', '밖에서 놀다', 'daily_verbs', 1, 'verb'],
  ['go to bed', '잠자리에 들다', 'daily_verbs', 1, 'verb'],
  ['set the table', '상차리다', 'daily_verbs', 1, 'verb'],
  ['clean the room', '방청소하다', 'daily_verbs', 1, 'verb'],
  ['water plants', '물주다', 'daily_verbs', 1, 'verb'],
  ['feed the pet', '애완동물 밥주다', 'daily_verbs', 1, 'verb'],
  ['take out trash', '쓰레기 버리다', 'daily_verbs', 1, 'verb'],
  ['do the dishes', '설거지하다', 'daily_verbs', 1, 'verb'],
  ['fold clothes', '빨래 개다', 'daily_verbs', 1, 'verb'],
  ['hang clothes', '빨래 널다', 'daily_verbs', 1, 'verb'],
  ['sweep', '쓸다', 'daily_verbs', 1, 'verb'],
  ['mop', '걸레질하다', 'daily_verbs', 1, 'verb'],
  ['dust', '먼지를 닦다', 'daily_verbs', 1, 'verb'],
  ['vacuum', '진공청소기로 청소하다', 'daily_verbs', 2, 'verb'],
  ['recycle', '재활용하다', 'daily_verbs', 2, 'verb'],
  ['sort', '분류하다', 'daily_verbs', 1, 'verb'],
  ['organize', '정리하다', 'daily_verbs', 2, 'verb'],
  ['decorate', '꾸미다', 'daily_verbs', 2, 'verb'],

  // ── prepositions / connectors ──
  ['in', '안에', 'preposition', 1, 'preposition'],
  ['on', '위에', 'preposition', 1, 'preposition'],
  ['at', '에서', 'preposition', 1, 'preposition'],
  ['to', '으로', 'preposition', 1, 'preposition'],
  ['from', '에서부터', 'preposition', 1, 'preposition'],
  ['with', '함께', 'preposition', 1, 'preposition'],
  ['without', '없이', 'preposition', 1, 'preposition'],
  ['for', '위해', 'preposition', 1, 'preposition'],
  ['about', '에 대해', 'preposition', 1, 'preposition'],
  ['of', '의', 'preposition', 1, 'preposition'],
  ['into', '안으로', 'preposition', 1, 'preposition'],
  ['out of', '밖으로', 'preposition', 1, 'preposition'],
  ['over', '위로', 'preposition', 1, 'preposition'],
  ['under', '아래에', 'preposition', 1, 'preposition'],
  ['next to', '옆에', 'preposition', 1, 'preposition'],
  ['in front of', '앞에', 'preposition', 1, 'preposition'],
  ['behind', '뒤에', 'preposition', 1, 'preposition'],
  ['between', '사이에', 'preposition', 1, 'preposition'],
  ['among', '가운데', 'preposition', 2, 'preposition'],
  ['against', '에 반대하여', 'preposition', 2, 'preposition'],

  // ── pronouns ──
  ['I', '나', 'pronoun', 1, 'pronoun'],
  ['you', '너', 'pronoun', 1, 'pronoun'],
  ['he', '그', 'pronoun', 1, 'pronoun'],
  ['she', '그녀', 'pronoun', 1, 'pronoun'],
  ['it', '그것', 'pronoun', 1, 'pronoun'],
  ['we', '우리', 'pronoun', 1, 'pronoun'],
  ['they', '그들', 'pronoun', 1, 'pronoun'],
  ['me', '나를', 'pronoun', 1, 'pronoun'],
  ['him', '그를', 'pronoun', 1, 'pronoun'],
  ['her', '그녀를', 'pronoun', 1, 'pronoun'],
  ['us', '우리를', 'pronoun', 1, 'pronoun'],
  ['them', '그들을', 'pronoun', 1, 'pronoun'],
  ['my', '나의', 'pronoun', 1, 'pronoun'],
  ['your', '너의', 'pronoun', 1, 'pronoun'],
  ['his', '그의', 'pronoun', 1, 'pronoun'],
  ['our', '우리의', 'pronoun', 1, 'pronoun'],
  ['their', '그들의', 'pronoun', 1, 'pronoun'],
  ['this', '이것', 'pronoun', 1, 'pronoun'],
  ['that', '저것', 'pronoun', 1, 'pronoun'],
  ['these', '이것들', 'pronoun', 1, 'pronoun'],
  ['those', '저것들', 'pronoun', 1, 'pronoun'],
  ['who', '누구', 'pronoun', 1, 'pronoun'],
  ['what', '무엇', 'pronoun', 1, 'pronoun'],
  ['which', '어느 것', 'pronoun', 1, 'pronoun'],
  ['where', '어디', 'pronoun', 1, 'pronoun'],
  ['when', '언제', 'pronoun', 1, 'pronoun'],
  ['why', '왜', 'pronoun', 1, 'pronoun'],
  ['how', '어떻게', 'pronoun', 1, 'pronoun'],
  ['everyone', '모두', 'pronoun', 1, 'pronoun'],
  ['someone', '누군가', 'pronoun', 1, 'pronoun'],
  ['nobody', '아무도 아닌', 'pronoun', 1, 'pronoun'],
  ['anything', '아무것', 'pronoun', 1, 'pronoun'],
  ['everything', '모든 것', 'pronoun', 1, 'pronoun'],
  ['nothing', '아무것도 아닌', 'pronoun', 1, 'pronoun'],
  ['something', '무언가', 'pronoun', 1, 'pronoun'],
  ['myself', '나 자신', 'pronoun', 1, 'pronoun'],
  ['yourself', '너 자신', 'pronoun', 1, 'pronoun'],
  ['himself', '그 자신', 'pronoun', 1, 'pronoun'],
  ['herself', '그녀 자신', 'pronoun', 1, 'pronoun'],
  ['itself', '그것 자체', 'pronoun', 1, 'pronoun'],
  ['ourselves', '우리 자신', 'pronoun', 1, 'pronoun'],
  ['themselves', '그들 자신', 'pronoun', 1, 'pronoun'],

  // ── conjunctions ──
  ['and', '그리고', 'conjunction', 1, 'conjunction'],
  ['but', '하지만', 'conjunction', 1, 'conjunction'],
  ['or', '또는', 'conjunction', 1, 'conjunction'],
  ['so', '그래서', 'conjunction', 1, 'conjunction'],
  ['because', '왜냐하면', 'conjunction', 1, 'conjunction'],
  ['if', '만약', 'conjunction', 1, 'conjunction'],
  ['when', '할 때', 'conjunction', 1, 'conjunction'],
  ['while', '하는 동안', 'conjunction', 1, 'conjunction'],
  ['although', '비록', 'conjunction', 2, 'conjunction'],
  ['unless', '아니면', 'conjunction', 2, 'conjunction'],
  ['until', '까지', 'conjunction', 1, 'conjunction'],
  ['after', '후에', 'conjunction', 1, 'conjunction'],
  ['before', '전에', 'conjunction', 1, 'conjunction'],
  ['since', '이래로', 'conjunction', 1, 'conjunction'],
  ['both', '둘 다', 'conjunction', 1, 'conjunction'],
  ['either', '둘 중 하나', 'conjunction', 1, 'conjunction'],
  ['neither', '둘 다 아닌', 'conjunction', 2, 'conjunction'],
  ['nor', '도 아닌', 'conjunction', 2, 'conjunction'],
  ['not only', '뿐만 아니라', 'conjunction', 2, 'conjunction'],
  ['as well as', '뿐만 아니라', 'conjunction', 2, 'conjunction'],

  // ── adverbs ──
  ['very', '매우', 'adverbs', 1, 'adverb'],
  ['really', '정말', 'adverbs', 1, 'adverb'],
  ['too', '너무', 'adverbs', 1, 'adverb'],
  ['quite', '꽤', 'adverbs', 1, 'adverb'],
  ['just', '방금', 'adverbs', 1, 'adverb'],
  ['only', '오직', 'adverbs', 1, 'adverb'],
  ['also', '또한', 'adverbs', 1, 'adverb'],
  ['again', '다시', 'adverbs', 1, 'adverb'],
  ['together', '함께', 'adverbs', 1, 'adverb'],
  ['alone', '혼자', 'adverbs', 1, 'adverb'],
  ['quickly', '빨리', 'adverbs', 1, 'adverb'],
  ['slowly', '천천히', 'adverbs', 1, 'adverb'],
  ['carefully', '조심히', 'adverbs', 1, 'adverb'],
  ['easily', '쉽게', 'adverbs', 1, 'adverb'],
  ['happily', '행복하게', 'adverbs', 1, 'adverb'],
  ['sadly', '슬프게', 'adverbs', 1, 'adverb'],
  ['loudly', '크게', 'adverbs', 1, 'adverb'],
  ['quietly', '조용히', 'adverbs', 1, 'adverb'],
  ['well', '잘', 'adverbs', 1, 'adverb'],
  ['badly', '나쁘게', 'adverbs', 1, 'adverb'],
  ['hard', '열심히', 'adverbs', 1, 'adverb'],
  ['fast', '빠르게', 'adverbs', 1, 'adverb'],
  ['high', '높이', 'adverbs', 1, 'adverb'],
  ['low', '낮게', 'adverbs', 1, 'adverb'],
  ['far', '멀리', 'adverbs', 1, 'adverb'],
  ['close', '가까이', 'adverbs', 1, 'adverb'],
  ['almost', '거의', 'adverbs', 1, 'adverb'],
  ['exactly', '정확히', 'adverbs', 2, 'adverb'],
  ['probably', '아마', 'adverbs', 2, 'adverb'],
  ['maybe', '아마도', 'adverbs', 1, 'adverb'],
  ['perhaps', '아마도', 'adverbs', 2, 'adverb'],
  ['certainly', '확실히', 'adverbs', 2, 'adverb'],
  ['definitely', '확실히', 'adverbs', 2, 'adverb'],
  ['fortunately', '다행히', 'adverbs', 2, 'adverb'],
  ['unfortunately', '불행히', 'adverbs', 2, 'adverb'],
  ['suddenly', '갑자기', 'adverbs', 1, 'adverb'],
  ['gradually', '점차', 'adverbs', 2, 'adverb'],
  ['finally', '마침내', 'adverbs', 1, 'adverb'],
  ['recently', '최근에', 'adverbs', 2, 'adverb'],
  ['especially', '특히', 'adverbs', 2, 'adverb'],
  ['actually', '사실은', 'adverbs', 2, 'adverb'],

  // ── more animals (exotic, farm, pets) ──
  ['chinchilla', '친칠라', 'animals', 2, 'noun'],
  ['lemur', '여우원숭이', 'animals', 2, 'noun'],
  ['orangutan', '오랑우탄', 'animals', 2, 'noun'],
  ['chimpanzee', '침팬지', 'animals', 2, 'noun'],
  ['baboon', '개코원숭이', 'animals', 2, 'noun'],
  ['gorilla', '고릴라', 'animals', 2, 'noun'],
  ['meerkat', '미어캣', 'animals', 2, 'noun'],
  ['mongoose', '몽구스', 'animals', 2, 'noun'],
  ['aardvark', '땅돼지', 'animals', 2, 'noun'],
  ['pangolin', '천산갑', 'animals', 2, 'noun'],
  ['okapi', '오카피', 'animals', 2, 'noun'],
  ['capybara', '카피바라', 'animals', 2, 'noun'],
  ['wombat', '웜뱃', 'animals', 2, 'noun'],
  ['possum', '주머니쥐', 'animals', 2, 'noun'],
  ['echidna', '가시두더지', 'animals', 2, 'noun'],
  ['dingo', '딩고', 'animals', 2, 'noun'],
  ['kookaburra', '쿠카부라', 'animals', 2, 'noun'],
  ['emu', '에뮤', 'animals', 2, 'noun'],
  ['cassowary', '화식조', 'animals', 2, 'noun'],
  ['cockatoo', '앵무새(흰)', 'animals', 2, 'noun'],
  ['macaw', '금강앵무', 'animals', 2, 'noun'],
  ['hummingbird', '벌새', 'animals', 2, 'noun'],
  ['kingfisher', '물총새', 'animals', 2, 'noun'],
  ['roadrunner', '큰뻐꾸기', 'animals', 2, 'noun'],
  ['quail', '메추리', 'animals', 2, 'noun'],
  ['partridge', '자고새', 'animals', 2, 'noun'],
  ['turkey', '칠면조', 'animals', 1, 'noun'],
  ['grouse', '뇌조', 'animals', 2, 'noun'],
  ['cuckoo', '뻐꾸기', 'animals', 2, 'noun'],
  ['nightingale', '나이팅게일', 'animals', 2, 'noun'],
  ['lark', '종달새', 'animals', 2, 'noun'],
  ['warbler', '솔새', 'animals', 2, 'noun'],
  ['swift', '칼새', 'animals', 2, 'noun'],
  ['martin', '제비류', 'animals', 2, 'noun'],
  ['raven', '큰까마귀', 'animals', 2, 'noun'],
  ['starling', '찌르레기', 'animals', 2, 'noun'],
  ['thrush', '개똥지빠귀', 'animals', 2, 'noun'],
  ['blackbird', '검은지빠귀', 'animals', 2, 'noun'],
  ['cardinal', '홍관조', 'animals', 2, 'noun'],
  ['oriole', '꾀꼬리', 'animals', 2, 'noun'],
  ['mandrill', '만드릴', 'animals', 2, 'noun'],
  ['gibbon', '긴팔원숭이', 'animals', 2, 'noun'],
  ['tamarin', '타마린', 'animals', 2, 'noun'],
  ['marmoset', '마모셋', 'animals', 2, 'noun'],
  ['macaroni penguin', '마카로니펭귄', 'animals', 2, 'noun'],
  ['emperor penguin', '황제펭귄', 'animals', 2, 'noun'],
  ['rockhopper penguin', '바위뛰기펭귄', 'animals', 2, 'noun'],
  ['arctic fox', '북극여우', 'animals', 2, 'noun'],
  ['red fox', '붉은여우', 'animals', 2, 'noun'],
  ['grey wolf', '회색늑대', 'animals', 2, 'noun'],

  // ── more house / furniture ──
  ['chandelier', '샹들리에', 'house', 2, 'noun'],
  ['bookcase', '책장', 'house', 1, 'noun'],
  ['nightstand', '침대탁자', 'house', 2, 'noun'],
  ['dresser', '화장대', 'house', 2, 'noun'],
  ['wardrobe', '옷장', 'house', 2, 'noun'],
  ['cupboard', '찬장', 'house', 2, 'noun'],
  ['pantry', '식료품 저장실', 'house', 2, 'noun'],
  ['counter', '조리대', 'house', 1, 'noun'],
  ['blinds', '블라인드', 'house', 2, 'noun'],
  ['shutter', '덧문', 'house', 2, 'noun'],
  ['doormat', '현관 깔개', 'house', 2, 'noun'],
  ['coaster', '컵받침', 'house', 2, 'noun'],
  ['placemat', '식탁매트', 'house', 2, 'noun'],
  ['tablecloth', '식탁보', 'house', 2, 'noun'],
  ['vase', '꽃병', 'house', 1, 'noun'],
  ['frame', '액자', 'house', 1, 'noun'],
  ['rug', '깔개', 'house', 1, 'noun'],
  ['cushion', '쿠션', 'house', 1, 'noun'],
  ['throw pillow', '장식베개', 'house', 2, 'noun'],
  ['quilt', '퀼트', 'house', 2, 'noun'],
  ['comforter', '이불', 'house', 2, 'noun'],
  ['duvet', '오리털이불', 'house', 2, 'noun'],
  ['hamper', '세탁바구니', 'house', 2, 'noun'],
  ['hanger', '옷걸이', 'house', 1, 'noun'],
  ['basket', '바구니', 'house', 1, 'noun'],
  ['bin', '휴지통', 'house', 1, 'noun'],
  ['pot', '냄비', 'house', 1, 'noun'],
  ['pan', '프라이팬', 'house', 1, 'noun'],
  ['kettle', '주전자', 'house', 1, 'noun'],
  ['teapot', '찻주전자', 'house', 2, 'noun'],
  ['mug', '머그컵', 'house', 1, 'noun'],
  ['saucer', '받침접시', 'house', 2, 'noun'],
  ['pitcher', '물병', 'house', 2, 'noun'],
  ['thermos', '보온병', 'house', 2, 'noun'],
  ['colander', '소쿠리', 'house', 2, 'noun'],
  ['grater', '강판', 'house', 2, 'noun'],
  ['ladle', '국자', 'house', 2, 'noun'],
  ['spatula', '뒤집개', 'house', 2, 'noun'],
  ['whisk', '거품기', 'house', 2, 'noun'],
  ['rolling pin', '밀대', 'house', 2, 'noun'],
  ['cutting board', '도마', 'house', 1, 'noun'],
  ['blender', '믹서기', 'house', 2, 'noun'],
  ['toaster', '토스터', 'house', 1, 'noun'],
  ['microwave', '전자레인지', 'house', 2, 'noun'],
  ['dishwasher', '식기세척기', 'house', 2, 'noun'],
  ['freezer', '냉동고', 'house', 2, 'noun'],

  // ── more nature (plants, trees, terrain) ──
  ['birch', '자작나무', 'nature', 2, 'noun'],
  ['cedar', '삼나무', 'nature', 2, 'noun'],
  ['elm', '느릅나무', 'nature', 2, 'noun'],
  ['ash', '물푸레나무', 'nature', 2, 'noun'],
  ['beech', '너도밤나무', 'nature', 2, 'noun'],
  ['poplar', '포플러', 'nature', 2, 'noun'],
  ['spruce', '가문비나무', 'nature', 2, 'noun'],
  ['redwood', '레드우드', 'nature', 2, 'noun'],
  ['sequoia', '세쿼이아', 'nature', 2, 'noun'],
  ['baobab', '바오밥나무', 'nature', 2, 'noun'],
  ['magnolia', '목련', 'nature', 2, 'noun'],
  ['cherry blossom', '벚꽃', 'nature', 1, 'noun'],
  ['jasmine', '재스민', 'nature', 2, 'noun'],
  ['hibiscus', '히비스커스', 'nature', 2, 'noun'],
  ['peony', '모란', 'nature', 2, 'noun'],
  ['carnation', '카네이션', 'nature', 2, 'noun'],
  ['chrysanthemum', '국화', 'nature', 2, 'noun'],
  ['poppy', '양귀비', 'nature', 2, 'noun'],
  ['iris', '붓꽃', 'nature', 2, 'noun'],
  ['marigold', '금잔화', 'nature', 2, 'noun'],
  ['daffodil', '수선화', 'nature', 2, 'noun'],
  ['hyacinth', '히아신스', 'nature', 2, 'noun'],
  ['pansy', '팬지', 'nature', 2, 'noun'],
  ['lavender', '라벤더', 'nature', 2, 'noun'],
  ['heather', '히스', 'nature', 2, 'noun'],
  ['sage', '세이지', 'nature', 2, 'noun'],
  ['chamomile', '카모마일', 'nature', 2, 'noun'],
  ['aloe', '알로에', 'nature', 2, 'noun'],
  ['ivy', '담쟁이덩굴', 'nature', 1, 'noun'],
  ['moss', '이끼', 'nature', 1, 'noun'],
  ['lichen', '지의류', 'nature', 2, 'noun'],
  ['seaweed', '해초', 'nature', 2, 'noun'],
  ['kelp', '다시마', 'nature', 2, 'noun'],
  ['reed', '갈대', 'nature', 2, 'noun'],
  ['cattail', '부들', 'nature', 2, 'noun'],
  ['lily pad', '수련잎', 'nature', 2, 'noun'],
  ['lotus', '연꽃', 'nature', 2, 'noun'],
  ['acorn', '도토리', 'nature', 1, 'noun'],
  ['pinecone', '솔방울', 'nature', 1, 'noun'],
  ['berry', '열매', 'nature', 1, 'noun'],
  ['twig', '잔가지', 'nature', 1, 'noun'],
  ['log', '통나무', 'nature', 1, 'noun'],
  ['stump', '그루터기', 'nature', 2, 'noun'],
  ['thicket', '수풀', 'nature', 2, 'noun'],
  ['meadow', '목초지', 'nature', 2, 'noun'],
  ['field', '들판', 'nature', 1, 'noun'],
  ['grove', '작은 숲', 'nature', 2, 'noun'],
  ['orchard', '과수원', 'nature', 2, 'noun'],
  ['hedge', '산울타리', 'nature', 2, 'noun'],
  ['pasture', '목장', 'nature', 2, 'noun'],

  // ── more everyday actions ──
  ['agree', '동의하다', 'actions', 1, 'verb'],
  ['allow', '허락하다', 'actions', 2, 'verb'],
  ['begin', '시작하다', 'actions', 1, 'verb'],
  ['belong', '속하다', 'actions', 2, 'verb'],
  ['borrow', '빌리다', 'actions', 1, 'verb'],
  ['bring', '가져오다', 'actions', 1, 'verb'],
  ['buy', '사다', 'actions', 1, 'verb'],
  ['call', '부르다', 'actions', 1, 'verb'],
  ['change', '바꾸다', 'actions', 1, 'verb'],
  ['check', '확인하다', 'actions', 1, 'verb'],
  ['choose', '고르다', 'actions', 1, 'verb'],
  ['collect', '모으다', 'actions', 1, 'verb'],
  ['cost', '비용이 들다', 'actions', 1, 'verb'],
  ['cross', '건너다', 'actions', 1, 'verb'],
  ['decide', '결정하다', 'actions', 1, 'verb'],
  ['deliver', '배달하다', 'actions', 2, 'verb'],
  ['describe', '묘사하다', 'actions', 2, 'verb'],
  ['destroy', '파괴하다', 'actions', 2, 'verb'],
  ['enjoy', '즐기다', 'actions', 1, 'verb'],
  ['enter', '들어가다', 'actions', 1, 'verb'],
  ['escape', '탈출하다', 'actions', 2, 'verb'],
  ['explain', '설명하다', 'actions', 2, 'verb'],
  ['explore', '탐험하다', 'actions', 2, 'verb'],
  ['finish', '끝내다', 'actions', 1, 'verb'],
  ['follow', '따르다', 'actions', 1, 'verb'],
  ['forget', '잊다', 'actions', 1, 'verb'],
  ['forgive', '용서하다', 'actions', 2, 'verb'],
  ['grow', '자라다', 'actions', 1, 'verb'],
  ['guess', '추측하다', 'actions', 1, 'verb'],
  ['happen', '일어나다', 'actions', 1, 'verb'],
  ['hope', '바라다', 'actions', 1, 'verb'],
  ['imagine', '상상하다', 'actions', 2, 'verb'],
  ['include', '포함하다', 'actions', 2, 'verb'],
  ['join', '합류하다', 'actions', 1, 'verb'],
  ['keep', '유지하다', 'actions', 1, 'verb'],
  ['leave', '떠나다', 'actions', 1, 'verb'],
  ['lend', '빌려주다', 'actions', 1, 'verb'],
  ['let', '허락하다', 'actions', 1, 'verb'],
  ['live', '살다', 'actions', 1, 'verb'],
  ['lose', '잃다', 'actions', 1, 'verb'],
  ['mean', '의미하다', 'actions', 1, 'verb'],
  ['meet', '만나다', 'actions', 1, 'verb'],
  ['miss', '그리워하다', 'actions', 1, 'verb'],
  ['move', '이사하다', 'actions', 1, 'verb'],
  ['notice', '알아차리다', 'actions', 2, 'verb'],
  ['obey', '순종하다', 'actions', 2, 'verb'],
  ['offer', '제공하다', 'actions', 2, 'verb'],
  ['order', '주문하다', 'actions', 1, 'verb'],
  ['own', '소유하다', 'actions', 1, 'verb'],
  ['pass', '지나가다', 'actions', 1, 'verb'],
  ['pay', '지불하다', 'actions', 1, 'verb'],
  ['plan', '계획하다', 'actions', 1, 'verb'],
  ['prepare', '준비하다', 'actions', 2, 'verb'],
  ['promise', '약속하다', 'actions', 2, 'verb'],
  ['protect', '보호하다', 'actions', 2, 'verb'],
  ['reach', '도달하다', 'actions', 1, 'verb'],
  ['receive', '받다', 'actions', 2, 'verb'],
  ['remember', '기억하다', 'actions', 1, 'verb'],
  ['remind', '상기시키다', 'actions', 2, 'verb'],
  ['repeat', '반복하다', 'actions', 1, 'verb'],
  ['return', '돌아오다', 'actions', 1, 'verb'],
  ['save', '저장하다', 'actions', 1, 'verb'],
  ['sell', '팔다', 'actions', 1, 'verb'],
  ['send', '보내다', 'actions', 1, 'verb'],
  ['share', '나누다', 'actions', 1, 'verb'],
  ['spend', '쓰다', 'actions', 1, 'verb'],
  ['start', '시작하다', 'actions', 1, 'verb'],
  ['steal', '훔치다', 'actions', 2, 'verb'],
  ['suggest', '제안하다', 'actions', 2, 'verb'],
  ['surprise', '놀라게 하다', 'actions', 1, 'verb'],
  ['travel', '여행하다', 'actions', 1, 'verb'],
  ['understand', '이해하다', 'actions', 1, 'verb'],
  ['use', '사용하다', 'actions', 1, 'verb'],
  ['visit', '방문하다', 'actions', 1, 'verb'],
  ['win', '이기다', 'actions', 1, 'verb'],
  ['wonder', '궁금해하다', 'actions', 1, 'verb'],
  ['work', '일하다', 'actions', 1, 'verb'],
  ['worry', '걱정하다', 'actions', 1, 'verb'],

  // ── occupations (simple) ──
  ['doctor', '의사', 'jobs', 1, 'noun'],
  ['nurse', '간호사', 'jobs', 1, 'noun'],
  ['teacher', '선생님', 'jobs', 1, 'noun'],
  ['farmer', '농부', 'jobs', 1, 'noun'],
  ['driver', '운전사', 'jobs', 1, 'noun'],
  ['cook', '요리사', 'jobs', 1, 'noun'],
  ['singer', '가수', 'jobs', 1, 'noun'],
  ['dancer', '무용가', 'jobs', 1, 'noun'],
  ['painter', '화가', 'jobs', 1, 'noun'],
  ['writer', '작가', 'jobs', 1, 'noun'],
  ['baker', '빵굽는 사람', 'jobs', 1, 'noun'],
  ['pilot', '조종사', 'jobs', 1, 'noun'],
  ['actor', '배우', 'jobs', 1, 'noun'],
  ['dentist', '치과의사', 'jobs', 2, 'noun'],
  ['firefighter', '소방관', 'jobs', 2, 'noun'],
  ['police officer', '경찰', 'jobs', 2, 'noun'],
  ['vet', '수의사', 'jobs', 1, 'noun'],
  ['builder', '건설 노동자', 'jobs', 1, 'noun'],
  ['sailor', '선원', 'jobs', 1, 'noun'],
  ['soldier', '군인', 'jobs', 1, 'noun'],
  ['scientist', '과학자', 'jobs', 2, 'noun'],
  ['astronaut', '우주비행사', 'jobs', 2, 'noun'],
  ['artist', '예술가', 'jobs', 1, 'noun'],
  ['musician', '음악가', 'jobs', 2, 'noun'],
  ['athlete', '운동선수', 'jobs', 2, 'noun'],

  // ── fruits & vegetables (more) ──
  ['melon', '멜론', 'food', 1, 'noun'],
  ['plum', '자두', 'food', 1, 'noun'],
  ['apricot', '살구', 'food', 2, 'noun'],
  ['nectarine', '천도복숭아', 'food', 2, 'noun'],
  ['starfruit', '별모양 과일', 'food', 2, 'noun'],
  ['jackfruit', '잭프루트', 'food', 2, 'noun'],
  ['durian', '두리안', 'food', 2, 'noun'],
  ['rambutan', '람부탄', 'food', 2, 'noun'],
  ['mangosteen', '망고스틴', 'food', 2, 'noun'],
  ['kumquat', '금귤', 'food', 2, 'noun'],
  ['endive', '엔다이브', 'food', 2, 'noun'],
  ['fennel', '회향', 'food', 2, 'noun'],
  ['leek', '리크(대파)', 'food', 2, 'noun'],
  ['okra', '오크라', 'food', 2, 'noun'],
  ['kale', '케일', 'food', 2, 'noun'],
  ['arugula', '루콜라', 'food', 2, 'noun'],
  ['chard', '근대', 'food', 2, 'noun'],
  ['watercress', '물냉이', 'food', 2, 'noun'],
  ['sprout', '새싹', 'food', 1, 'noun'],
  ['bean sprout', '콩나물', 'food', 1, 'noun'],
  ['tofu', '두부', 'food', 1, 'noun'],
  ['soy sauce', '간장', 'food', 1, 'noun'],
  ['kimchi', '김치', 'food', 1, 'noun'],
  ['rice cake', '떡', 'food', 1, 'noun'],
  ['seaweed', '해초/김', 'food', 1, 'noun'],

  // ── school / classroom ──
  ['backpack', '가방', 'school', 1, 'noun'],
  ['pencil case', '필통', 'school', 1, 'noun'],
  ['marker', '마커', 'school', 1, 'noun'],
  ['highlighter', '형광펜', 'school', 2, 'noun'],
  ['stapler', '스테이플러', 'school', 2, 'noun'],
  ['folder', '폴더', 'school', 1, 'noun'],
  ['binder', '바인더', 'school', 2, 'noun'],
  ['globe', '지구본', 'school', 1, 'noun'],
  ['whiteboard', '화이트보드', 'school', 2, 'noun'],
  ['chalk', '분필', 'school', 1, 'noun'],
  ['lunch box', '도시락통', 'school', 1, 'noun'],
  ['water bottle', '물병', 'school', 1, 'noun'],
  ['locker', '사물함', 'school', 1, 'noun'],
  ['cafeteria', '구내식당', 'school', 2, 'noun'],
  ['principal', '교장선생님', 'school', 2, 'noun'],
  ['classmate', '반 친구', 'school', 1, 'noun'],
  ['field trip', '현장학습', 'school', 1, 'noun'],
  ['assembly', '조회', 'school', 2, 'noun'],
  ['diploma', '졸업장', 'school', 2, 'noun'],
  ['semester', '학기', 'school', 2, 'noun'],
  ['attendance', '출석', 'school', 2, 'noun'],
  ['permission', '허가', 'school', 2, 'noun'],
  ['detention', '방과후 벌', 'school', 2, 'noun'],
  ['honor roll', '우등생 명단', 'school', 2, 'noun'],
  ['scholarship', '장학금', 'school', 2, 'noun'],

  // ── sports (simple) ──
  ['soccer', '축구', 'sports', 1, 'noun'],
  ['baseball', '야구', 'sports', 1, 'noun'],
  ['basketball', '농구', 'sports', 1, 'noun'],
  ['tennis', '테니스', 'sports', 1, 'noun'],
  ['volleyball', '배구', 'sports', 1, 'noun'],
  ['badminton', '배드민턴', 'sports', 1, 'noun'],
  ['table tennis', '탁구', 'sports', 1, 'noun'],
  ['golf', '골프', 'sports', 1, 'noun'],
  ['swimming', '수영', 'sports', 1, 'noun'],
  ['running', '달리기', 'sports', 1, 'noun'],
  ['skating', '스케이팅', 'sports', 1, 'noun'],
  ['skiing', '스키', 'sports', 1, 'noun'],
  ['surfing', '서핑', 'sports', 1, 'noun'],
  ['bowling', '볼링', 'sports', 1, 'noun'],
  ['archery', '양궁', 'sports', 2, 'noun'],
  ['gymnastics', '체조', 'sports', 2, 'noun'],
  ['judo', '유도', 'sports', 1, 'noun'],
  ['taekwondo', '태권도', 'sports', 1, 'noun'],
  ['karate', '가라테', 'sports', 1, 'noun'],
  ['fencing', '펜싱', 'sports', 2, 'noun'],
  ['rowing', '조정', 'sports', 2, 'noun'],
  ['diving', '다이빙', 'sports', 1, 'noun'],
  ['boxing', '복싱', 'sports', 1, 'noun'],
  ['wrestling', '레슬링', 'sports', 2, 'noun'],
  ['hockey', '하키', 'sports', 1, 'noun'],

  // ── holidays & events ──
  ['birthday', '생일', 'events', 1, 'noun'],
  ['wedding', '결혼식', 'events', 2, 'noun'],
  ['funeral', '장례식', 'events', 2, 'noun'],
  ['anniversary', '기념일', 'events', 2, 'noun'],
  ['graduation', '졸업식', 'events', 2, 'noun'],
  ['ceremony', '의식', 'events', 2, 'noun'],
  ['parade', '퍼레이드', 'events', 1, 'noun'],
  ['carnival', '카니발', 'events', 2, 'noun'],
  ['festival', '축제', 'events', 1, 'noun'],
  ['concert', '콘서트', 'events', 1, 'noun'],
  ['picnic', '소풍', 'events', 1, 'noun'],
  ['barbecue', '바베큐', 'events', 2, 'noun'],
  ['sleepover', '잠자리 파티', 'events', 2, 'noun'],
  ['reunion', '동창회', 'events', 2, 'noun'],
  ['talent show', '장기자랑', 'events', 2, 'noun'],
  ['costume party', '코스튬 파티', 'events', 2, 'noun'],
  ['surprise party', '깜짝 파티', 'events', 2, 'noun'],
  ['New Year', '새해', 'events', 1, 'noun'],
  ['Valentine', '밸런타인', 'events', 2, 'noun'],
  ['Easter', '부활절', 'events', 2, 'noun'],
  ['Thanksgiving', '추수감사절', 'events', 2, 'noun'],
  ['Halloween', '할로윈', 'events', 1, 'noun'],
  ['Christmas', '크리스마스', 'events', 1, 'noun'],
  ['holiday', '공휴일', 'events', 1, 'noun'],
  ['vacation', '방학', 'events', 1, 'noun'],

  // ── technology (simple) ──
  ['computer', '컴퓨터', 'technology', 1, 'noun'],
  ['phone', '전화기', 'technology', 1, 'noun'],
  ['tablet', '태블릿', 'technology', 1, 'noun'],
  ['laptop', '노트북', 'technology', 1, 'noun'],
  ['camera', '카메라', 'technology', 1, 'noun'],
  ['radio', '라디오', 'technology', 1, 'noun'],
  ['television', '텔레비전', 'technology', 1, 'noun'],
  ['video', '비디오', 'technology', 1, 'noun'],
  ['internet', '인터넷', 'technology', 1, 'noun'],
  ['email', '이메일', 'technology', 1, 'noun'],
  ['website', '웹사이트', 'technology', 1, 'noun'],
  ['game', '게임', 'technology', 1, 'noun'],
  ['robot', '로봇', 'technology', 1, 'noun'],
  ['battery', '배터리', 'technology', 1, 'noun'],
  ['screen', '화면', 'technology', 1, 'noun'],
  ['keyboard', '키보드', 'technology', 1, 'noun'],
  ['printer', '프린터', 'technology', 1, 'noun'],
  ['headphones', '헤드폰', 'technology', 1, 'noun'],
  ['speaker', '스피커', 'technology', 1, 'noun'],
  ['charger', '충전기', 'technology', 1, 'noun'],

  // ── health (simple) ──
  ['healthy', '건강한', 'health', 1, 'adjective'],
  ['sick', '아픈', 'health', 1, 'adjective'],
  ['hurt', '다친', 'health', 1, 'adjective'],
  ['fever', '열', 'health', 1, 'noun'],
  ['cold', '감기', 'health', 1, 'noun'],
  ['cough', '기침', 'health', 1, 'noun'],
  ['headache', '두통', 'health', 1, 'noun'],
  ['stomachache', '배앓이', 'health', 2, 'noun'],
  ['toothache', '치통', 'health', 2, 'noun'],
  ['medicine', '약', 'health', 1, 'noun'],
  ['doctor', '의사', 'health', 1, 'noun'],
  ['hospital', '병원', 'health', 1, 'noun'],
  ['bandage', '반창고', 'health', 1, 'noun'],
  ['rest', '휴식', 'health', 1, 'noun'],
  ['exercise', '운동', 'health', 1, 'noun'],
  ['vitamin', '비타민', 'health', 2, 'noun'],
  ['allergy', '알레르기', 'health', 2, 'noun'],
  ['sneeze', '재채기', 'health', 1, 'noun'],
  ['bruise', '멍', 'health', 1, 'noun'],
  ['scratch', '긁힌 상처', 'health', 1, 'noun'],
];

export const extraGrade3Words: WordData[] = expand(DATA, 1);
