import type { WordData, PartOfSpeech } from '../../types/game';

type CW = [string, string, string, number, string];

function expand(words: CW[], startId: number): WordData[] {
  return words.map((w, i) => ({
    id: `g6x_${String(startId + i).padStart(4, '0')}`,
    english: w[0],
    korean: w[1],
    grade: 6 as const,
    category: w[2],
    difficulty: w[3] as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: w[4] as PartOfSpeech,
    exampleSentence: '',
    exampleKorean: '',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  }));
}

const DATA: CW[] = [
  // ── society & government ──
  ['democracy', '민주주의', 'government', 4, 'noun'],
  ['election', '선거', 'government', 4, 'noun'],
  ['vote', '투표', 'government', 3, 'noun'],
  ['president', '대통령', 'government', 3, 'noun'],
  ['government', '정부', 'government', 4, 'noun'],
  ['congress', '의회', 'government', 4, 'noun'],
  ['parliament', '국회', 'government', 4, 'noun'],
  ['senator', '상원의원', 'government', 4, 'noun'],
  ['representative', '대표', 'government', 5, 'noun'],
  ['mayor', '시장(직위)', 'government', 3, 'noun'],
  ['governor', '주지사', 'government', 4, 'noun'],
  ['minister', '장관', 'government', 4, 'noun'],
  ['ambassador', '대사', 'government', 5, 'noun'],
  ['diplomat', '외교관', 'government', 5, 'noun'],
  ['constitution', '헌법', 'government', 5, 'noun'],
  ['amendment', '개정안', 'government', 5, 'noun'],
  ['legislation', '법률', 'government', 5, 'noun'],
  ['regulation', '규제', 'government', 5, 'noun'],
  ['policy', '정책', 'government', 4, 'noun'],
  ['reform', '개혁', 'government', 4, 'noun'],
  ['rights', '권리', 'government', 3, 'noun'],
  ['liberty', '자유', 'government', 4, 'noun'],
  ['justice', '정의', 'government', 4, 'noun'],
  ['equality', '평등', 'government', 4, 'noun'],
  ['citizen', '시민', 'government', 3, 'noun'],
  ['patriot', '애국자', 'government', 4, 'noun'],
  ['nationalism', '국민주의', 'government', 5, 'noun'],
  ['capitalism', '자본주의', 'government', 5, 'noun'],
  ['socialism', '사회주의', 'government', 5, 'noun'],
  ['communism', '공산주의', 'government', 5, 'noun'],
  ['ideology', '이념', 'government', 5, 'noun'],
  ['campaign', '캠페인', 'government', 4, 'noun'],
  ['petition', '청원', 'government', 5, 'noun'],
  ['protest', '시위', 'government', 4, 'noun'],
  ['boycott', '불매운동', 'government', 5, 'noun'],
  ['sanction', '제재', 'government', 5, 'noun'],
  ['treaty', '조약', 'government', 4, 'noun'],
  ['diplomacy', '외교', 'government', 5, 'noun'],
  ['sovereignty', '주권', 'government', 5, 'noun'],
  ['territory', '영토', 'government', 4, 'noun'],
  ['republic', '공화국', 'government', 4, 'noun'],
  ['monarchy', '군주제', 'government', 4, 'noun'],
  ['dictatorship', '독재', 'government', 5, 'noun'],
  ['bureaucracy', '관료주의', 'government', 5, 'noun'],
  ['corruption', '부패', 'government', 5, 'noun'],
  ['transparency', '투명성', 'government', 5, 'noun'],
  ['accountability', '책임', 'government', 5, 'noun'],
  ['welfare', '복지', 'government', 4, 'noun'],
  ['taxation', '과세', 'government', 5, 'noun'],
  ['immigration', '이민', 'government', 5, 'noun'],

  // ── environment ──
  ['environment', '환경', 'environment', 3, 'noun'],
  ['pollution', '오염', 'environment', 4, 'noun'],
  ['climate change', '기후변화', 'environment', 4, 'noun'],
  ['global warming', '지구온난화', 'environment', 4, 'noun'],
  ['greenhouse effect', '온실 효과', 'environment', 5, 'noun'],
  ['carbon footprint', '탄소 발자국', 'environment', 5, 'noun'],
  ['carbon dioxide', '이산화탄소', 'environment', 5, 'noun'],
  ['methane', '메탄', 'environment', 5, 'noun'],
  ['ozone layer', '오존층', 'environment', 5, 'noun'],
  ['acid rain', '산성비', 'environment', 4, 'noun'],
  ['smog', '스모그', 'environment', 4, 'noun'],
  ['deforestation', '삼림 벌채', 'environment', 5, 'noun'],
  ['reforestation', '재조림', 'environment', 5, 'noun'],
  ['desertification', '사막화', 'environment', 5, 'noun'],
  ['biodiversity', '생물다양성', 'environment', 5, 'noun'],
  ['ecosystem', '생태계', 'environment', 4, 'noun'],
  ['habitat', '서식지', 'environment', 4, 'noun'],
  ['species', '종', 'environment', 4, 'noun'],
  ['endangered', '멸종위기의', 'environment', 4, 'adjective'],
  ['extinction', '멸종', 'environment', 4, 'noun'],
  ['conservation', '보존', 'environment', 4, 'noun'],
  ['preservation', '보전', 'environment', 5, 'noun'],
  ['sustainability', '지속가능성', 'environment', 5, 'noun'],
  ['renewable', '재생 가능한', 'environment', 4, 'adjective'],
  ['nonrenewable', '재생 불가능한', 'environment', 5, 'adjective'],
  ['solar energy', '태양 에너지', 'environment', 4, 'noun'],
  ['wind energy', '풍력 에너지', 'environment', 4, 'noun'],
  ['hydroelectric', '수력의', 'environment', 5, 'adjective'],
  ['geothermal', '지열의', 'environment', 5, 'adjective'],
  ['fossil fuel', '화석 연료', 'environment', 4, 'noun'],
  ['nuclear energy', '원자력', 'environment', 5, 'noun'],
  ['emission', '배출', 'environment', 5, 'noun'],
  ['waste', '폐기물', 'environment', 3, 'noun'],
  ['landfill', '매립지', 'environment', 5, 'noun'],
  ['compost', '퇴비', 'environment', 5, 'noun'],
  ['recycle', '재활용하다', 'environment', 3, 'verb'],
  ['reduce', '줄이다', 'environment', 3, 'verb'],
  ['reuse', '재사용하다', 'environment', 3, 'verb'],
  ['organic', '유기농의', 'environment', 4, 'adjective'],
  ['pesticide', '살충제', 'environment', 5, 'noun'],
  ['herbicide', '제초제', 'environment', 5, 'noun'],
  ['fertilizer', '비료', 'environment', 5, 'noun'],
  ['contamination', '오염', 'environment', 5, 'noun'],
  ['toxic', '독성의', 'environment', 4, 'adjective'],
  ['hazardous', '위험한', 'environment', 5, 'adjective'],
  ['biodegradable', '생분해성의', 'environment', 5, 'adjective'],
  ['ecological', '생태학적인', 'environment', 5, 'adjective'],
  ['carbon neutral', '탄소 중립의', 'environment', 5, 'adjective'],
  ['wildlife', '야생동물', 'environment', 3, 'noun'],
  ['marine', '해양의', 'environment', 4, 'adjective'],

  // ── advanced science concepts ──
  ['atom', '원자', 'science', 4, 'noun'],
  ['molecule', '분자', 'science', 4, 'noun'],
  ['element', '원소', 'science', 4, 'noun'],
  ['compound', '화합물', 'science', 5, 'noun'],
  ['reaction', '반응', 'science', 4, 'noun'],
  ['catalyst', '촉매', 'science', 5, 'noun'],
  ['electron', '전자', 'science', 5, 'noun'],
  ['proton', '양성자', 'science', 5, 'noun'],
  ['neutron', '중성자', 'science', 5, 'noun'],
  ['nucleus', '핵', 'science', 5, 'noun'],
  ['ion', '이온', 'science', 5, 'noun'],
  ['isotope', '동위원소', 'science', 5, 'noun'],
  ['periodic table', '주기율표', 'science', 5, 'noun'],
  ['hydrogen', '수소', 'science', 4, 'noun'],
  ['oxygen', '산소', 'science', 4, 'noun'],
  ['nitrogen', '질소', 'science', 4, 'noun'],
  ['helium', '헬륨', 'science', 4, 'noun'],
  ['sodium', '나트륨', 'science', 5, 'noun'],
  ['chlorine', '염소', 'science', 5, 'noun'],
  ['photosynthesis', '광합성', 'science', 5, 'noun'],
  ['osmosis', '삼투', 'science', 5, 'noun'],
  ['diffusion', '확산', 'science', 5, 'noun'],
  ['evaporation', '증발', 'science', 4, 'noun'],
  ['condensation', '응결', 'science', 5, 'noun'],
  ['precipitation', '강수', 'science', 5, 'noun'],
  ['sublimation', '승화', 'science', 5, 'noun'],
  ['combustion', '연소', 'science', 5, 'noun'],
  ['oxidation', '산화', 'science', 5, 'noun'],
  ['reduction', '환원', 'science', 5, 'noun'],
  ['electrolysis', '전기분해', 'science', 5, 'noun'],
  ['electromagnetic', '전자기의', 'science', 5, 'adjective'],
  ['spectrum', '스펙트럼', 'science', 5, 'noun'],
  ['wavelength', '파장', 'science', 5, 'noun'],
  ['amplitude', '진폭', 'science', 5, 'noun'],
  ['inertia', '관성', 'science', 5, 'noun'],
  ['momentum', '운동량', 'science', 5, 'noun'],
  ['acceleration', '가속도', 'science', 5, 'noun'],
  ['velocity', '속도', 'science', 5, 'noun'],
  ['kinetic', '운동의', 'science', 5, 'adjective'],
  ['potential', '위치의', 'science', 5, 'adjective'],
  ['thermal', '열의', 'science', 5, 'adjective'],
  ['conductor', '전도체', 'science', 5, 'noun'],
  ['insulator', '절연체', 'science', 5, 'noun'],
  ['semiconductor', '반도체', 'science', 5, 'noun'],
  ['circuit', '회로', 'science', 4, 'noun'],
  ['voltage', '전압', 'science', 5, 'noun'],
  ['current', '전류', 'science', 5, 'noun'],
  ['resistance', '저항', 'science', 5, 'noun'],
  ['magnetism', '자기', 'science', 5, 'noun'],
  ['relativity', '상대성', 'science', 5, 'noun'],

  // ── biology / genetics ──
  ['DNA', 'DNA', 'biology', 4, 'noun'],
  ['RNA', 'RNA', 'biology', 5, 'noun'],
  ['gene', '유전자', 'biology', 4, 'noun'],
  ['chromosome', '염색체', 'biology', 5, 'noun'],
  ['genetic', '유전의', 'biology', 4, 'adjective'],
  ['heredity', '유전', 'biology', 5, 'noun'],
  ['mutation', '돌연변이', 'biology', 5, 'noun'],
  ['natural selection', '자연선택', 'biology', 5, 'noun'],
  ['adaptation', '적응', 'biology', 4, 'noun'],
  ['evolution', '진화', 'biology', 4, 'noun'],
  ['cell', '세포', 'biology', 4, 'noun'],
  ['nucleus', '세포핵', 'biology', 5, 'noun'],
  ['membrane', '세포막', 'biology', 5, 'noun'],
  ['mitochondria', '미토콘드리아', 'biology', 5, 'noun'],
  ['chloroplast', '엽록체', 'biology', 5, 'noun'],
  ['mitosis', '유사분열', 'biology', 5, 'noun'],
  ['meiosis', '감수분열', 'biology', 5, 'noun'],
  ['protein', '단백질', 'biology', 4, 'noun'],
  ['enzyme', '효소', 'biology', 5, 'noun'],
  ['hormone', '호르몬', 'biology', 5, 'noun'],
  ['organ', '기관', 'biology', 4, 'noun'],
  ['tissue', '조직', 'biology', 5, 'noun'],
  ['nervous system', '신경계', 'biology', 5, 'noun'],
  ['digestive system', '소화계', 'biology', 5, 'noun'],
  ['circulatory system', '순환계', 'biology', 5, 'noun'],
  ['respiratory system', '호흡계', 'biology', 5, 'noun'],
  ['skeletal system', '골격계', 'biology', 5, 'noun'],
  ['muscular system', '근육계', 'biology', 5, 'noun'],
  ['ecosystem', '생태계', 'biology', 4, 'noun'],
  ['symbiosis', '공생', 'biology', 5, 'noun'],
  ['parasite', '기생충', 'biology', 5, 'noun'],
  ['pathogen', '병원체', 'biology', 5, 'noun'],
  ['antibody', '항체', 'biology', 5, 'noun'],
  ['vaccine', '백신', 'biology', 4, 'noun'],
  ['stem cell', '줄기세포', 'biology', 5, 'noun'],
  ['clone', '복제', 'biology', 5, 'noun'],
  ['biodiversity', '생물다양성', 'biology', 5, 'noun'],
  ['taxonomy', '분류학', 'biology', 5, 'noun'],
  ['kingdom', '계(생물)', 'biology', 4, 'noun'],
  ['phylum', '문(생물)', 'biology', 5, 'noun'],

  // ── advanced technology ──
  ['artificial intelligence', '인공지능', 'technology', 5, 'noun'],
  ['machine learning', '기계학습', 'technology', 5, 'noun'],
  ['robot', '로봇', 'technology', 3, 'noun'],
  ['automation', '자동화', 'technology', 5, 'noun'],
  ['nanotechnology', '나노기술', 'technology', 5, 'noun'],
  ['biotechnology', '생명공학', 'technology', 5, 'noun'],
  ['cybersecurity', '사이버보안', 'technology', 5, 'noun'],
  ['cryptocurrency', '암호화폐', 'technology', 5, 'noun'],
  ['blockchain', '블록체인', 'technology', 5, 'noun'],
  ['quantum computing', '양자 컴퓨팅', 'technology', 5, 'noun'],
  ['big data', '빅데이터', 'technology', 4, 'noun'],
  ['cloud computing', '클라우드 컴퓨팅', 'technology', 5, 'noun'],
  ['Internet of Things', '사물인터넷', 'technology', 5, 'noun'],
  ['5G', '5G', 'technology', 4, 'noun'],
  ['fiber optic', '광섬유', 'technology', 5, 'noun'],
  ['hologram', '홀로그램', 'technology', 5, 'noun'],
  ['laser', '레이저', 'technology', 4, 'noun'],
  ['radar', '레이더', 'technology', 4, 'noun'],
  ['sonar', '소나', 'technology', 5, 'noun'],
  ['telescope', '망원경', 'technology', 4, 'noun'],
  ['microscope', '현미경', 'technology', 4, 'noun'],
  ['laboratory', '연구실', 'technology', 4, 'noun'],
  ['simulator', '시뮬레이터', 'technology', 5, 'noun'],
  ['prototype', '시제품', 'technology', 5, 'noun'],
  ['patent', '특허', 'technology', 5, 'noun'],
  ['innovation', '혁신', 'technology', 4, 'noun'],
  ['obsolete', '구식의', 'technology', 5, 'adjective'],
  ['cutting-edge', '최첨단의', 'technology', 5, 'adjective'],
  ['wireless', '무선의', 'technology', 4, 'adjective'],
  ['portable', '휴대용의', 'technology', 4, 'adjective'],

  // ── philosophy / thinking ──
  ['philosophy', '철학', 'philosophy', 5, 'noun'],
  ['ethics', '윤리학', 'philosophy', 5, 'noun'],
  ['morality', '도덕', 'philosophy', 5, 'noun'],
  ['virtue', '미덕', 'philosophy', 5, 'noun'],
  ['wisdom', '지혜', 'philosophy', 4, 'noun'],
  ['knowledge', '지식', 'philosophy', 4, 'noun'],
  ['ignorance', '무지', 'philosophy', 5, 'noun'],
  ['logic', '논리', 'philosophy', 4, 'noun'],
  ['reasoning', '추론', 'philosophy', 5, 'noun'],
  ['argument', '논증', 'philosophy', 4, 'noun'],
  ['evidence', '증거', 'philosophy', 4, 'noun'],
  ['proof', '증명', 'philosophy', 4, 'noun'],
  ['hypothesis', '가설', 'philosophy', 5, 'noun'],
  ['theory', '이론', 'philosophy', 4, 'noun'],
  ['principle', '원칙', 'philosophy', 4, 'noun'],
  ['concept', '개념', 'philosophy', 4, 'noun'],
  ['perspective', '관점', 'philosophy', 5, 'noun'],
  ['bias', '편견', 'philosophy', 5, 'noun'],
  ['prejudice', '편견', 'philosophy', 5, 'noun'],
  ['stereotype', '고정관념', 'philosophy', 5, 'noun'],
  ['assumption', '가정', 'philosophy', 5, 'noun'],
  ['belief', '신념', 'philosophy', 4, 'noun'],
  ['doubt', '의심', 'philosophy', 4, 'noun'],
  ['certainty', '확신', 'philosophy', 5, 'noun'],
  ['ambiguity', '모호함', 'philosophy', 5, 'noun'],
  ['paradox', '역설', 'philosophy', 5, 'noun'],
  ['dilemma', '딜레마', 'philosophy', 5, 'noun'],
  ['controversy', '논란', 'philosophy', 5, 'noun'],
  ['consensus', '합의', 'philosophy', 5, 'noun'],
  ['compromise', '타협', 'philosophy', 5, 'noun'],
  ['conscience', '양심', 'philosophy', 5, 'noun'],
  ['empathy', '공감', 'philosophy', 5, 'noun'],
  ['compassion', '연민', 'philosophy', 5, 'noun'],
  ['integrity', '정직', 'philosophy', 5, 'noun'],
  ['dignity', '존엄', 'philosophy', 5, 'noun'],
  ['tolerance', '관용', 'philosophy', 5, 'noun'],
  ['diversity', '다양성', 'philosophy', 4, 'noun'],
  ['inclusion', '포용', 'philosophy', 5, 'noun'],
  ['equity', '공정', 'philosophy', 5, 'noun'],
  ['responsibility', '책임', 'philosophy', 4, 'noun'],

  // ── global issues ──
  ['globalization', '세계화', 'global', 5, 'noun'],
  ['urbanization', '도시화', 'global', 5, 'noun'],
  ['industrialization', '산업화', 'global', 5, 'noun'],
  ['poverty', '빈곤', 'global', 4, 'noun'],
  ['famine', '기근', 'global', 5, 'noun'],
  ['drought', '가뭄', 'global', 4, 'noun'],
  ['refugee', '난민', 'global', 5, 'noun'],
  ['humanitarian', '인도주의의', 'global', 5, 'adjective'],
  ['human rights', '인권', 'global', 4, 'noun'],
  ['child labor', '아동 노동', 'global', 4, 'noun'],
  ['literacy', '문해력', 'global', 5, 'noun'],
  ['inequality', '불평등', 'global', 5, 'noun'],
  ['discrimination', '차별', 'global', 5, 'noun'],
  ['terrorism', '테러', 'global', 5, 'noun'],
  ['nuclear weapon', '핵무기', 'global', 5, 'noun'],
  ['disarmament', '군축', 'global', 5, 'noun'],
  ['peacekeeping', '평화유지', 'global', 5, 'noun'],
  ['United Nations', '유엔', 'global', 4, 'noun'],
  ['NATO', '나토', 'global', 5, 'noun'],
  ['World Health Organization', '세계보건기구', 'global', 5, 'noun'],
  ['international', '국제적인', 'global', 4, 'adjective'],
  ['domestic', '국내의', 'global', 4, 'adjective'],
  ['foreign', '외국의', 'global', 4, 'adjective'],
  ['multilateral', '다자간의', 'global', 5, 'adjective'],
  ['bilateral', '양자간의', 'global', 5, 'adjective'],
  ['cooperation', '협력', 'global', 4, 'noun'],
  ['competition', '경쟁', 'global', 4, 'noun'],
  ['negotiation', '협상', 'global', 5, 'noun'],
  ['mediation', '중재', 'global', 5, 'noun'],
  ['resolution', '결의안', 'global', 5, 'noun'],

  // ── career / work ──
  ['career', '직업', 'career', 4, 'noun'],
  ['profession', '전문직', 'career', 4, 'noun'],
  ['occupation', '직업', 'career', 4, 'noun'],
  ['employment', '고용', 'career', 5, 'noun'],
  ['unemployment', '실업', 'career', 5, 'noun'],
  ['resume', '이력서', 'career', 5, 'noun'],
  ['interview', '면접', 'career', 4, 'noun'],
  ['qualification', '자격', 'career', 5, 'noun'],
  ['certificate', '자격증', 'career', 5, 'noun'],
  ['diploma', '졸업장', 'career', 5, 'noun'],
  ['degree', '학위', 'career', 4, 'noun'],
  ['scholarship', '장학금', 'career', 5, 'noun'],
  ['internship', '인턴십', 'career', 5, 'noun'],
  ['apprentice', '견습생', 'career', 5, 'noun'],
  ['mentor', '멘토', 'career', 4, 'noun'],
  ['colleague', '동료', 'career', 5, 'noun'],
  ['supervisor', '상사', 'career', 5, 'noun'],
  ['entrepreneur', '기업가', 'career', 5, 'noun'],
  ['CEO', '최고경영자', 'career', 4, 'noun'],
  ['startup', '스타트업', 'career', 4, 'noun'],
  ['corporation', '기업', 'career', 5, 'noun'],
  ['nonprofit', '비영리', 'career', 5, 'noun'],
  ['promotion', '승진', 'career', 5, 'noun'],
  ['retirement', '은퇴', 'career', 5, 'noun'],
  ['pension', '연금', 'career', 5, 'noun'],
  ['freelance', '프리랜서', 'career', 5, 'noun'],
  ['remote work', '재택근무', 'career', 4, 'noun'],
  ['commute', '통근', 'career', 5, 'noun'],
  ['workplace', '직장', 'career', 4, 'noun'],
  ['office', '사무실', 'career', 3, 'noun'],

  // ── psychology / mind ──
  ['psychology', '심리학', 'psychology', 5, 'noun'],
  ['behavior', '행동', 'psychology', 4, 'noun'],
  ['personality', '성격', 'psychology', 4, 'noun'],
  ['character', '성품', 'psychology', 4, 'noun'],
  ['temperament', '기질', 'psychology', 5, 'noun'],
  ['attitude', '태도', 'psychology', 4, 'noun'],
  ['motivation', '동기', 'psychology', 5, 'noun'],
  ['instinct', '본능', 'psychology', 5, 'noun'],
  ['intuition', '직감', 'psychology', 5, 'noun'],
  ['perception', '인식', 'psychology', 5, 'noun'],
  ['cognition', '인지', 'psychology', 5, 'noun'],
  ['memory', '기억', 'psychology', 4, 'noun'],
  ['concentration', '집중', 'psychology', 4, 'noun'],
  ['attention', '주의', 'psychology', 4, 'noun'],
  ['imagination', '상상력', 'psychology', 4, 'noun'],
  ['creativity', '창의력', 'psychology', 4, 'noun'],
  ['intelligence', '지능', 'psychology', 4, 'noun'],
  ['emotion', '감정', 'psychology', 4, 'noun'],
  ['mood', '기분', 'psychology', 4, 'noun'],
  ['stress', '스트레스', 'psychology', 4, 'noun'],
  ['anxiety', '불안', 'psychology', 5, 'noun'],
  ['depression', '우울증', 'psychology', 5, 'noun'],
  ['trauma', '트라우마', 'psychology', 5, 'noun'],
  ['therapy', '치료', 'psychology', 5, 'noun'],
  ['meditation', '명상', 'psychology', 4, 'noun'],
  ['mindfulness', '마음챙김', 'psychology', 5, 'noun'],
  ['self-esteem', '자존감', 'psychology', 5, 'noun'],
  ['confidence', '자신감', 'psychology', 4, 'noun'],
  ['resilience', '회복력', 'psychology', 5, 'noun'],
  ['wellbeing', '행복', 'psychology', 5, 'noun'],

  // ── advanced academic verbs ──
  ['abandon', '포기하다', 'academic_verbs', 4, 'verb'],
  ['abolish', '폐지하다', 'academic_verbs', 5, 'verb'],
  ['absorb', '흡수하다', 'academic_verbs', 4, 'verb'],
  ['accelerate', '가속하다', 'academic_verbs', 5, 'verb'],
  ['accomplish', '성취하다', 'academic_verbs', 4, 'verb'],
  ['accumulate', '축적하다', 'academic_verbs', 5, 'verb'],
  ['acknowledge', '인정하다', 'academic_verbs', 5, 'verb'],
  ['acquire', '습득하다', 'academic_verbs', 5, 'verb'],
  ['adapt', '적응하다', 'academic_verbs', 4, 'verb'],
  ['administer', '관리하다', 'academic_verbs', 5, 'verb'],
  ['advocate', '옹호하다', 'academic_verbs', 5, 'verb'],
  ['allocate', '배분하다', 'academic_verbs', 5, 'verb'],
  ['alter', '변경하다', 'academic_verbs', 4, 'verb'],
  ['anticipate', '예상하다', 'academic_verbs', 5, 'verb'],
  ['collaborate', '협력하다', 'academic_verbs', 5, 'verb'],
  ['compensate', '보상하다', 'academic_verbs', 5, 'verb'],
  ['compile', '편집하다', 'academic_verbs', 5, 'verb'],
  ['comprise', '구성하다', 'academic_verbs', 5, 'verb'],
  ['conceive', '구상하다', 'academic_verbs', 5, 'verb'],
  ['consolidate', '통합하다', 'academic_verbs', 5, 'verb'],
  ['constrain', '제한하다', 'academic_verbs', 5, 'verb'],
  ['contemplate', '심사숙고하다', 'academic_verbs', 5, 'verb'],
  ['contradict', '모순되다', 'academic_verbs', 5, 'verb'],
  ['cultivate', '경작하다', 'academic_verbs', 5, 'verb'],
  ['dedicate', '헌신하다', 'academic_verbs', 5, 'verb'],
  ['delegate', '위임하다', 'academic_verbs', 5, 'verb'],
  ['deliberate', '숙고하다', 'academic_verbs', 5, 'verb'],
  ['depict', '묘사하다', 'academic_verbs', 5, 'verb'],
  ['deploy', '배치하다', 'academic_verbs', 5, 'verb'],
  ['derive', '유래하다', 'academic_verbs', 5, 'verb'],
  ['deteriorate', '악화되다', 'academic_verbs', 5, 'verb'],
  ['devise', '고안하다', 'academic_verbs', 5, 'verb'],
  ['differentiate', '구별하다', 'academic_verbs', 5, 'verb'],
  ['diminish', '줄어들다', 'academic_verbs', 5, 'verb'],
  ['disclose', '공개하다', 'academic_verbs', 5, 'verb'],
  ['discriminate', '차별하다', 'academic_verbs', 5, 'verb'],
  ['displace', '이동시키다', 'academic_verbs', 5, 'verb'],
  ['dispose', '처분하다', 'academic_verbs', 5, 'verb'],
  ['dominate', '지배하다', 'academic_verbs', 5, 'verb'],
  ['elaborate', '상세히 설명하다', 'academic_verbs', 5, 'verb'],
  ['eliminate', '제거하다', 'academic_verbs', 5, 'verb'],
  ['emerge', '나타나다', 'academic_verbs', 4, 'verb'],
  ['encounter', '마주치다', 'academic_verbs', 5, 'verb'],
  ['enhance', '향상시키다', 'academic_verbs', 5, 'verb'],
  ['ensure', '보장하다', 'academic_verbs', 4, 'verb'],
  ['exploit', '이용하다', 'academic_verbs', 5, 'verb'],
  ['facilitate', '촉진하다', 'academic_verbs', 5, 'verb'],
  ['fluctuate', '변동하다', 'academic_verbs', 5, 'verb'],
  ['generate', '생성하다', 'academic_verbs', 5, 'verb'],
  ['implement', '실행하다', 'academic_verbs', 5, 'verb'],
  ['impose', '부과하다', 'academic_verbs', 5, 'verb'],
  ['incorporate', '통합하다', 'academic_verbs', 5, 'verb'],
  ['inhibit', '억제하다', 'academic_verbs', 5, 'verb'],
  ['initiate', '시작하다', 'academic_verbs', 5, 'verb'],
  ['integrate', '통합하다', 'academic_verbs', 5, 'verb'],
  ['manipulate', '조작하다', 'academic_verbs', 5, 'verb'],
  ['minimize', '최소화하다', 'academic_verbs', 5, 'verb'],
  ['modify', '수정하다', 'academic_verbs', 5, 'verb'],
  ['monitor', '감시하다', 'academic_verbs', 4, 'verb'],
  ['negotiate', '협상하다', 'academic_verbs', 5, 'verb'],
  ['obtain', '얻다', 'academic_verbs', 4, 'verb'],
  ['occupy', '차지하다', 'academic_verbs', 5, 'verb'],
  ['participate', '참여하다', 'academic_verbs', 4, 'verb'],
  ['perceive', '인식하다', 'academic_verbs', 5, 'verb'],
  ['persist', '고집하다', 'academic_verbs', 5, 'verb'],
  ['precede', '앞서다', 'academic_verbs', 5, 'verb'],
  ['presume', '추정하다', 'academic_verbs', 5, 'verb'],
  ['prohibit', '금지하다', 'academic_verbs', 5, 'verb'],
  ['pursue', '추구하다', 'academic_verbs', 5, 'verb'],
  ['refine', '정제하다', 'academic_verbs', 5, 'verb'],
  ['reinforce', '강화하다', 'academic_verbs', 5, 'verb'],
  ['restrain', '억제하다', 'academic_verbs', 5, 'verb'],
  ['restrict', '제한하다', 'academic_verbs', 5, 'verb'],
  ['retain', '유지하다', 'academic_verbs', 5, 'verb'],
  ['simulate', '모의실험하다', 'academic_verbs', 5, 'verb'],
  ['speculate', '추측하다', 'academic_verbs', 5, 'verb'],
  ['stimulate', '자극하다', 'academic_verbs', 5, 'verb'],
  ['subordinate', '종속시키다', 'academic_verbs', 5, 'verb'],
  ['supplement', '보충하다', 'academic_verbs', 5, 'verb'],
  ['sustain', '유지하다', 'academic_verbs', 5, 'verb'],
  ['terminate', '종료하다', 'academic_verbs', 5, 'verb'],
  ['transform', '변형시키다', 'academic_verbs', 5, 'verb'],
  ['transmit', '전송하다', 'academic_verbs', 5, 'verb'],
  ['undergo', '겪다', 'academic_verbs', 5, 'verb'],
  ['utilize', '활용하다', 'academic_verbs', 5, 'verb'],
  ['verify', '검증하다', 'academic_verbs', 5, 'verb'],
  ['violate', '위반하다', 'academic_verbs', 5, 'verb'],
  ['warrant', '보증하다', 'academic_verbs', 5, 'verb'],
  ['yield', '산출하다', 'academic_verbs', 5, 'verb'],

  // ── connectors / academic language ──
  ['therefore', '그러므로', 'connectors', 4, 'adverb'],
  ['however', '그러나', 'connectors', 4, 'adverb'],
  ['moreover', '게다가', 'connectors', 4, 'adverb'],
  ['furthermore', '더욱이', 'connectors', 5, 'adverb'],
  ['nevertheless', '그럼에도 불구하고', 'connectors', 5, 'adverb'],
  ['consequently', '결과적으로', 'connectors', 5, 'adverb'],
  ['meanwhile', '한편', 'connectors', 4, 'adverb'],
  ['alternatively', '대안적으로', 'connectors', 5, 'adverb'],
  ['conversely', '반대로', 'connectors', 5, 'adverb'],
  ['subsequently', '그 후에', 'connectors', 5, 'adverb'],
  ['presumably', '아마도', 'connectors', 5, 'adverb'],
  ['approximately', '대략', 'connectors', 4, 'adverb'],
  ['significantly', '상당히', 'connectors', 5, 'adverb'],
  ['considerably', '상당히', 'connectors', 5, 'adverb'],
  ['predominantly', '주로', 'connectors', 5, 'adverb'],
  ['ultimately', '궁극적으로', 'connectors', 5, 'adverb'],
  ['primarily', '주로', 'connectors', 5, 'adverb'],
  ['inevitably', '필연적으로', 'connectors', 5, 'adverb'],
  ['presumably', '추정컨대', 'connectors', 5, 'adverb'],
  ['regardless', '상관없이', 'connectors', 5, 'adverb'],

  // ── law & justice ──
  ['court', '법원', 'law', 4, 'noun'],
  ['trial', '재판', 'law', 4, 'noun'],
  ['jury', '배심원', 'law', 5, 'noun'],
  ['verdict', '판결', 'law', 5, 'noun'],
  ['sentence', '선고', 'law', 4, 'noun'],
  ['appeal', '항소', 'law', 5, 'noun'],
  ['defendant', '피고', 'law', 5, 'noun'],
  ['plaintiff', '원고', 'law', 5, 'noun'],
  ['prosecutor', '검사', 'law', 5, 'noun'],
  ['attorney', '변호사', 'law', 5, 'noun'],
  ['witness', '증인', 'law', 4, 'noun'],
  ['testimony', '증언', 'law', 5, 'noun'],
  ['evidence', '증거', 'law', 4, 'noun'],
  ['allegation', '혐의', 'law', 5, 'noun'],
  ['conviction', '유죄판결', 'law', 5, 'noun'],
  ['acquittal', '무죄판결', 'law', 5, 'noun'],
  ['bail', '보석금', 'law', 5, 'noun'],
  ['parole', '가석방', 'law', 5, 'noun'],
  ['probation', '집행유예', 'law', 5, 'noun'],
  ['penalty', '벌칙', 'law', 4, 'noun'],
  ['fine', '벌금', 'law', 4, 'noun'],
  ['prison', '감옥', 'law', 4, 'noun'],
  ['crime', '범죄', 'law', 4, 'noun'],
  ['criminal', '범죄자', 'law', 4, 'noun'],
  ['offense', '범행', 'law', 5, 'noun'],
  ['violation', '위반', 'law', 5, 'noun'],
  ['fraud', '사기', 'law', 5, 'noun'],
  ['theft', '절도', 'law', 5, 'noun'],
  ['vandalism', '기물파손', 'law', 5, 'noun'],
  ['arson', '방화', 'law', 5, 'noun'],

  // ── economics advanced ──
  ['capitalism', '자본주의', 'economics', 5, 'noun'],
  ['monopoly', '독점', 'economics', 5, 'noun'],
  ['competition', '경쟁', 'economics', 4, 'noun'],
  ['consumer', '소비자', 'economics', 4, 'noun'],
  ['producer', '생산자', 'economics', 4, 'noun'],
  ['entrepreneur', '기업가', 'economics', 5, 'noun'],
  ['corporation', '기업', 'economics', 5, 'noun'],
  ['shareholder', '주주', 'economics', 5, 'noun'],
  ['dividend', '배당금', 'economics', 5, 'noun'],
  ['bankruptcy', '파산', 'economics', 5, 'noun'],
  ['subsidy', '보조금', 'economics', 5, 'noun'],
  ['tariff', '관세', 'economics', 5, 'noun'],
  ['quota', '할당량', 'economics', 5, 'noun'],
  ['deficit', '적자', 'economics', 5, 'noun'],
  ['surplus', '흑자', 'economics', 5, 'noun'],
  ['GDP', '국내총생산', 'economics', 5, 'noun'],
  ['inflation', '인플레이션', 'economics', 5, 'noun'],
  ['deflation', '디플레이션', 'economics', 5, 'noun'],
  ['recession', '불경기', 'economics', 5, 'noun'],
  ['depression', '대공황', 'economics', 5, 'noun'],
  ['commodity', '상품', 'economics', 5, 'noun'],
  ['resource', '자원', 'economics', 4, 'noun'],
  ['raw material', '원자재', 'economics', 5, 'noun'],
  ['infrastructure', '인프라', 'economics', 5, 'noun'],
  ['globalization', '세계화', 'economics', 5, 'noun'],
  ['outsourcing', '외주', 'economics', 5, 'noun'],
  ['privatization', '민영화', 'economics', 5, 'noun'],
  ['deregulation', '규제 완화', 'economics', 5, 'noun'],
  ['fiscal', '재정의', 'economics', 5, 'adjective'],
  ['monetary', '통화의', 'economics', 5, 'adjective'],

  // ── sociology / anthropology ──
  ['anthropology', '인류학', 'social_science', 5, 'noun'],
  ['sociology', '사회학', 'social_science', 5, 'noun'],
  ['demographics', '인구통계', 'social_science', 5, 'noun'],
  ['census', '인구조사', 'social_science', 5, 'noun'],
  ['urbanization', '도시화', 'social_science', 5, 'noun'],
  ['migration', '이주', 'social_science', 5, 'noun'],
  ['assimilation', '동화', 'social_science', 5, 'noun'],
  ['segregation', '분리', 'social_science', 5, 'noun'],
  ['integration', '통합', 'social_science', 5, 'noun'],
  ['hierarchy', '위계', 'social_science', 5, 'noun'],
  ['class', '계층', 'social_science', 4, 'noun'],
  ['caste', '카스트', 'social_science', 5, 'noun'],
  ['norm', '규범', 'social_science', 5, 'noun'],
  ['taboo', '금기', 'social_science', 5, 'noun'],
  ['ritual', '의식', 'social_science', 5, 'noun'],
  ['artifact', '유물', 'social_science', 5, 'noun'],
  ['excavation', '발굴', 'social_science', 5, 'noun'],
  ['civilization', '문명', 'social_science', 4, 'noun'],
  ['indigenous', '토착의', 'social_science', 5, 'adjective'],
  ['ethnic', '민족의', 'social_science', 5, 'adjective'],
  ['cultural', '문화적인', 'social_science', 4, 'adjective'],
  ['social', '사회적인', 'social_science', 4, 'adjective'],
  ['communal', '공동의', 'social_science', 5, 'adjective'],
  ['secular', '세속적인', 'social_science', 5, 'adjective'],
  ['sacred', '신성한', 'social_science', 5, 'adjective'],
  ['patriarchal', '가부장적인', 'social_science', 5, 'adjective'],
  ['matriarchal', '모계의', 'social_science', 5, 'adjective'],
  ['nomadic', '유목의', 'social_science', 5, 'adjective'],
  ['agrarian', '농업의', 'social_science', 5, 'adjective'],
  ['feudal', '봉건의', 'social_science', 5, 'adjective'],

  // ── literary / writing terms ──
  ['allegory', '우화', 'literary', 5, 'noun'],
  ['alliteration', '두운', 'literary', 5, 'noun'],
  ['analogy', '유추', 'literary', 5, 'noun'],
  ['anecdote', '일화', 'literary', 5, 'noun'],
  ['antagonist', '적대자', 'literary', 5, 'noun'],
  ['protagonist', '주인공', 'literary', 5, 'noun'],
  ['archetype', '원형', 'literary', 5, 'noun'],
  ['climax', '절정', 'literary', 5, 'noun'],
  ['denouement', '결말', 'literary', 5, 'noun'],
  ['dialogue', '대화', 'literary', 4, 'noun'],
  ['monologue', '독백', 'literary', 5, 'noun'],
  ['epilogue', '에필로그', 'literary', 5, 'noun'],
  ['prologue', '프롤로그', 'literary', 5, 'noun'],
  ['foreshadowing', '복선', 'literary', 5, 'noun'],
  ['flashback', '회상', 'literary', 5, 'noun'],
  ['hyperbole', '과장', 'literary', 5, 'noun'],
  ['imagery', '심상', 'literary', 5, 'noun'],
  ['irony', '아이러니', 'literary', 5, 'noun'],
  ['satire', '풍자', 'literary', 5, 'noun'],
  ['symbolism', '상징주의', 'literary', 5, 'noun'],
  ['motif', '모티프', 'literary', 5, 'noun'],
  ['narrative', '서사', 'literary', 5, 'noun'],
  ['omniscient', '전지의', 'literary', 5, 'adjective'],
  ['perspective', '시점', 'literary', 4, 'noun'],
  ['rhetoric', '수사학', 'literary', 5, 'noun'],
  ['stanza', '연(시)', 'literary', 5, 'noun'],
  ['verse', '운문', 'literary', 5, 'noun'],
  ['prose', '산문', 'literary', 5, 'noun'],
  ['genre', '장르', 'literary', 4, 'noun'],
  ['memoir', '회고록', 'literary', 5, 'noun'],

  // ── advanced adjectives ──
  ['ambiguous', '모호한', 'advanced_adj', 5, 'adjective'],
  ['anonymous', '익명의', 'advanced_adj', 5, 'adjective'],
  ['arbitrary', '임의의', 'advanced_adj', 5, 'adjective'],
  ['autonomous', '자율적인', 'advanced_adj', 5, 'adjective'],
  ['coherent', '일관된', 'advanced_adj', 5, 'adjective'],
  ['compatible', '호환되는', 'advanced_adj', 5, 'adjective'],
  ['competent', '유능한', 'advanced_adj', 5, 'adjective'],
  ['compulsory', '의무적인', 'advanced_adj', 5, 'adjective'],
  ['concurrent', '동시의', 'advanced_adj', 5, 'adjective'],
  ['conducive', '도움이 되는', 'advanced_adj', 5, 'adjective'],
  ['consecutive', '연속적인', 'advanced_adj', 5, 'adjective'],
  ['contemporary', '현대의', 'advanced_adj', 5, 'adjective'],
  ['cumulative', '누적의', 'advanced_adj', 5, 'adjective'],
  ['definitive', '결정적인', 'advanced_adj', 5, 'adjective'],
  ['demographic', '인구통계의', 'advanced_adj', 5, 'adjective'],
  ['empirical', '경험적인', 'advanced_adj', 5, 'adjective'],
  ['explicit', '명시적인', 'advanced_adj', 5, 'adjective'],
  ['implicit', '암시적인', 'advanced_adj', 5, 'adjective'],
  ['feasible', '실현 가능한', 'advanced_adj', 5, 'adjective'],
  ['hypothetical', '가정의', 'advanced_adj', 5, 'adjective'],
  ['ideological', '이념적인', 'advanced_adj', 5, 'adjective'],
  ['inherent', '고유한', 'advanced_adj', 5, 'adjective'],
  ['integral', '필수적인', 'advanced_adj', 5, 'adjective'],
  ['mandatory', '의무적인', 'advanced_adj', 5, 'adjective'],
  ['marginal', '주변의', 'advanced_adj', 5, 'adjective'],
  ['nominal', '명목상의', 'advanced_adj', 5, 'adjective'],
  ['optimal', '최적의', 'advanced_adj', 5, 'adjective'],
  ['paradoxical', '역설적인', 'advanced_adj', 5, 'adjective'],
  ['peripheral', '주변부의', 'advanced_adj', 5, 'adjective'],
  ['plausible', '그럴듯한', 'advanced_adj', 5, 'adjective'],
  ['pragmatic', '실용적인', 'advanced_adj', 5, 'adjective'],
  ['predominant', '우세한', 'advanced_adj', 5, 'adjective'],
  ['preliminary', '예비의', 'advanced_adj', 5, 'adjective'],
  ['presumed', '추정된', 'advanced_adj', 5, 'adjective'],
  ['prevalent', '만연한', 'advanced_adj', 5, 'adjective'],
  ['profound', '심오한', 'advanced_adj', 5, 'adjective'],
  ['progressive', '진보적인', 'advanced_adj', 5, 'adjective'],
  ['proportional', '비례하는', 'advanced_adj', 5, 'adjective'],
  ['provisional', '임시의', 'advanced_adj', 5, 'adjective'],
  ['qualitative', '질적인', 'advanced_adj', 5, 'adjective'],
  ['quantitative', '양적인', 'advanced_adj', 5, 'adjective'],
  ['redundant', '불필요한', 'advanced_adj', 5, 'adjective'],
  ['retrospective', '회고적인', 'advanced_adj', 5, 'adjective'],
  ['rigorous', '엄격한', 'advanced_adj', 5, 'adjective'],
  ['simultaneous', '동시의', 'advanced_adj', 5, 'adjective'],
  ['spontaneous', '자발적인', 'advanced_adj', 5, 'adjective'],
  ['strategic', '전략적인', 'advanced_adj', 5, 'adjective'],
  ['systematic', '체계적인', 'advanced_adj', 5, 'adjective'],
  ['tentative', '잠정적인', 'advanced_adj', 5, 'adjective'],
  ['viable', '실행 가능한', 'advanced_adj', 5, 'adjective'],

  // ── advanced nouns (academic) ──
  ['abstract', '요약', 'advanced_nouns', 5, 'noun'],
  ['analogy', '유추', 'advanced_nouns', 5, 'noun'],
  ['anomaly', '이상 현상', 'advanced_nouns', 5, 'noun'],
  ['apparatus', '장치', 'advanced_nouns', 5, 'noun'],
  ['appendix', '부록', 'advanced_nouns', 5, 'noun'],
  ['assessment', '평가', 'advanced_nouns', 4, 'noun'],
  ['benchmark', '기준점', 'advanced_nouns', 5, 'noun'],
  ['bibliography', '참고문헌', 'advanced_nouns', 5, 'noun'],
  ['catalyst', '촉매제', 'advanced_nouns', 5, 'noun'],
  ['chronology', '연대기', 'advanced_nouns', 5, 'noun'],
  ['citation', '인용', 'advanced_nouns', 5, 'noun'],
  ['cohort', '집단', 'advanced_nouns', 5, 'noun'],
  ['compilation', '편집물', 'advanced_nouns', 5, 'noun'],
  ['connotation', '내포', 'advanced_nouns', 5, 'noun'],
  ['denotation', '외연', 'advanced_nouns', 5, 'noun'],
  ['correlation', '상관관계', 'advanced_nouns', 5, 'noun'],
  ['curriculum', '교육과정', 'advanced_nouns', 5, 'noun'],
  ['discourse', '담론', 'advanced_nouns', 5, 'noun'],
  ['disparity', '격차', 'advanced_nouns', 5, 'noun'],
  ['doctrine', '교리', 'advanced_nouns', 5, 'noun'],
  ['entity', '실체', 'advanced_nouns', 5, 'noun'],
  ['excerpt', '발췌', 'advanced_nouns', 5, 'noun'],
  ['fallacy', '오류', 'advanced_nouns', 5, 'noun'],
  ['hierarchy', '위계', 'advanced_nouns', 5, 'noun'],
  ['hypothesis', '가설', 'advanced_nouns', 5, 'noun'],
  ['implication', '함의', 'advanced_nouns', 5, 'noun'],
  ['incentive', '인센티브', 'advanced_nouns', 5, 'noun'],
  ['index', '색인', 'advanced_nouns', 5, 'noun'],
  ['infrastructure', '사회기반시설', 'advanced_nouns', 5, 'noun'],
  ['jurisdiction', '관할권', 'advanced_nouns', 5, 'noun'],
  ['methodology', '방법론', 'advanced_nouns', 5, 'noun'],
  ['paradigm', '패러다임', 'advanced_nouns', 5, 'noun'],
  ['parameter', '매개변수', 'advanced_nouns', 5, 'noun'],
  ['phenomenon', '현상', 'advanced_nouns', 5, 'noun'],
  ['portfolio', '포트폴리오', 'advanced_nouns', 5, 'noun'],
  ['precedent', '선례', 'advanced_nouns', 5, 'noun'],
  ['premise', '전제', 'advanced_nouns', 5, 'noun'],
  ['protocol', '프로토콜', 'advanced_nouns', 5, 'noun'],
  ['quota', '할당량', 'advanced_nouns', 5, 'noun'],
  ['rationale', '근거', 'advanced_nouns', 5, 'noun'],
  ['spectrum', '스펙트럼', 'advanced_nouns', 5, 'noun'],
  ['synthesis', '통합', 'advanced_nouns', 5, 'noun'],
  ['thesis', '논문', 'advanced_nouns', 5, 'noun'],
  ['threshold', '한계점', 'advanced_nouns', 5, 'noun'],
  ['trajectory', '궤적', 'advanced_nouns', 5, 'noun'],
  ['variable', '변수', 'advanced_nouns', 5, 'noun'],
  ['venue', '장소', 'advanced_nouns', 5, 'noun'],
  ['versus', '대', 'advanced_nouns', 4, 'preposition'],
  ['via', '통하여', 'advanced_nouns', 4, 'preposition'],
  ['whereby', '그것에 의해', 'advanced_nouns', 5, 'adverb'],

  // ── world history / ancient civilizations ──
  ['pharaoh', '파라오', 'history', 5, 'noun'],
  ['gladiator', '검투사', 'history', 5, 'noun'],
  ['colosseum', '콜로세움', 'history', 5, 'noun'],
  ['acropolis', '아크로폴리스', 'history', 5, 'noun'],
  ['renaissance', '르네상스', 'history', 5, 'noun'],
  ['reformation', '종교개혁', 'history', 5, 'noun'],
  ['enlightenment', '계몽주의', 'history', 5, 'noun'],
  ['feudalism', '봉건제', 'history', 5, 'noun'],
  ['imperialism', '제국주의', 'history', 5, 'noun'],
  ['colonialism', '식민주의', 'history', 5, 'noun'],
  ['industrialization', '산업화', 'history', 5, 'noun'],
  ['emancipation', '해방', 'history', 5, 'noun'],
  ['suffrage', '선거권', 'history', 5, 'noun'],
  ['abolition', '폐지', 'history', 5, 'noun'],
  ['segregation', '인종차별', 'history', 5, 'noun'],
  ['civil rights', '시민권', 'history', 4, 'noun'],
  ['apartheid', '아파르트헤이트', 'history', 5, 'noun'],
  ['genocide', '집단학살', 'history', 5, 'noun'],
  ['holocaust', '대학살', 'history', 5, 'noun'],
  ['armistice', '휴전', 'history', 5, 'noun'],
  ['coup', '쿠데타', 'history', 5, 'noun'],
  ['propaganda', '선전', 'history', 5, 'noun'],
  ['manifesto', '선언문', 'history', 5, 'noun'],
  ['ideology', '이데올로기', 'history', 5, 'noun'],
  ['sovereignty', '주권', 'history', 5, 'noun'],
  ['monarchy', '왕정', 'history', 5, 'noun'],
  ['theocracy', '신정정치', 'history', 5, 'noun'],
  ['oligarchy', '과두제', 'history', 5, 'noun'],
  ['anarchy', '무정부 상태', 'history', 5, 'noun'],
  ['tyranny', '폭정', 'history', 5, 'noun'],

  // ── medicine / health advanced ──
  ['anatomy', '해부학', 'medicine', 5, 'noun'],
  ['physiology', '생리학', 'medicine', 5, 'noun'],
  ['pathology', '병리학', 'medicine', 5, 'noun'],
  ['neurology', '신경학', 'medicine', 5, 'noun'],
  ['cardiology', '심장학', 'medicine', 5, 'noun'],
  ['oncology', '종양학', 'medicine', 5, 'noun'],
  ['pediatrics', '소아과', 'medicine', 5, 'noun'],
  ['orthopedics', '정형외과', 'medicine', 5, 'noun'],
  ['dermatology', '피부과', 'medicine', 5, 'noun'],
  ['ophthalmology', '안과학', 'medicine', 5, 'noun'],
  ['radiology', '방사선학', 'medicine', 5, 'noun'],
  ['anesthesia', '마취', 'medicine', 5, 'noun'],
  ['transplant', '이식', 'medicine', 5, 'noun'],
  ['prosthesis', '의수/의족', 'medicine', 5, 'noun'],
  ['rehabilitation', '재활', 'medicine', 5, 'noun'],
  ['clinical', '임상의', 'medicine', 5, 'adjective'],
  ['surgical', '수술의', 'medicine', 5, 'adjective'],
  ['pharmaceutical', '제약의', 'medicine', 5, 'adjective'],
  ['therapeutic', '치료의', 'medicine', 5, 'adjective'],
  ['diagnostic', '진단의', 'medicine', 5, 'adjective'],

  // ── mathematics advanced ──
  ['algebra', '대수학', 'mathematics', 4, 'noun'],
  ['calculus', '미적분', 'mathematics', 5, 'noun'],
  ['trigonometry', '삼각법', 'mathematics', 5, 'noun'],
  ['polynomial', '다항식', 'mathematics', 5, 'noun'],
  ['coefficient', '계수', 'mathematics', 5, 'noun'],
  ['matrix', '행렬', 'mathematics', 5, 'noun'],
  ['theorem', '정리', 'mathematics', 5, 'noun'],
  ['axiom', '공리', 'mathematics', 5, 'noun'],
  ['proof', '증명', 'mathematics', 4, 'noun'],
  ['inequality', '부등식', 'mathematics', 5, 'noun'],
  ['logarithm', '로그', 'mathematics', 5, 'noun'],
  ['exponential', '지수의', 'mathematics', 5, 'adjective'],
  ['rational number', '유리수', 'mathematics', 5, 'noun'],
  ['irrational number', '무리수', 'mathematics', 5, 'noun'],
  ['prime number', '소수', 'mathematics', 4, 'noun'],
  ['composite', '합성의', 'mathematics', 5, 'adjective'],
  ['congruent', '합동의', 'mathematics', 5, 'adjective'],
  ['tangent', '접선', 'mathematics', 5, 'noun'],
  ['vertex', '꼭짓점', 'mathematics', 5, 'noun'],
  ['polygon', '다각형', 'mathematics', 4, 'noun'],
  ['polyhedron', '다면체', 'mathematics', 5, 'noun'],
  ['tessellation', '테셀레이션', 'mathematics', 5, 'noun'],
  ['coordinate', '좌표', 'mathematics', 4, 'noun'],
  ['quadrant', '사분면', 'mathematics', 5, 'noun'],
  ['intersection', '교점', 'mathematics', 5, 'noun'],

  // ── advanced verbs (grade 6 level) ──
  ['abstain', '삼가다', 'verbs_adv', 5, 'verb'],
  ['alleviate', '완화하다', 'verbs_adv', 5, 'verb'],
  ['amalgamate', '합병하다', 'verbs_adv', 5, 'verb'],
  ['articulate', '명확히 말하다', 'verbs_adv', 5, 'verb'],
  ['augment', '증대시키다', 'verbs_adv', 5, 'verb'],
  ['circumvent', '우회하다', 'verbs_adv', 5, 'verb'],
  ['coerce', '강요하다', 'verbs_adv', 5, 'verb'],
  ['commend', '칭찬하다', 'verbs_adv', 5, 'verb'],
  ['comply', '따르다', 'verbs_adv', 5, 'verb'],
  ['concede', '인정하다', 'verbs_adv', 5, 'verb'],
  ['condone', '묵인하다', 'verbs_adv', 5, 'verb'],
  ['confiscate', '몰수하다', 'verbs_adv', 5, 'verb'],
  ['converge', '수렴하다', 'verbs_adv', 5, 'verb'],
  ['correlate', '상관시키다', 'verbs_adv', 5, 'verb'],
  ['debilitate', '약화시키다', 'verbs_adv', 5, 'verb'],
  ['denounce', '비난하다', 'verbs_adv', 5, 'verb'],
  ['deplete', '고갈시키다', 'verbs_adv', 5, 'verb'],
  ['deter', '단념시키다', 'verbs_adv', 5, 'verb'],
  ['discern', '분별하다', 'verbs_adv', 5, 'verb'],
  ['disperse', '흩뿌리다', 'verbs_adv', 5, 'verb'],
  ['disseminate', '유포하다', 'verbs_adv', 5, 'verb'],
  ['elicit', '이끌어내다', 'verbs_adv', 5, 'verb'],
  ['emulate', '모방하다', 'verbs_adv', 5, 'verb'],
  ['endorse', '지지하다', 'verbs_adv', 5, 'verb'],
  ['enumerate', '열거하다', 'verbs_adv', 5, 'verb'],
  ['eradicate', '근절하다', 'verbs_adv', 5, 'verb'],
  ['exacerbate', '악화시키다', 'verbs_adv', 5, 'verb'],
  ['exemplify', '예시하다', 'verbs_adv', 5, 'verb'],
  ['expedite', '신속 처리하다', 'verbs_adv', 5, 'verb'],
  ['extrapolate', '추정하다', 'verbs_adv', 5, 'verb'],
  ['fabricate', '조작하다', 'verbs_adv', 5, 'verb'],
  ['formulate', '공식화하다', 'verbs_adv', 5, 'verb'],
  ['incite', '선동하다', 'verbs_adv', 5, 'verb'],
  ['indemnify', '배상하다', 'verbs_adv', 5, 'verb'],
  ['instigate', '선동하다', 'verbs_adv', 5, 'verb'],
  ['mitigate', '완화하다', 'verbs_adv', 5, 'verb'],
  ['perpetuate', '영속시키다', 'verbs_adv', 5, 'verb'],
  ['precipitate', '촉발하다', 'verbs_adv', 5, 'verb'],
  ['proliferate', '급증하다', 'verbs_adv', 5, 'verb'],
  ['promulgate', '공포하다', 'verbs_adv', 5, 'verb'],
  ['reconcile', '화해시키다', 'verbs_adv', 5, 'verb'],
  ['rectify', '시정하다', 'verbs_adv', 5, 'verb'],
  ['rehabilitate', '재활시키다', 'verbs_adv', 5, 'verb'],
  ['relinquish', '포기하다', 'verbs_adv', 5, 'verb'],
  ['replenish', '보충하다', 'verbs_adv', 5, 'verb'],
  ['scrutinize', '면밀히 조사하다', 'verbs_adv', 5, 'verb'],
  ['stipulate', '규정하다', 'verbs_adv', 5, 'verb'],
  ['substantiate', '입증하다', 'verbs_adv', 5, 'verb'],
  ['supersede', '대체하다', 'verbs_adv', 5, 'verb'],
  ['transcend', '초월하다', 'verbs_adv', 5, 'verb'],

  // ── media / journalism ──
  ['anchor', '앵커', 'media', 4, 'noun'],
  ['bias', '편향', 'media', 5, 'noun'],
  ['broadcast', '방송', 'media', 4, 'noun'],
  ['column', '칼럼', 'media', 4, 'noun'],
  ['correspondent', '특파원', 'media', 5, 'noun'],
  ['editorial', '사설', 'media', 5, 'noun'],
  ['expose', '폭로 기사', 'media', 5, 'noun'],
  ['headline', '헤드라인', 'media', 4, 'noun'],
  ['investigative', '탐사의', 'media', 5, 'adjective'],
  ['journalist', '기자', 'media', 4, 'noun'],
  ['mainstream', '주류의', 'media', 5, 'adjective'],
  ['misinformation', '오정보', 'media', 5, 'noun'],
  ['objectivity', '객관성', 'media', 5, 'noun'],
  ['outlet', '매체', 'media', 5, 'noun'],
  ['press conference', '기자회견', 'media', 4, 'noun'],
  ['propaganda', '선전활동', 'media', 5, 'noun'],
  ['publication', '출판물', 'media', 5, 'noun'],
  ['sensationalism', '선정주의', 'media', 5, 'noun'],
  ['source', '출처', 'media', 4, 'noun'],
  ['tabloid', '타블로이드', 'media', 5, 'noun'],

  // ── more philosophy / ethics ──
  ['altruism', '이타주의', 'ethics', 5, 'noun'],
  ['autonomy', '자율', 'ethics', 5, 'noun'],
  ['benevolence', '자비', 'ethics', 5, 'noun'],
  ['categorical', '범주적인', 'ethics', 5, 'adjective'],
  ['consequentialism', '결과주의', 'ethics', 5, 'noun'],
  ['deontology', '의무론', 'ethics', 5, 'noun'],
  ['determinism', '결정론', 'ethics', 5, 'noun'],
  ['dualism', '이원론', 'ethics', 5, 'noun'],
  ['empiricism', '경험주의', 'ethics', 5, 'noun'],
  ['epistemology', '인식론', 'ethics', 5, 'noun'],
  ['existentialism', '실존주의', 'ethics', 5, 'noun'],
  ['hedonism', '쾌락주의', 'ethics', 5, 'noun'],
  ['idealism', '이상주의', 'ethics', 5, 'noun'],
  ['materialism', '유물론', 'ethics', 5, 'noun'],
  ['metaphysics', '형이상학', 'ethics', 5, 'noun'],
  ['nihilism', '허무주의', 'ethics', 5, 'noun'],
  ['ontology', '존재론', 'ethics', 5, 'noun'],
  ['pragmatism', '실용주의', 'ethics', 5, 'noun'],
  ['rationalism', '합리주의', 'ethics', 5, 'noun'],
  ['utilitarianism', '공리주의', 'ethics', 5, 'noun'],
];

export const extraGrade6Words: WordData[] = expand(DATA, 1);
