import type { WordData, PartOfSpeech } from '../../types/game';

type CW = [string, string, string, number, string];

function expand(words: CW[], startId: number): WordData[] {
  return words.map((w, i) => ({
    id: `g4x_${String(startId + i).padStart(4, '0')}`,
    english: w[0],
    korean: w[1],
    grade: 4 as const,
    category: w[2],
    difficulty: w[3] as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: w[4] as PartOfSpeech,
    exampleSentence: '',
    exampleKorean: '',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  }));
}

const DATA: CW[] = [
  // ── professions (extras not in existing) ──
  ['police', '경찰', 'jobs', 2, 'noun'],
  ['surgeon', '외과의사', 'jobs', 3, 'noun'],
  ['therapist', '치료사', 'jobs', 3, 'noun'],
  ['pharmacist', '약사', 'jobs', 3, 'noun'],
  ['paramedic', '응급구조사', 'jobs', 3, 'noun'],
  ['mechanic', '정비사', 'jobs', 2, 'noun'],
  ['carpenter', '목수', 'jobs', 2, 'noun'],
  ['plumber', '배관공', 'jobs', 2, 'noun'],
  ['electrician', '전기기사', 'jobs', 3, 'noun'],
  ['barber', '이발사', 'jobs', 2, 'noun'],
  ['tailor', '재봉사', 'jobs', 2, 'noun'],
  ['butcher', '정육업자', 'jobs', 2, 'noun'],
  ['florist', '꽃집 주인', 'jobs', 2, 'noun'],
  ['janitor', '관리인', 'jobs', 2, 'noun'],
  ['cashier', '계산원', 'jobs', 2, 'noun'],
  ['waiter', '웨이터', 'jobs', 2, 'noun'],
  ['waitress', '웨이트리스', 'jobs', 2, 'noun'],
  ['bartender', '바텐더', 'jobs', 3, 'noun'],
  ['receptionist', '접수원', 'jobs', 3, 'noun'],
  ['secretary', '비서', 'jobs', 3, 'noun'],
  ['accountant', '회계사', 'jobs', 3, 'noun'],
  ['banker', '은행원', 'jobs', 2, 'noun'],
  ['investor', '투자가', 'jobs', 3, 'noun'],
  ['manager', '매니저', 'jobs', 2, 'noun'],
  ['director', '감독', 'jobs', 2, 'noun'],
  ['producer', '프로듀서', 'jobs', 3, 'noun'],
  ['journalist', '기자', 'jobs', 3, 'noun'],
  ['editor', '편집자', 'jobs', 2, 'noun'],
  ['translator', '번역가', 'jobs', 3, 'noun'],
  ['interpreter', '통역사', 'jobs', 3, 'noun'],
  ['librarian', '사서', 'jobs', 3, 'noun'],
  ['professor', '교수', 'jobs', 3, 'noun'],
  ['tutor', '과외 선생', 'jobs', 2, 'noun'],
  ['principal', '교장', 'jobs', 3, 'noun'],
  ['coach', '코치', 'jobs', 2, 'noun'],
  ['referee', '심판', 'jobs', 2, 'noun'],
  ['lifeguard', '인명구조원', 'jobs', 3, 'noun'],
  ['detective', '탐정', 'jobs', 3, 'noun'],
  ['guard', '경비원', 'jobs', 2, 'noun'],
  ['spy', '스파이', 'jobs', 2, 'noun'],
  ['photographer', '사진작가', 'jobs', 3, 'noun'],
  ['designer', '디자이너', 'jobs', 2, 'noun'],
  ['architect', '건축가', 'jobs', 3, 'noun'],
  ['programmer', '프로그래머', 'jobs', 3, 'noun'],
  ['inventor', '발명가', 'jobs', 3, 'noun'],
  ['explorer', '탐험가', 'jobs', 3, 'noun'],
  ['captain', '선장', 'jobs', 2, 'noun'],
  ['general', '장군', 'jobs', 2, 'noun'],
  ['mayor', '시장(직위)', 'jobs', 2, 'noun'],
  ['governor', '주지사', 'jobs', 3, 'noun'],

  // ── sports (extras) ──
  ['soccer', '축구', 'sports', 2, 'noun'],
  ['baseball', '야구', 'sports', 2, 'noun'],
  ['basketball', '농구', 'sports', 2, 'noun'],
  ['tennis', '테니스', 'sports', 2, 'noun'],
  ['swimming', '수영', 'sports', 2, 'noun'],
  ['running', '달리기', 'sports', 2, 'noun'],
  ['skiing', '스키', 'sports', 2, 'noun'],
  ['skating', '스케이팅', 'sports', 2, 'noun'],
  ['golf', '골프', 'sports', 2, 'noun'],
  ['boxing', '권투', 'sports', 2, 'noun'],
  ['volleyball', '배구', 'sports', 2, 'noun'],
  ['badminton', '배드민턴', 'sports', 2, 'noun'],
  ['table tennis', '탁구', 'sports', 2, 'noun'],
  ['hockey', '하키', 'sports', 2, 'noun'],
  ['cycling', '자전거 타기', 'sports', 2, 'noun'],
  ['surfing', '서핑', 'sports', 2, 'noun'],
  ['climbing', '등반', 'sports', 2, 'noun'],
  ['fishing', '낚시', 'sports', 2, 'noun'],
  ['camping', '캠핑', 'sports', 2, 'noun'],
  ['hiking', '하이킹', 'sports', 2, 'noun'],
  ['yoga', '요가', 'sports', 2, 'noun'],
  ['karate', '가라테', 'sports', 2, 'noun'],
  ['judo', '유도', 'sports', 2, 'noun'],
  ['taekwondo', '태권도', 'sports', 2, 'noun'],
  ['wrestling', '레슬링', 'sports', 2, 'noun'],
  ['fencing', '펜싱', 'sports', 2, 'noun'],
  ['archery', '양궁', 'sports', 2, 'noun'],
  ['gymnastics', '체조', 'sports', 3, 'noun'],
  ['track', '육상', 'sports', 2, 'noun'],
  ['marathon', '마라톤', 'sports', 3, 'noun'],
  ['relay', '릴레이', 'sports', 2, 'noun'],
  ['sprint', '단거리 달리기', 'sports', 2, 'noun'],
  ['hurdle', '허들', 'sports', 2, 'noun'],
  ['pole vault', '장대높이뛰기', 'sports', 3, 'noun'],
  ['long jump', '멀리뛰기', 'sports', 2, 'noun'],
  ['high jump', '높이뛰기', 'sports', 2, 'noun'],
  ['shot put', '포환던지기', 'sports', 3, 'noun'],
  ['javelin', '창던지기', 'sports', 3, 'noun'],
  ['ball', '공', 'sports', 2, 'noun'],
  ['goal', '골', 'sports', 2, 'noun'],
  ['team', '팀', 'sports', 2, 'noun'],
  ['match', '경기', 'sports', 2, 'noun'],
  ['race', '경주', 'sports', 2, 'noun'],
  ['score', '점수', 'sports', 2, 'noun'],
  ['win', '이기다', 'sports', 2, 'verb'],
  ['lose', '지다', 'sports', 2, 'verb'],
  ['practice', '연습', 'sports', 2, 'noun'],
  ['champion', '챔피언', 'sports', 2, 'noun'],
  ['medal', '메달', 'sports', 2, 'noun'],
  ['trophy', '트로피', 'sports', 2, 'noun'],
  ['stadium', '경기장', 'sports', 3, 'noun'],
  ['court', '코트', 'sports', 2, 'noun'],
  ['field', '필드', 'sports', 2, 'noun'],
  ['pool', '수영장', 'sports', 2, 'noun'],
  ['rink', '링크', 'sports', 2, 'noun'],
  ['net', '네트', 'sports', 2, 'noun'],
  ['racket', '라켓', 'sports', 2, 'noun'],
  ['bat', '배트', 'sports', 2, 'noun'],
  ['glove', '글러브', 'sports', 2, 'noun'],
  ['helmet', '헬멧', 'sports', 2, 'noun'],
  ['uniform', '유니폼', 'sports', 2, 'noun'],
  ['whistle', '호루라기', 'sports', 2, 'noun'],
  ['pass', '패스', 'sports', 2, 'noun'],
  ['shoot', '슛', 'sports', 2, 'verb'],
  ['dribble', '드리블', 'sports', 2, 'verb'],
  ['tackle', '태클', 'sports', 2, 'verb'],
  ['serve', '서브', 'sports', 2, 'verb'],
  ['block', '블록', 'sports', 2, 'verb'],
  ['foul', '파울', 'sports', 2, 'noun'],
  ['penalty', '벌칙', 'sports', 3, 'noun'],
  ['timeout', '타임아웃', 'sports', 2, 'noun'],
  ['halftime', '하프타임', 'sports', 2, 'noun'],
  ['overtime', '연장전', 'sports', 3, 'noun'],
  ['playoffs', '플레이오프', 'sports', 3, 'noun'],
  ['tournament', '토너먼트', 'sports', 3, 'noun'],
  ['league', '리그', 'sports', 2, 'noun'],
  ['Olympics', '올림픽', 'sports', 3, 'noun'],
  ['World Cup', '월드컵', 'sports', 2, 'noun'],

  // ── emotions (extras) ──
  ['delighted', '기뻐하는', 'emotions', 3, 'adjective'],
  ['thrilled', '흥분한', 'emotions', 3, 'adjective'],
  ['content', '만족하는', 'emotions', 3, 'adjective'],
  ['satisfied', '만족한', 'emotions', 3, 'adjective'],
  ['relieved', '안심한', 'emotions', 3, 'adjective'],
  ['amused', '즐거운', 'emotions', 3, 'adjective'],
  ['amazed', '놀란', 'emotions', 2, 'adjective'],
  ['impressed', '감명받은', 'emotions', 3, 'adjective'],
  ['inspired', '영감 받은', 'emotions', 3, 'adjective'],
  ['motivated', '동기부여된', 'emotions', 3, 'adjective'],
  ['determined', '결심한', 'emotions', 3, 'adjective'],
  ['focused', '집중한', 'emotions', 2, 'adjective'],
  ['energetic', '활기찬', 'emotions', 3, 'adjective'],
  ['enthusiastic', '열정적인', 'emotions', 3, 'adjective'],
  ['passionate', '열정적인', 'emotions', 3, 'adjective'],
  ['optimistic', '낙관적인', 'emotions', 3, 'adjective'],
  ['pessimistic', '비관적인', 'emotions', 3, 'adjective'],
  ['anxious', '불안한', 'emotions', 3, 'adjective'],
  ['frustrated', '좌절한', 'emotions', 3, 'adjective'],
  ['irritated', '짜증난', 'emotions', 3, 'adjective'],
  ['annoyed', '화난', 'emotions', 3, 'adjective'],
  ['furious', '격노한', 'emotions', 3, 'adjective'],
  ['miserable', '비참한', 'emotions', 3, 'adjective'],
  ['depressed', '우울한', 'emotions', 3, 'adjective'],
  ['heartbroken', '상심한', 'emotions', 3, 'adjective'],
  ['homesick', '향수병에 걸린', 'emotions', 3, 'adjective'],
  ['ashamed', '부끄러운', 'emotions', 3, 'adjective'],
  ['embarrassed', '당황한', 'emotions', 3, 'adjective'],
  ['guilty', '죄책감 드는', 'emotions', 3, 'adjective'],
  ['regretful', '후회하는', 'emotions', 3, 'adjective'],
  ['nostalgic', '향수를 느끼는', 'emotions', 3, 'adjective'],
  ['suspicious', '의심스러운', 'emotions', 3, 'adjective'],
  ['doubtful', '의심하는', 'emotions', 3, 'adjective'],
  ['hesitant', '주저하는', 'emotions', 3, 'adjective'],
  ['reluctant', '꺼리는', 'emotions', 3, 'adjective'],
  ['desperate', '절망적인', 'emotions', 3, 'adjective'],
  ['helpless', '무력한', 'emotions', 3, 'adjective'],
  ['overwhelmed', '압도된', 'emotions', 3, 'adjective'],
  ['stressed', '스트레스 받은', 'emotions', 3, 'adjective'],
  ['exhausted', '지친', 'emotions', 3, 'adjective'],
  ['restless', '안절부절하는', 'emotions', 3, 'adjective'],
  ['baffled', '어리둥절한', 'emotions', 3, 'adjective'],
  ['puzzled', '어리둥절한', 'emotions', 3, 'adjective'],
  ['astonished', '깜짝 놀란', 'emotions', 3, 'adjective'],
  ['stunned', '멍해진', 'emotions', 3, 'adjective'],
  ['terrified', '겁에 질린', 'emotions', 3, 'adjective'],
  ['horrified', '공포에 질린', 'emotions', 3, 'adjective'],
  ['panicked', '공황 상태의', 'emotions', 3, 'adjective'],
  ['envious', '부러워하는', 'emotions', 3, 'adjective'],
  ['resentful', '원망하는', 'emotions', 3, 'adjective'],
  ['sympathetic', '동정하는', 'emotions', 3, 'adjective'],

  // ── house / rooms (extras) ──
  ['apartment', '아파트', 'house', 2, 'noun'],
  ['cottage', '오두막', 'house', 2, 'noun'],
  ['mansion', '대저택', 'house', 3, 'noun'],
  ['cabin', '통나무집', 'house', 2, 'noun'],
  ['tent', '텐트', 'house', 2, 'noun'],
  ['igloo', '이글루', 'house', 2, 'noun'],
  ['hut', '오두막', 'house', 2, 'noun'],
  ['studio', '스튜디오', 'house', 2, 'noun'],
  ['patio', '테라스', 'house', 3, 'noun'],
  ['deck', '데크', 'house', 2, 'noun'],
  ['lobby', '로비', 'house', 2, 'noun'],
  ['hallway', '복도', 'house', 2, 'noun'],
  ['pantry', '식료품 저장실', 'house', 3, 'noun'],
  ['laundry room', '세탁실', 'house', 2, 'noun'],
  ['dining room', '식당', 'house', 2, 'noun'],
  ['study', '서재', 'house', 2, 'noun'],
  ['nursery', '아기방', 'house', 3, 'noun'],
  ['den', '서재', 'house', 2, 'noun'],
  ['cellar', '지하 저장실', 'house', 3, 'noun'],
  ['loft', '다락', 'house', 2, 'noun'],
  ['furniture', '가구', 'house', 3, 'noun'],
  ['bookshelf', '책꽂이', 'house', 2, 'noun'],
  ['wardrobe', '옷장', 'house', 3, 'noun'],
  ['nightstand', '침대 옆 탁자', 'house', 3, 'noun'],
  ['rocking chair', '흔들의자', 'house', 2, 'noun'],
  ['stool', '의자(등받이 없는)', 'house', 2, 'noun'],
  ['bench', '벤치', 'house', 2, 'noun'],
  ['couch', '소파', 'house', 2, 'noun'],
  ['rug', '깔개', 'house', 2, 'noun'],
  ['wallpaper', '벽지', 'house', 3, 'noun'],
  ['chandelier', '샹들리에', 'house', 3, 'noun'],
  ['vase', '꽃병', 'house', 2, 'noun'],
  ['candle', '양초', 'house', 2, 'noun'],
  ['frame', '액자', 'house', 2, 'noun'],
  ['clock', '시계', 'house', 2, 'noun'],
  ['thermostat', '온도조절기', 'house', 3, 'noun'],
  ['doorbell', '초인종', 'house', 2, 'noun'],
  ['doorknob', '문손잡이', 'house', 2, 'noun'],
  ['hinge', '경첩', 'house', 3, 'noun'],
  ['faucet', '수도꼭지', 'house', 3, 'noun'],

  // ── technology ──
  ['computer', '컴퓨터', 'technology', 2, 'noun'],
  ['laptop', '노트북', 'technology', 2, 'noun'],
  ['tablet', '태블릿', 'technology', 2, 'noun'],
  ['smartphone', '스마트폰', 'technology', 2, 'noun'],
  ['keyboard', '키보드', 'technology', 2, 'noun'],
  ['mouse', '마우스', 'technology', 2, 'noun'],
  ['monitor', '모니터', 'technology', 2, 'noun'],
  ['screen', '화면', 'technology', 2, 'noun'],
  ['printer', '프린터', 'technology', 2, 'noun'],
  ['scanner', '스캐너', 'technology', 2, 'noun'],
  ['speaker', '스피커', 'technology', 2, 'noun'],
  ['headphones', '헤드폰', 'technology', 2, 'noun'],
  ['microphone', '마이크', 'technology', 2, 'noun'],
  ['camera', '카메라', 'technology', 2, 'noun'],
  ['battery', '배터리', 'technology', 2, 'noun'],
  ['charger', '충전기', 'technology', 2, 'noun'],
  ['cable', '케이블', 'technology', 2, 'noun'],
  ['plug', '플러그', 'technology', 2, 'noun'],
  ['outlet', '콘센트', 'technology', 2, 'noun'],
  ['switch', '스위치', 'technology', 2, 'noun'],
  ['button', '버튼', 'technology', 2, 'noun'],
  ['remote control', '리모컨', 'technology', 2, 'noun'],
  ['Wi-Fi', '와이파이', 'technology', 2, 'noun'],
  ['internet', '인터넷', 'technology', 2, 'noun'],
  ['email', '이메일', 'technology', 2, 'noun'],
  ['website', '웹사이트', 'technology', 2, 'noun'],
  ['app', '앱', 'technology', 2, 'noun'],
  ['download', '다운로드', 'technology', 2, 'noun'],
  ['upload', '업로드', 'technology', 2, 'noun'],
  ['password', '비밀번호', 'technology', 2, 'noun'],
  ['username', '사용자이름', 'technology', 2, 'noun'],
  ['file', '파일', 'technology', 2, 'noun'],
  ['folder', '폴더', 'technology', 2, 'noun'],
  ['data', '데이터', 'technology', 2, 'noun'],
  ['memory', '메모리', 'technology', 2, 'noun'],
  ['storage', '저장소', 'technology', 2, 'noun'],
  ['software', '소프트웨어', 'technology', 3, 'noun'],
  ['hardware', '하드웨어', 'technology', 3, 'noun'],
  ['program', '프로그램', 'technology', 2, 'noun'],
  ['code', '코드', 'technology', 2, 'noun'],
  ['bug', '버그', 'technology', 2, 'noun'],
  ['update', '업데이트', 'technology', 2, 'noun'],
  ['install', '설치하다', 'technology', 2, 'verb'],
  ['search', '검색하다', 'technology', 2, 'verb'],
  ['click', '클릭하다', 'technology', 2, 'verb'],
  ['type', '입력하다', 'technology', 2, 'verb'],
  ['scroll', '스크롤하다', 'technology', 2, 'verb'],
  ['save', '저장하다', 'technology', 2, 'verb'],
  ['delete', '삭제하다', 'technology', 2, 'verb'],
  ['copy', '복사하다', 'technology', 2, 'verb'],
  ['paste', '붙여넣기', 'technology', 2, 'verb'],
  ['print', '인쇄하다', 'technology', 2, 'verb'],
  ['charge', '충전하다', 'technology', 2, 'verb'],
  ['connect', '연결하다', 'technology', 2, 'verb'],
  ['disconnect', '연결 끊다', 'technology', 3, 'verb'],
  ['restart', '재시작하다', 'technology', 2, 'verb'],
  ['shut down', '종료하다', 'technology', 2, 'verb'],

  // ── time expressions (extras) ──
  ['century', '세기', 'time', 3, 'noun'],
  ['decade', '10년', 'time', 3, 'noun'],
  ['era', '시대', 'time', 3, 'noun'],
  ['period', '기간', 'time', 2, 'noun'],
  ['moment', '순간', 'time', 2, 'noun'],
  ['instant', '순간', 'time', 3, 'noun'],
  ['daily', '매일의', 'time', 2, 'adjective'],
  ['weekly', '매주의', 'time', 2, 'adjective'],
  ['monthly', '매달의', 'time', 2, 'adjective'],
  ['yearly', '매년의', 'time', 2, 'adjective'],
  ['annual', '연례의', 'time', 3, 'adjective'],
  ['ancient', '고대의', 'time', 3, 'adjective'],
  ['modern', '현대의', 'time', 2, 'adjective'],
  ['recent', '최근의', 'time', 2, 'adjective'],
  ['current', '현재의', 'time', 2, 'adjective'],
  ['previous', '이전의', 'time', 3, 'adjective'],
  ['next', '다음의', 'time', 2, 'adjective'],
  ['permanent', '영구적인', 'time', 3, 'adjective'],
  ['temporary', '일시적인', 'time', 3, 'adjective'],
  ['schedule', '일정', 'time', 2, 'noun'],
  ['deadline', '마감일', 'time', 3, 'noun'],
  ['appointment', '약속', 'time', 3, 'noun'],
  ['routine', '일과', 'time', 3, 'noun'],
  ['habit', '습관', 'time', 2, 'noun'],
  ['tradition', '전통', 'time', 3, 'noun'],

  // ── geography ──
  ['continent', '대륙', 'geography', 3, 'noun'],
  ['country', '나라', 'geography', 2, 'noun'],
  ['state', '주(州)', 'geography', 2, 'noun'],
  ['city', '도시', 'geography', 2, 'noun'],
  ['town', '마을', 'geography', 2, 'noun'],
  ['village', '시골 마을', 'geography', 2, 'noun'],
  ['capital', '수도', 'geography', 2, 'noun'],
  ['border', '국경', 'geography', 3, 'noun'],
  ['region', '지역', 'geography', 3, 'noun'],
  ['zone', '구역', 'geography', 2, 'noun'],
  ['territory', '영토', 'geography', 3, 'noun'],
  ['peninsula', '반도', 'geography', 3, 'noun'],
  ['archipelago', '군도', 'geography', 3, 'noun'],
  ['equator', '적도', 'geography', 3, 'noun'],
  ['hemisphere', '반구', 'geography', 3, 'noun'],
  ['latitude', '위도', 'geography', 3, 'noun'],
  ['longitude', '경도', 'geography', 3, 'noun'],
  ['altitude', '고도', 'geography', 3, 'noun'],
  ['terrain', '지형', 'geography', 3, 'noun'],
  ['plain', '평야', 'geography', 2, 'noun'],
  ['prairie', '대초원', 'geography', 3, 'noun'],
  ['plateau', '고원', 'geography', 3, 'noun'],
  ['canyon', '협곡', 'geography', 3, 'noun'],
  ['gorge', '깊은 골짜기', 'geography', 3, 'noun'],
  ['basin', '분지', 'geography', 3, 'noun'],
  ['delta', '삼각주', 'geography', 3, 'noun'],
  ['oasis', '오아시스', 'geography', 3, 'noun'],
  ['savanna', '사바나', 'geography', 3, 'noun'],
  ['tundra', '툰드라', 'geography', 3, 'noun'],
  ['marsh', '습지', 'geography', 3, 'noun'],
  ['swamp', '늪', 'geography', 3, 'noun'],
  ['bay', '만', 'geography', 2, 'noun'],
  ['gulf', '걸프', 'geography', 3, 'noun'],
  ['strait', '해협', 'geography', 3, 'noun'],
  ['channel', '수로', 'geography', 3, 'noun'],
  ['harbor', '항구', 'geography', 2, 'noun'],
  ['coast', '해안', 'geography', 2, 'noun'],
  ['beach', '해변', 'geography', 2, 'noun'],
  ['reef', '암초', 'geography', 3, 'noun'],
  ['glacier', '빙하', 'geography', 3, 'noun'],
  ['iceberg', '빙산', 'geography', 3, 'noun'],

  // ── social / community ──
  ['community', '공동체', 'social', 3, 'noun'],
  ['society', '사회', 'social', 3, 'noun'],
  ['culture', '문화', 'social', 2, 'noun'],
  ['tradition', '전통', 'social', 3, 'noun'],
  ['custom', '관습', 'social', 3, 'noun'],
  ['ceremony', '의식', 'social', 3, 'noun'],
  ['celebration', '축하', 'social', 3, 'noun'],
  ['festival', '축제', 'social', 2, 'noun'],
  ['holiday', '공휴일', 'social', 2, 'noun'],
  ['vacation', '방학', 'social', 2, 'noun'],
  ['party', '파티', 'social', 2, 'noun'],
  ['gathering', '모임', 'social', 3, 'noun'],
  ['meeting', '회의', 'social', 2, 'noun'],
  ['conference', '학회', 'social', 3, 'noun'],
  ['event', '행사', 'social', 2, 'noun'],
  ['concert', '콘서트', 'social', 2, 'noun'],
  ['show', '공연', 'social', 2, 'noun'],
  ['exhibition', '전시회', 'social', 3, 'noun'],
  ['parade', '퍼레이드', 'social', 2, 'noun'],
  ['protest', '시위', 'social', 3, 'noun'],
  ['volunteer', '자원봉사자', 'social', 3, 'noun'],
  ['charity', '자선', 'social', 3, 'noun'],
  ['donation', '기부', 'social', 3, 'noun'],
  ['organization', '단체', 'social', 3, 'noun'],
  ['club', '동아리', 'social', 2, 'noun'],
  ['group', '그룹', 'social', 2, 'noun'],
  ['member', '회원', 'social', 2, 'noun'],
  ['leader', '리더', 'social', 2, 'noun'],
  ['follower', '추종자', 'social', 3, 'noun'],
  ['citizen', '시민', 'social', 3, 'noun'],
  ['resident', '주민', 'social', 3, 'noun'],
  ['immigrant', '이민자', 'social', 3, 'noun'],
  ['refugee', '난민', 'social', 3, 'noun'],
  ['population', '인구', 'social', 3, 'noun'],
  ['generation', '세대', 'social', 3, 'noun'],
  ['heritage', '유산', 'social', 3, 'noun'],
  ['language', '언어', 'social', 2, 'noun'],
  ['religion', '종교', 'social', 3, 'noun'],
  ['race', '인종', 'social', 3, 'noun'],
  ['gender', '성별', 'social', 3, 'noun'],

  // ── health / medicine ──
  ['health', '건강', 'health', 2, 'noun'],
  ['illness', '질병', 'health', 3, 'noun'],
  ['disease', '질환', 'health', 3, 'noun'],
  ['infection', '감염', 'health', 3, 'noun'],
  ['fever', '열', 'health', 2, 'noun'],
  ['cold', '감기', 'health', 2, 'noun'],
  ['flu', '독감', 'health', 2, 'noun'],
  ['allergy', '알레르기', 'health', 3, 'noun'],
  ['headache', '두통', 'health', 2, 'noun'],
  ['stomachache', '복통', 'health', 2, 'noun'],
  ['toothache', '치통', 'health', 2, 'noun'],
  ['backache', '요통', 'health', 2, 'noun'],
  ['sore throat', '인후통', 'health', 2, 'noun'],
  ['cough', '기침', 'health', 2, 'noun'],
  ['sneeze', '재채기', 'health', 2, 'noun'],
  ['rash', '발진', 'health', 3, 'noun'],
  ['bruise', '멍', 'health', 2, 'noun'],
  ['wound', '상처', 'health', 2, 'noun'],
  ['scar', '흉터', 'health', 3, 'noun'],
  ['bandage', '붕대', 'health', 2, 'noun'],
  ['cast', '깁스', 'health', 3, 'noun'],
  ['crutch', '목발', 'health', 3, 'noun'],
  ['wheelchair', '휠체어', 'health', 3, 'noun'],
  ['medicine', '약', 'health', 2, 'noun'],
  ['pill', '알약', 'health', 2, 'noun'],
  ['syrup', '시럽약', 'health', 2, 'noun'],
  ['injection', '주사', 'health', 3, 'noun'],
  ['vaccine', '백신', 'health', 3, 'noun'],
  ['surgery', '수술', 'health', 3, 'noun'],
  ['checkup', '건강검진', 'health', 2, 'noun'],
  ['diet', '식단', 'health', 2, 'noun'],
  ['exercise', '운동', 'health', 2, 'noun'],
  ['rest', '휴식', 'health', 2, 'noun'],
  ['sleep', '수면', 'health', 2, 'noun'],
  ['nutrition', '영양', 'health', 3, 'noun'],
  ['vitamin', '비타민', 'health', 2, 'noun'],
  ['protein', '단백질', 'health', 3, 'noun'],
  ['calorie', '칼로리', 'health', 3, 'noun'],
  ['hygiene', '위생', 'health', 3, 'noun'],
  ['germ', '세균', 'health', 2, 'noun'],
  ['bacteria', '박테리아', 'health', 3, 'noun'],
  ['virus', '바이러스', 'health', 3, 'noun'],
  ['symptom', '증상', 'health', 3, 'noun'],
  ['treatment', '치료', 'health', 3, 'noun'],
  ['recovery', '회복', 'health', 3, 'noun'],
  ['prescription', '처방전', 'health', 3, 'noun'],
  ['ambulance', '구급차', 'health', 3, 'noun'],
  ['emergency', '응급', 'health', 3, 'noun'],
  ['hospital', '병원', 'health', 2, 'noun'],
  ['clinic', '의원', 'health', 2, 'noun'],

  // ── science basics ──
  ['experiment', '실험', 'science', 3, 'noun'],
  ['hypothesis', '가설', 'science', 3, 'noun'],
  ['theory', '이론', 'science', 3, 'noun'],
  ['research', '연구', 'science', 3, 'noun'],
  ['discovery', '발견', 'science', 3, 'noun'],
  ['observation', '관찰', 'science', 3, 'noun'],
  ['evidence', '증거', 'science', 3, 'noun'],
  ['conclusion', '결론', 'science', 3, 'noun'],
  ['result', '결과', 'science', 2, 'noun'],
  ['method', '방법', 'science', 3, 'noun'],
  ['process', '과정', 'science', 3, 'noun'],
  ['sample', '표본', 'science', 3, 'noun'],
  ['measurement', '측정', 'science', 3, 'noun'],
  ['temperature', '온도', 'science', 2, 'noun'],
  ['volume', '부피', 'science', 3, 'noun'],
  ['weight', '무게', 'science', 2, 'noun'],
  ['length', '길이', 'science', 2, 'noun'],
  ['width', '너비', 'science', 2, 'noun'],
  ['height', '높이', 'science', 2, 'noun'],
  ['depth', '깊이', 'science', 2, 'noun'],
  ['speed', '속력', 'science', 2, 'noun'],
  ['force', '힘', 'science', 2, 'noun'],
  ['energy', '에너지', 'science', 2, 'noun'],
  ['power', '동력', 'science', 2, 'noun'],
  ['heat', '열', 'science', 2, 'noun'],
  ['light', '빛', 'science', 2, 'noun'],
  ['sound', '소리', 'science', 2, 'noun'],
  ['wave', '파동', 'science', 3, 'noun'],
  ['frequency', '주파수', 'science', 3, 'noun'],
  ['vibration', '진동', 'science', 3, 'noun'],
  ['magnet', '자석', 'science', 2, 'noun'],
  ['gravity', '중력', 'science', 3, 'noun'],
  ['friction', '마찰', 'science', 3, 'noun'],
  ['pressure', '압력', 'science', 3, 'noun'],
  ['density', '밀도', 'science', 3, 'noun'],
  ['matter', '물질', 'science', 3, 'noun'],
  ['solid', '고체', 'science', 2, 'noun'],
  ['liquid', '액체', 'science', 2, 'noun'],
  ['gas', '기체', 'science', 2, 'noun'],
  ['vapor', '증기', 'science', 3, 'noun'],
  ['solution', '용액', 'science', 3, 'noun'],
  ['mixture', '혼합물', 'science', 3, 'noun'],
  ['element', '원소', 'science', 3, 'noun'],
  ['compound', '화합물', 'science', 3, 'noun'],
  ['reaction', '반응', 'science', 3, 'noun'],
  ['acid', '산', 'science', 3, 'noun'],
  ['base', '염기', 'science', 3, 'noun'],
  ['crystal', '결정', 'science', 3, 'noun'],
  ['mineral', '광물', 'science', 3, 'noun'],
  ['fossil', '화석', 'science', 3, 'noun'],

  // ── nature / ecology ──
  ['habitat', '서식지', 'ecology', 3, 'noun'],
  ['ecosystem', '생태계', 'ecology', 3, 'noun'],
  ['food chain', '먹이사슬', 'ecology', 3, 'noun'],
  ['predator', '포식자', 'ecology', 3, 'noun'],
  ['prey', '먹이', 'ecology', 3, 'noun'],
  ['herbivore', '초식동물', 'ecology', 3, 'noun'],
  ['carnivore', '육식동물', 'ecology', 3, 'noun'],
  ['omnivore', '잡식동물', 'ecology', 3, 'noun'],
  ['mammal', '포유류', 'ecology', 3, 'noun'],
  ['reptile', '파충류', 'ecology', 3, 'noun'],
  ['amphibian', '양서류', 'ecology', 3, 'noun'],
  ['insect', '곤충', 'ecology', 2, 'noun'],
  ['arachnid', '거미류', 'ecology', 3, 'noun'],
  ['crustacean', '갑각류', 'ecology', 3, 'noun'],
  ['mollusk', '연체동물', 'ecology', 3, 'noun'],
  ['vertebrate', '척추동물', 'ecology', 3, 'noun'],
  ['invertebrate', '무척추동물', 'ecology', 3, 'noun'],
  ['migration', '이동', 'ecology', 3, 'noun'],
  ['hibernation', '겨울잠', 'ecology', 3, 'noun'],
  ['camouflage', '위장', 'ecology', 3, 'noun'],
  ['adaptation', '적응', 'ecology', 3, 'noun'],
  ['evolution', '진화', 'ecology', 3, 'noun'],
  ['species', '종', 'ecology', 3, 'noun'],
  ['population', '개체수', 'ecology', 3, 'noun'],
  ['biodiversity', '생물다양성', 'ecology', 3, 'noun'],
  ['conservation', '보존', 'ecology', 3, 'noun'],
  ['pollution', '오염', 'ecology', 3, 'noun'],
  ['deforestation', '삼림 벌채', 'ecology', 3, 'noun'],
  ['extinction', '멸종', 'ecology', 3, 'noun'],
  ['recycling', '재활용', 'ecology', 3, 'noun'],

  // ── arts and hobbies ──
  ['painting', '그림', 'hobbies', 2, 'noun'],
  ['drawing', '드로잉', 'hobbies', 2, 'noun'],
  ['sculpture', '조각', 'hobbies', 3, 'noun'],
  ['pottery', '도자기', 'hobbies', 3, 'noun'],
  ['photography', '사진', 'hobbies', 3, 'noun'],
  ['calligraphy', '서예', 'hobbies', 3, 'noun'],
  ['origami', '종이접기', 'hobbies', 2, 'noun'],
  ['knitting', '뜨개질', 'hobbies', 2, 'noun'],
  ['sewing', '바느질', 'hobbies', 2, 'noun'],
  ['gardening', '정원 가꾸기', 'hobbies', 2, 'noun'],
  ['cooking', '요리', 'hobbies', 2, 'noun'],
  ['baking', '베이킹', 'hobbies', 2, 'noun'],
  ['reading', '독서', 'hobbies', 2, 'noun'],
  ['writing', '글쓰기', 'hobbies', 2, 'noun'],
  ['singing', '노래', 'hobbies', 2, 'noun'],
  ['dancing', '춤', 'hobbies', 2, 'noun'],
  ['acting', '연기', 'hobbies', 2, 'noun'],
  ['magic', '마술', 'hobbies', 2, 'noun'],
  ['juggling', '저글링', 'hobbies', 3, 'noun'],
  ['puzzle', '퍼즐', 'hobbies', 2, 'noun'],
  ['chess', '체스', 'hobbies', 2, 'noun'],
  ['collecting', '수집', 'hobbies', 2, 'noun'],
  ['stamp', '우표', 'hobbies', 2, 'noun'],
  ['coin', '동전', 'hobbies', 2, 'noun'],
  ['model', '모형', 'hobbies', 2, 'noun'],
  ['craft', '공예', 'hobbies', 2, 'noun'],
  ['DIY', '직접 만들기', 'hobbies', 2, 'noun'],
  ['comic', '만화', 'hobbies', 2, 'noun'],
  ['cartoon', '만화', 'hobbies', 2, 'noun'],
  ['animation', '애니메이션', 'hobbies', 3, 'noun'],

  // ── weather & seasons (grade 4 level) ──
  ['climate', '기후', 'weather', 3, 'noun'],
  ['atmosphere', '대기', 'weather', 3, 'noun'],
  ['humidity', '습도', 'weather', 3, 'noun'],
  ['precipitation', '강수량', 'weather', 3, 'noun'],
  ['barometer', '기압계', 'weather', 3, 'noun'],
  ['meteorology', '기상학', 'weather', 3, 'noun'],
  ['monsoon', '장마', 'weather', 3, 'noun'],
  ['cyclone', '사이클론', 'weather', 3, 'noun'],
  ['front', '전선', 'weather', 3, 'noun'],
  ['visibility', '가시거리', 'weather', 3, 'noun'],
  ['dew point', '이슬점', 'weather', 3, 'noun'],
  ['wind chill', '체감온도', 'weather', 3, 'noun'],
  ['heat wave', '폭염', 'weather', 3, 'noun'],
  ['cold snap', '한파', 'weather', 3, 'noun'],
  ['overcast', '흐린', 'weather', 3, 'adjective'],
  ['partly cloudy', '구름 조금', 'weather', 2, 'adjective'],
  ['clear', '맑은', 'weather', 2, 'adjective'],
  ['mild', '온화한', 'weather', 2, 'adjective'],
  ['severe', '심한', 'weather', 3, 'adjective'],
  ['extreme', '극한의', 'weather', 3, 'adjective'],

  // ── math & numbers (grade 4) ──
  ['addition', '덧셈', 'math', 2, 'noun'],
  ['subtraction', '뺄셈', 'math', 2, 'noun'],
  ['multiplication', '곱셈', 'math', 3, 'noun'],
  ['division', '나눗셈', 'math', 3, 'noun'],
  ['fraction', '분수', 'math', 3, 'noun'],
  ['decimal', '소수', 'math', 3, 'noun'],
  ['percent', '백분율', 'math', 2, 'noun'],
  ['average', '평균', 'math', 2, 'noun'],
  ['sum', '합', 'math', 2, 'noun'],
  ['difference', '차이', 'math', 2, 'noun'],
  ['product', '곱', 'math', 2, 'noun'],
  ['quotient', '몫', 'math', 3, 'noun'],
  ['remainder', '나머지', 'math', 3, 'noun'],
  ['even number', '짝수', 'math', 2, 'noun'],
  ['odd number', '홀수', 'math', 2, 'noun'],
  ['digit', '숫자', 'math', 2, 'noun'],
  ['place value', '자릿값', 'math', 3, 'noun'],
  ['rounding', '반올림', 'math', 3, 'noun'],
  ['estimation', '어림', 'math', 3, 'noun'],
  ['equation', '등식', 'math', 3, 'noun'],

  // ── buildings & structures ──
  ['skyscraper', '고층건물', 'buildings', 3, 'noun'],
  ['tower', '탑', 'buildings', 2, 'noun'],
  ['lighthouse', '등대', 'buildings', 2, 'noun'],
  ['windmill', '풍차', 'buildings', 2, 'noun'],
  ['dam', '댐', 'buildings', 2, 'noun'],
  ['monument', '기념비', 'buildings', 3, 'noun'],
  ['statue', '동상', 'buildings', 2, 'noun'],
  ['fountain', '분수대', 'buildings', 2, 'noun'],
  ['arch', '아치', 'buildings', 2, 'noun'],
  ['dome', '돔', 'buildings', 2, 'noun'],
  ['pillar', '기둥', 'buildings', 3, 'noun'],
  ['column', '열주', 'buildings', 3, 'noun'],
  ['pyramid', '피라미드', 'buildings', 2, 'noun'],
  ['cathedral', '대성당', 'buildings', 3, 'noun'],
  ['mosque', '모스크', 'buildings', 3, 'noun'],
  ['synagogue', '유대교 교당', 'buildings', 3, 'noun'],
  ['shrine', '신전', 'buildings', 3, 'noun'],
  ['fortress', '요새', 'buildings', 3, 'noun'],
  ['ruins', '폐허', 'buildings', 3, 'noun'],
  ['barn', '헛간', 'buildings', 2, 'noun'],
  ['warehouse', '창고', 'buildings', 3, 'noun'],
  ['greenhouse', '온실', 'buildings', 2, 'noun'],
  ['observatory', '천문대', 'buildings', 3, 'noun'],
  ['aquarium', '수족관', 'buildings', 2, 'noun'],
  ['planetarium', '천문관', 'buildings', 3, 'noun'],

  // ── tools ──
  ['hammer', '망치', 'tools', 2, 'noun'],
  ['screwdriver', '드라이버', 'tools', 2, 'noun'],
  ['wrench', '렌치', 'tools', 2, 'noun'],
  ['pliers', '펜치', 'tools', 2, 'noun'],
  ['saw', '톱', 'tools', 2, 'noun'],
  ['drill', '드릴', 'tools', 2, 'noun'],
  ['nail', '못', 'tools', 2, 'noun'],
  ['screw', '나사', 'tools', 2, 'noun'],
  ['bolt', '볼트', 'tools', 2, 'noun'],
  ['nut', '너트', 'tools', 2, 'noun'],
  ['level', '수평계', 'tools', 2, 'noun'],
  ['tape measure', '줄자', 'tools', 2, 'noun'],
  ['ladder', '사다리', 'tools', 2, 'noun'],
  ['wheelbarrow', '외바퀴 수레', 'tools', 3, 'noun'],
  ['shovel', '삽', 'tools', 2, 'noun'],
  ['rake', '갈퀴', 'tools', 2, 'noun'],
  ['hoe', '괭이', 'tools', 2, 'noun'],
  ['axe', '도끼', 'tools', 2, 'noun'],
  ['pickaxe', '곡괭이', 'tools', 2, 'noun'],
  ['chainsaw', '전기톱', 'tools', 3, 'noun'],
  ['paintbrush', '붓', 'tools', 2, 'noun'],
  ['roller', '롤러', 'tools', 2, 'noun'],
  ['sandpaper', '사포', 'tools', 2, 'noun'],
  ['clamp', '클램프', 'tools', 3, 'noun'],
  ['chisel', '끌', 'tools', 3, 'noun'],

  // ── cooking verbs & terms ──
  ['bake', '굽다(오븐)', 'cooking', 2, 'verb'],
  ['broil', '직화로 굽다', 'cooking', 3, 'verb'],
  ['grill', '그릴에 굽다', 'cooking', 2, 'verb'],
  ['roast', '로스팅하다', 'cooking', 2, 'verb'],
  ['steam', '찌다', 'cooking', 2, 'verb'],
  ['simmer', '약불로 끓이다', 'cooking', 3, 'verb'],
  ['sautee', '볶다', 'cooking', 3, 'verb'],
  ['deep fry', '튀기다', 'cooking', 2, 'verb'],
  ['blanch', '데치다', 'cooking', 3, 'verb'],
  ['marinate', '재우다', 'cooking', 3, 'verb'],
  ['season', '간을 하다', 'cooking', 2, 'verb'],
  ['garnish', '장식하다', 'cooking', 3, 'verb'],
  ['dice', '깍둑썰기하다', 'cooking', 2, 'verb'],
  ['mince', '다지다', 'cooking', 3, 'verb'],
  ['grate', '강판에 갈다', 'cooking', 2, 'verb'],
  ['whisk', '거품기로 섞다', 'cooking', 3, 'verb'],
  ['knead', '반죽하다', 'cooking', 3, 'verb'],
  ['strain', '거르다', 'cooking', 3, 'verb'],
  ['drain', '물기를 빼다', 'cooking', 2, 'verb'],
  ['defrost', '해동하다', 'cooking', 2, 'verb'],
  ['recipe', '요리법', 'cooking', 2, 'noun'],
  ['ingredient', '재료', 'cooking', 3, 'noun'],
  ['portion', '1인분', 'cooking', 2, 'noun'],
  ['serving', '분량', 'cooking', 2, 'noun'],
  ['appetizer', '전채요리', 'cooking', 3, 'noun'],
  ['main course', '메인요리', 'cooking', 2, 'noun'],
  ['side dish', '반찬', 'cooking', 2, 'noun'],
  ['dessert', '디저트', 'cooking', 2, 'noun'],
  ['leftover', '남은 음식', 'cooking', 2, 'noun'],
  ['takeout', '테이크아웃', 'cooking', 2, 'noun'],

  // ── verbs - movement & communication ──
  ['arrive', '도착하다', 'verbs', 2, 'verb'],
  ['depart', '출발하다', 'verbs', 3, 'verb'],
  ['enter', '들어가다', 'verbs', 2, 'verb'],
  ['exit', '나가다', 'verbs', 2, 'verb'],
  ['approach', '다가가다', 'verbs', 3, 'verb'],
  ['retreat', '후퇴하다', 'verbs', 3, 'verb'],
  ['advance', '전진하다', 'verbs', 3, 'verb'],
  ['follow', '따라가다', 'verbs', 2, 'verb'],
  ['lead', '이끌다', 'verbs', 2, 'verb'],
  ['chase', '쫓다', 'verbs', 2, 'verb'],
  ['escape', '탈출하다', 'verbs', 2, 'verb'],
  ['return', '돌아오다', 'verbs', 2, 'verb'],
  ['deliver', '배달하다', 'verbs', 2, 'verb'],
  ['transport', '수송하다', 'verbs', 3, 'verb'],
  ['transfer', '이동하다', 'verbs', 3, 'verb'],
  ['explore', '탐험하다', 'verbs', 2, 'verb'],
  ['discover', '발견하다', 'verbs', 2, 'verb'],
  ['search', '찾다', 'verbs', 2, 'verb'],
  ['seek', '구하다', 'verbs', 3, 'verb'],
  ['wander', '방황하다', 'verbs', 3, 'verb'],
  ['roam', '돌아다니다', 'verbs', 3, 'verb'],
  ['stroll', '산책하다', 'verbs', 2, 'verb'],
  ['march', '행진하다', 'verbs', 2, 'verb'],
  ['jog', '조깅하다', 'verbs', 2, 'verb'],
  ['sprint', '전력질주하다', 'verbs', 2, 'verb'],
  ['gallop', '전속력으로 달리다', 'verbs', 3, 'verb'],
  ['creep', '살금살금 가다', 'verbs', 2, 'verb'],
  ['sneak', '몰래 가다', 'verbs', 2, 'verb'],
  ['tiptoe', '발끝으로 걷다', 'verbs', 2, 'verb'],
  ['stumble', '비틀거리다', 'verbs', 3, 'verb'],
  ['trip', '넘어지다', 'verbs', 2, 'verb'],
  ['fall', '떨어지다', 'verbs', 2, 'verb'],
  ['slip', '미끄러지다', 'verbs', 2, 'verb'],
  ['crash', '충돌하다', 'verbs', 2, 'verb'],
  ['bump', '부딪히다', 'verbs', 2, 'verb'],
  ['collide', '충돌하다', 'verbs', 3, 'verb'],
  ['bounce', '튀다', 'verbs', 2, 'verb'],
  ['float', '뜨다', 'verbs', 2, 'verb'],
  ['sink', '가라앉다', 'verbs', 2, 'verb'],
  ['dive', '잠수하다', 'verbs', 2, 'verb'],
  ['soar', '높이 날다', 'verbs', 3, 'verb'],
  ['glide', '활공하다', 'verbs', 3, 'verb'],
  ['hover', '맴돌다', 'verbs', 3, 'verb'],
  ['land', '착륙하다', 'verbs', 2, 'verb'],
  ['launch', '발사하다', 'verbs', 3, 'verb'],
  ['communicate', '소통하다', 'verbs', 3, 'verb'],
  ['announce', '발표하다', 'verbs', 3, 'verb'],
  ['declare', '선언하다', 'verbs', 3, 'verb'],
  ['mention', '언급하다', 'verbs', 2, 'verb'],
  ['whisper', '속삭이다', 'verbs', 2, 'verb'],
  ['shout', '외치다', 'verbs', 2, 'verb'],
  ['scream', '비명지르다', 'verbs', 2, 'verb'],
  ['yell', '소리지르다', 'verbs', 2, 'verb'],
  ['mumble', '중얼거리다', 'verbs', 3, 'verb'],
  ['murmur', '속삭이다', 'verbs', 3, 'verb'],
  ['chat', '수다 떨다', 'verbs', 2, 'verb'],
  ['gossip', '가십하다', 'verbs', 3, 'verb'],
  ['complain', '불평하다', 'verbs', 2, 'verb'],
  ['praise', '칭찬하다', 'verbs', 2, 'verb'],
  ['criticize', '비판하다', 'verbs', 3, 'verb'],
  ['encourage', '격려하다', 'verbs', 2, 'verb'],
  ['warn', '경고하다', 'verbs', 2, 'verb'],
  ['remind', '상기시키다', 'verbs', 2, 'verb'],
  ['promise', '약속하다', 'verbs', 2, 'verb'],
  ['apologize', '사과하다', 'verbs', 3, 'verb'],
  ['forgive', '용서하다', 'verbs', 2, 'verb'],
  ['thank', '감사하다', 'verbs', 2, 'verb'],
  ['greet', '인사하다', 'verbs', 2, 'verb'],
  ['introduce', '소개하다', 'verbs', 2, 'verb'],
  ['invite', '초대하다', 'verbs', 2, 'verb'],
  ['refuse', '거절하다', 'verbs', 2, 'verb'],
  ['accept', '수락하다', 'verbs', 2, 'verb'],
  ['reject', '거부하다', 'verbs', 3, 'verb'],
  ['agree', '동의하다', 'verbs', 2, 'verb'],
  ['disagree', '반대하다', 'verbs', 2, 'verb'],
  ['argue', '논쟁하다', 'verbs', 2, 'verb'],
  ['debate', '토론하다', 'verbs', 3, 'verb'],
  ['persuade', '설득하다', 'verbs', 3, 'verb'],
  ['convince', '납득시키다', 'verbs', 3, 'verb'],
  ['negotiate', '협상하다', 'verbs', 3, 'verb'],

  // ── verbs - mental / thinking ──
  ['believe', '믿다', 'verbs', 2, 'verb'],
  ['doubt', '의심하다', 'verbs', 3, 'verb'],
  ['guess', '추측하다', 'verbs', 2, 'verb'],
  ['wonder', '궁금해하다', 'verbs', 2, 'verb'],
  ['imagine', '상상하다', 'verbs', 2, 'verb'],
  ['realize', '깨닫다', 'verbs', 2, 'verb'],
  ['recognize', '알아보다', 'verbs', 3, 'verb'],
  ['remember', '기억하다', 'verbs', 2, 'verb'],
  ['forget', '잊다', 'verbs', 2, 'verb'],
  ['notice', '알아차리다', 'verbs', 2, 'verb'],
  ['understand', '이해하다', 'verbs', 2, 'verb'],
  ['misunderstand', '오해하다', 'verbs', 3, 'verb'],
  ['consider', '고려하다', 'verbs', 3, 'verb'],
  ['decide', '결정하다', 'verbs', 2, 'verb'],
  ['choose', '선택하다', 'verbs', 2, 'verb'],
  ['prefer', '선호하다', 'verbs', 2, 'verb'],
  ['plan', '계획하다', 'verbs', 2, 'verb'],
  ['prepare', '준비하다', 'verbs', 2, 'verb'],
  ['expect', '기대하다', 'verbs', 2, 'verb'],
  ['hope', '바라다', 'verbs', 2, 'verb'],
  ['wish', '소원하다', 'verbs', 2, 'verb'],
  ['dream', '꿈꾸다', 'verbs', 2, 'verb'],
  ['worry', '걱정하다', 'verbs', 2, 'verb'],
  ['regret', '후회하다', 'verbs', 3, 'verb'],
  ['appreciate', '감사하다', 'verbs', 3, 'verb'],
  ['admire', '존경하다', 'verbs', 3, 'verb'],
  ['respect', '존중하다', 'verbs', 2, 'verb'],
  ['trust', '신뢰하다', 'verbs', 2, 'verb'],
  ['suspect', '의심하다', 'verbs', 3, 'verb'],
  ['ignore', '무시하다', 'verbs', 2, 'verb'],

  // ── verbs - creation & action ──
  ['create', '만들다', 'verbs', 2, 'verb'],
  ['invent', '발명하다', 'verbs', 3, 'verb'],
  ['design', '디자인하다', 'verbs', 2, 'verb'],
  ['construct', '건설하다', 'verbs', 3, 'verb'],
  ['destroy', '파괴하다', 'verbs', 2, 'verb'],
  ['repair', '수리하다', 'verbs', 2, 'verb'],
  ['replace', '교체하다', 'verbs', 2, 'verb'],
  ['install', '설치하다', 'verbs', 3, 'verb'],
  ['remove', '제거하다', 'verbs', 2, 'verb'],
  ['attach', '붙이다', 'verbs', 3, 'verb'],
  ['detach', '분리하다', 'verbs', 3, 'verb'],
  ['connect', '연결하다', 'verbs', 2, 'verb'],
  ['separate', '분리하다', 'verbs', 2, 'verb'],
  ['combine', '결합하다', 'verbs', 3, 'verb'],
  ['divide', '나누다', 'verbs', 2, 'verb'],
  ['multiply', '곱하다', 'verbs', 3, 'verb'],
  ['add', '더하다', 'verbs', 2, 'verb'],
  ['subtract', '빼다', 'verbs', 3, 'verb'],
  ['increase', '증가시키다', 'verbs', 2, 'verb'],
  ['decrease', '감소시키다', 'verbs', 3, 'verb'],
  ['expand', '확장하다', 'verbs', 3, 'verb'],
  ['shrink', '줄어들다', 'verbs', 2, 'verb'],
  ['stretch', '늘리다', 'verbs', 2, 'verb'],
  ['compress', '압축하다', 'verbs', 3, 'verb'],
  ['collect', '수집하다', 'verbs', 2, 'verb'],
  ['gather', '모으다', 'verbs', 2, 'verb'],
  ['scatter', '흩뿌리다', 'verbs', 3, 'verb'],
  ['spread', '퍼뜨리다', 'verbs', 2, 'verb'],
  ['arrange', '정렬하다', 'verbs', 2, 'verb'],
  ['organize', '조직하다', 'verbs', 2, 'verb'],
  ['sort', '정렬하다', 'verbs', 2, 'verb'],
  ['store', '저장하다', 'verbs', 2, 'verb'],
  ['pack', '포장하다', 'verbs', 2, 'verb'],
  ['unpack', '짐을 풀다', 'verbs', 2, 'verb'],
  ['wrap', '포장하다', 'verbs', 2, 'verb'],
  ['unwrap', '포장을 풀다', 'verbs', 2, 'verb'],
  ['load', '싣다', 'verbs', 2, 'verb'],
  ['unload', '내리다', 'verbs', 2, 'verb'],
  ['pour', '붓다', 'verbs', 2, 'verb'],
  ['spill', '쏟다', 'verbs', 2, 'verb'],

  // ── adjectives (grade 4 level) ──
  ['ancient', '고대의', 'adjectives', 3, 'adjective'],
  ['modern', '현대의', 'adjectives', 2, 'adjective'],
  ['traditional', '전통적인', 'adjectives', 3, 'adjective'],
  ['natural', '자연의', 'adjectives', 2, 'adjective'],
  ['artificial', '인공적인', 'adjectives', 3, 'adjective'],
  ['original', '원래의', 'adjectives', 3, 'adjective'],
  ['ordinary', '평범한', 'adjectives', 2, 'adjective'],
  ['extraordinary', '특별한', 'adjectives', 3, 'adjective'],
  ['common', '흔한', 'adjectives', 2, 'adjective'],
  ['rare', '희귀한', 'adjectives', 2, 'adjective'],
  ['unique', '독특한', 'adjectives', 2, 'adjective'],
  ['typical', '전형적인', 'adjectives', 3, 'adjective'],
  ['obvious', '명백한', 'adjectives', 3, 'adjective'],
  ['mysterious', '신비한', 'adjectives', 3, 'adjective'],
  ['familiar', '익숙한', 'adjectives', 2, 'adjective'],
  ['strange', '이상한', 'adjectives', 2, 'adjective'],
  ['weird', '기이한', 'adjectives', 2, 'adjective'],
  ['normal', '정상의', 'adjectives', 2, 'adjective'],
  ['unusual', '특이한', 'adjectives', 2, 'adjective'],
  ['certain', '확실한', 'adjectives', 2, 'adjective'],
  ['uncertain', '불확실한', 'adjectives', 3, 'adjective'],
  ['possible', '가능한', 'adjectives', 2, 'adjective'],
  ['impossible', '불가능한', 'adjectives', 2, 'adjective'],
  ['necessary', '필요한', 'adjectives', 3, 'adjective'],
  ['unnecessary', '불필요한', 'adjectives', 3, 'adjective'],
  ['available', '이용 가능한', 'adjectives', 3, 'adjective'],
  ['absent', '부재의', 'adjectives', 3, 'adjective'],
  ['present', '현재의', 'adjectives', 2, 'adjective'],
  ['recent', '최근의', 'adjectives', 2, 'adjective'],
  ['previous', '이전의', 'adjectives', 3, 'adjective'],
  ['following', '다음의', 'adjectives', 2, 'adjective'],
  ['entire', '전체의', 'adjectives', 2, 'adjective'],
  ['complete', '완전한', 'adjectives', 2, 'adjective'],
  ['incomplete', '불완전한', 'adjectives', 3, 'adjective'],
  ['basic', '기본의', 'adjectives', 2, 'adjective'],
  ['advanced', '고급의', 'adjectives', 3, 'adjective'],
  ['complex', '복잡한', 'adjectives', 3, 'adjective'],
  ['various', '다양한', 'adjectives', 3, 'adjective'],
  ['separate', '별도의', 'adjectives', 3, 'adjective'],
  ['similar', '비슷한', 'adjectives', 2, 'adjective'],
  ['identical', '동일한', 'adjectives', 3, 'adjective'],
  ['opposite', '반대의', 'adjectives', 2, 'adjective'],
  ['equal', '같은', 'adjectives', 2, 'adjective'],
  ['unequal', '불평등한', 'adjectives', 3, 'adjective'],
  ['fair', '공정한', 'adjectives', 2, 'adjective'],
  ['unfair', '불공정한', 'adjectives', 2, 'adjective'],
  ['legal', '합법적인', 'adjectives', 3, 'adjective'],
  ['illegal', '불법적인', 'adjectives', 3, 'adjective'],
  ['public', '공공의', 'adjectives', 2, 'adjective'],
  ['private', '사적인', 'adjectives', 2, 'adjective'],
  ['official', '공식적인', 'adjectives', 3, 'adjective'],
  ['professional', '전문적인', 'adjectives', 3, 'adjective'],
  ['physical', '신체적인', 'adjectives', 3, 'adjective'],
  ['mental', '정신적인', 'adjectives', 3, 'adjective'],
  ['emotional', '감정적인', 'adjectives', 3, 'adjective'],
  ['financial', '재정적인', 'adjectives', 3, 'adjective'],
  ['political', '정치적인', 'adjectives', 3, 'adjective'],
  ['cultural', '문화적인', 'adjectives', 3, 'adjective'],
  ['global', '세계적인', 'adjectives', 2, 'adjective'],
  ['local', '지역의', 'adjectives', 2, 'adjective'],
  ['national', '국가의', 'adjectives', 3, 'adjective'],
  ['international', '국제적인', 'adjectives', 3, 'adjective'],
  ['urban', '도시의', 'adjectives', 3, 'adjective'],
  ['rural', '시골의', 'adjectives', 3, 'adjective'],
  ['suburban', '교외의', 'adjectives', 3, 'adjective'],
  ['industrial', '산업의', 'adjectives', 3, 'adjective'],
  ['commercial', '상업의', 'adjectives', 3, 'adjective'],
  ['residential', '주거의', 'adjectives', 3, 'adjective'],
  ['educational', '교육의', 'adjectives', 3, 'adjective'],
  ['environmental', '환경의', 'adjectives', 3, 'adjective'],
  ['scientific', '과학적인', 'adjectives', 3, 'adjective'],
  ['technological', '기술적인', 'adjectives', 3, 'adjective'],
  ['historical', '역사적인', 'adjectives', 3, 'adjective'],
  ['geographical', '지리적인', 'adjectives', 3, 'adjective'],
  ['biological', '생물학적인', 'adjectives', 3, 'adjective'],
  ['chemical', '화학적인', 'adjectives', 3, 'adjective'],
  ['electrical', '전기의', 'adjectives', 3, 'adjective'],
  ['mechanical', '기계적인', 'adjectives', 3, 'adjective'],
  ['automatic', '자동의', 'adjectives', 3, 'adjective'],
  ['manual', '수동의', 'adjectives', 3, 'adjective'],

  // ── daily life nouns ──
  ['alarm', '알람', 'daily', 2, 'noun'],
  ['appointment', '약속', 'daily', 3, 'noun'],
  ['backpack', '배낭', 'daily', 2, 'noun'],
  ['blanket', '담요', 'daily', 2, 'noun'],
  ['calendar', '달력', 'daily', 2, 'noun'],
  ['chore', '집안일', 'daily', 2, 'noun'],
  ['commute', '출퇴근', 'daily', 3, 'noun'],
  ['deadline', '마감', 'daily', 3, 'noun'],
  ['diary', '일기장', 'daily', 2, 'noun'],
  ['errand', '심부름', 'daily', 2, 'noun'],
  ['grocery', '식료품', 'daily', 2, 'noun'],
  ['hobby', '취미', 'daily', 2, 'noun'],
  ['housework', '집안일', 'daily', 2, 'noun'],
  ['laundry', '빨래', 'daily', 2, 'noun'],
  ['luggage', '짐', 'daily', 3, 'noun'],
  ['mail', '우편', 'daily', 2, 'noun'],
  ['nap', '낮잠', 'daily', 2, 'noun'],
  ['pillow', '베개', 'daily', 2, 'noun'],
  ['receipt', '영수증', 'daily', 3, 'noun'],
  ['routine', '일상', 'daily', 3, 'noun'],
  ['schedule', '일정', 'daily', 2, 'noun'],
  ['suitcase', '여행가방', 'daily', 2, 'noun'],
  ['task', '과업', 'daily', 2, 'noun'],
  ['wallet', '지갑', 'daily', 2, 'noun'],
  ['weekend', '주말', 'daily', 2, 'noun'],

  // ── school subjects & academic ──
  ['arithmetic', '산수', 'school', 3, 'noun'],
  ['biology', '생물학', 'school', 3, 'noun'],
  ['chemistry', '화학', 'school', 3, 'noun'],
  ['composition', '작문', 'school', 3, 'noun'],
  ['curriculum', '교과과정', 'school', 3, 'noun'],
  ['debate', '토론', 'school', 3, 'noun'],
  ['economics', '경제학', 'school', 3, 'noun'],
  ['essay', '에세이', 'school', 2, 'noun'],
  ['ethics', '윤리', 'school', 3, 'noun'],
  ['geography', '지리', 'school', 2, 'noun'],
  ['history', '역사', 'school', 2, 'noun'],
  ['literature', '문학', 'school', 3, 'noun'],
  ['philosophy', '철학', 'school', 3, 'noun'],
  ['physics', '물리학', 'school', 3, 'noun'],
  ['psychology', '심리학', 'school', 3, 'noun'],
  ['sociology', '사회학', 'school', 3, 'noun'],
  ['algebra', '대수학', 'school', 3, 'noun'],
  ['geometry', '기하학', 'school', 3, 'noun'],
  ['calculus', '미적분', 'school', 3, 'noun'],
  ['trigonometry', '삼각법', 'school', 3, 'noun'],

  // ── nature / outdoor ──
  ['campfire', '캠프파이어', 'outdoor', 2, 'noun'],
  ['compass', '나침반', 'outdoor', 2, 'noun'],
  ['flashlight', '손전등', 'outdoor', 2, 'noun'],
  ['gear', '장비', 'outdoor', 2, 'noun'],
  ['hammock', '해먹', 'outdoor', 3, 'noun'],
  ['insect repellent', '방충제', 'outdoor', 3, 'noun'],
  ['lantern', '랜턴', 'outdoor', 2, 'noun'],
  ['map', '지도', 'outdoor', 2, 'noun'],
  ['path', '길', 'outdoor', 2, 'noun'],
  ['sleeping bag', '침낭', 'outdoor', 2, 'noun'],
  ['sunscreen', '자외선차단제', 'outdoor', 2, 'noun'],
  ['tent', '텐트', 'outdoor', 2, 'noun'],
  ['thermos', '보온병', 'outdoor', 2, 'noun'],
  ['trail', '등산로', 'outdoor', 2, 'noun'],
  ['waterproof', '방수의', 'outdoor', 3, 'adjective'],
  ['campground', '야영장', 'outdoor', 2, 'noun'],
  ['wilderness', '황야', 'outdoor', 3, 'noun'],
  ['picnic', '소풍', 'outdoor', 2, 'noun'],
  ['barbecue', '바베큐', 'outdoor', 2, 'noun'],
  ['bonfire', '모닥불', 'outdoor', 2, 'noun'],

  // ── body actions / physical ──
  ['balance', '균형잡다', 'physical', 2, 'verb'],
  ['bounce', '튀다', 'physical', 2, 'verb'],
  ['cartwheel', '옆돌기', 'physical', 3, 'noun'],
  ['dodge', '피하다', 'physical', 2, 'verb'],
  ['exercise', '운동하다', 'physical', 2, 'verb'],
  ['flex', '구부리다', 'physical', 2, 'verb'],
  ['gallop', '질주하다', 'physical', 3, 'verb'],
  ['handstand', '물구나무서기', 'physical', 2, 'noun'],
  ['jog', '조깅하다', 'physical', 2, 'verb'],
  ['leap', '도약하다', 'physical', 2, 'verb'],
  ['lunge', '돌진하다', 'physical', 3, 'verb'],
  ['march', '행진하다', 'physical', 2, 'verb'],
  ['plunge', '뛰어들다', 'physical', 3, 'verb'],
  ['somersault', '재주넘기', 'physical', 3, 'noun'],
  ['sprint', '전력질주', 'physical', 2, 'verb'],
  ['squat', '쪼그리다', 'physical', 2, 'verb'],
  ['toss', '던지다', 'physical', 2, 'verb'],
  ['tumble', '구르다', 'physical', 2, 'verb'],
  ['wade', '걸어서 건너다', 'physical', 3, 'verb'],
  ['wrestle', '씨름하다', 'physical', 3, 'verb'],

  // ── more emotions/personality ──
  ['ambitious', '야심찬', 'personality', 3, 'adjective'],
  ['arrogant', '거만한', 'personality', 3, 'adjective'],
  ['awkward', '어색한', 'personality', 2, 'adjective'],
  ['careless', '부주의한', 'personality', 2, 'adjective'],
  ['cautious', '조심스러운', 'personality', 3, 'adjective'],
  ['charming', '매력적인', 'personality', 2, 'adjective'],
  ['clever', '영리한', 'personality', 2, 'adjective'],
  ['clumsy', '서투른', 'personality', 2, 'adjective'],
  ['courageous', '용감한', 'personality', 3, 'adjective'],
  ['cowardly', '겁많은', 'personality', 3, 'adjective'],
  ['cruel', '잔인한', 'personality', 3, 'adjective'],
  ['dedicated', '헌신적인', 'personality', 3, 'adjective'],
  ['diligent', '부지런한', 'personality', 3, 'adjective'],
  ['easygoing', '느긋한', 'personality', 2, 'adjective'],
  ['elegant', '우아한', 'personality', 3, 'adjective'],
  ['faithful', '충실한', 'personality', 3, 'adjective'],
  ['fierce', '사나운', 'personality', 2, 'adjective'],
  ['generous', '관대한', 'personality', 3, 'adjective'],
  ['genuine', '진실한', 'personality', 3, 'adjective'],
  ['gloomy', '우울한', 'personality', 3, 'adjective'],
  ['graceful', '우아한', 'personality', 3, 'adjective'],
  ['greedy', '욕심 많은', 'personality', 2, 'adjective'],
  ['gullible', '잘 속는', 'personality', 3, 'adjective'],
  ['humble', '겸손한', 'personality', 3, 'adjective'],
  ['impatient', '참을성 없는', 'personality', 2, 'adjective'],
  ['independent', '독립적인', 'personality', 3, 'adjective'],
  ['innocent', '순진한', 'personality', 3, 'adjective'],
  ['intelligent', '총명한', 'personality', 3, 'adjective'],
  ['loyal', '충성스러운', 'personality', 3, 'adjective'],
  ['mature', '성숙한', 'personality', 3, 'adjective'],
  ['mischievous', '장난꾸러기의', 'personality', 3, 'adjective'],
  ['modest', '겸손한', 'personality', 3, 'adjective'],
  ['naive', '순진한', 'personality', 3, 'adjective'],
  ['noble', '고결한', 'personality', 3, 'adjective'],
  ['obedient', '순종적인', 'personality', 3, 'adjective'],
  ['observant', '관찰력 있는', 'personality', 3, 'adjective'],
  ['outgoing', '외향적인', 'personality', 2, 'adjective'],
  ['passionate', '열정적인', 'personality', 3, 'adjective'],
  ['persistent', '끈기있는', 'personality', 3, 'adjective'],
  ['playful', '장난스러운', 'personality', 2, 'adjective'],
  ['reliable', '믿을 수 있는', 'personality', 3, 'adjective'],
  ['resourceful', '수완 좋은', 'personality', 3, 'adjective'],
  ['respectful', '공손한', 'personality', 3, 'adjective'],
  ['responsible', '책임감 있는', 'personality', 3, 'adjective'],
  ['secretive', '비밀스러운', 'personality', 3, 'adjective'],
  ['sensitive', '민감한', 'personality', 3, 'adjective'],
  ['sincere', '진심의', 'personality', 3, 'adjective'],
  ['stubborn', '고집센', 'personality', 2, 'adjective'],
  ['thoughtful', '사려깊은', 'personality', 3, 'adjective'],
  ['timid', '소심한', 'personality', 3, 'adjective'],
  ['tolerant', '관용적인', 'personality', 3, 'adjective'],
  ['trustworthy', '신뢰할 수 있는', 'personality', 3, 'adjective'],
  ['vain', '허영심 있는', 'personality', 3, 'adjective'],
  ['versatile', '다재다능한', 'personality', 3, 'adjective'],
  ['witty', '재치 있는', 'personality', 3, 'adjective'],

  // ── more geography ──
  ['atlas', '지도책', 'geography', 2, 'noun'],
  ['compass rose', '나침반 표시', 'geography', 3, 'noun'],
  ['continent', '대륙', 'geography', 3, 'noun'],
  ['desert', '사막', 'geography', 2, 'noun'],
  ['elevation', '고도', 'geography', 3, 'noun'],
  ['globe', '지구본', 'geography', 2, 'noun'],
  ['hemisphere', '반구', 'geography', 3, 'noun'],
  ['jungle', '정글', 'geography', 2, 'noun'],
  ['lagoon', '석호', 'geography', 3, 'noun'],
  ['landform', '지형', 'geography', 3, 'noun'],
  ['latitude', '위도', 'geography', 3, 'noun'],
  ['longitude', '경도', 'geography', 3, 'noun'],
  ['meadow', '초원', 'geography', 2, 'noun'],
  ['ocean', '대양', 'geography', 2, 'noun'],
  ['prairie', '대초원', 'geography', 3, 'noun'],
  ['rainforest', '우림', 'geography', 2, 'noun'],
  ['savanna', '사바나', 'geography', 3, 'noun'],
  ['shore', '물가', 'geography', 2, 'noun'],
  ['summit', '정상', 'geography', 3, 'noun'],
  ['tundra', '툰드라', 'geography', 3, 'noun'],
  ['tributary', '지류', 'geography', 3, 'noun'],
  ['volcano', '화산', 'geography', 2, 'noun'],
  ['waterway', '수로', 'geography', 3, 'noun'],
  ['wetland', '습지', 'geography', 3, 'noun'],
  ['woodland', '삼림지', 'geography', 2, 'noun'],

  // ── music / art terms ──
  ['audience', '관객', 'arts', 2, 'noun'],
  ['audition', '오디션', 'arts', 3, 'noun'],
  ['backstage', '무대 뒤', 'arts', 2, 'noun'],
  ['ballet', '발레', 'arts', 2, 'noun'],
  ['canvas', '캔버스', 'arts', 2, 'noun'],
  ['cast', '출연진', 'arts', 2, 'noun'],
  ['choir', '합창단', 'arts', 3, 'noun'],
  ['choreography', '안무', 'arts', 3, 'noun'],
  ['compose', '작곡하다', 'arts', 3, 'verb'],
  ['concert', '콘서트', 'arts', 2, 'noun'],
  ['conductor', '지휘자', 'arts', 3, 'noun'],
  ['costume', '의상', 'arts', 2, 'noun'],
  ['curtain', '막', 'arts', 2, 'noun'],
  ['director', '감독', 'arts', 2, 'noun'],
  ['duet', '이중주', 'arts', 3, 'noun'],
  ['encore', '앙코르', 'arts', 3, 'noun'],
  ['ensemble', '앙상블', 'arts', 3, 'noun'],
  ['exhibit', '전시품', 'arts', 3, 'noun'],
  ['gallery', '갤러리', 'arts', 2, 'noun'],
  ['harmony', '화음', 'arts', 3, 'noun'],
  ['lyric', '가사', 'arts', 2, 'noun'],
  ['melody', '멜로디', 'arts', 2, 'noun'],
  ['mural', '벽화', 'arts', 3, 'noun'],
  ['opera', '오페라', 'arts', 3, 'noun'],
  ['orchestra', '오케스트라', 'arts', 3, 'noun'],
  ['overture', '서곡', 'arts', 3, 'noun'],
  ['palette', '팔레트', 'arts', 3, 'noun'],
  ['performance', '공연', 'arts', 2, 'noun'],
  ['portrait', '초상화', 'arts', 3, 'noun'],
  ['rehearsal', '리허설', 'arts', 3, 'noun'],
  ['rhythm', '리듬', 'arts', 2, 'noun'],
  ['scenery', '무대 장치', 'arts', 3, 'noun'],
  ['sketch', '스케치', 'arts', 2, 'noun'],
  ['solo', '독주', 'arts', 2, 'noun'],
  ['spotlight', '스포트라이트', 'arts', 2, 'noun'],
  ['stage', '무대', 'arts', 2, 'noun'],
  ['symphony', '교향곡', 'arts', 3, 'noun'],
  ['tempo', '박자', 'arts', 3, 'noun'],
  ['verse', '절', 'arts', 3, 'noun'],
  ['watercolor', '수채화', 'arts', 2, 'noun'],

  // ── space / solar system ──
  ['asteroid', '소행성', 'space', 3, 'noun'],
  ['atmosphere', '대기', 'space', 3, 'noun'],
  ['comet', '혜성', 'space', 3, 'noun'],
  ['constellation', '별자리', 'space', 3, 'noun'],
  ['crater', '분화구', 'space', 3, 'noun'],
  ['galaxy', '은하', 'space', 3, 'noun'],
  ['gravity', '중력', 'space', 2, 'noun'],
  ['lunar', '달의', 'space', 3, 'adjective'],
  ['meteor', '유성', 'space', 3, 'noun'],
  ['moon', '달', 'space', 2, 'noun'],
  ['orbit', '궤도', 'space', 3, 'noun'],
  ['planet', '행성', 'space', 2, 'noun'],
  ['rocket', '로켓', 'space', 2, 'noun'],
  ['satellite', '인공위성', 'space', 3, 'noun'],
  ['solar', '태양의', 'space', 2, 'adjective'],
  ['spacecraft', '우주선', 'space', 3, 'noun'],
  ['star', '별', 'space', 2, 'noun'],
  ['sun', '태양', 'space', 2, 'noun'],
  ['telescope', '망원경', 'space', 2, 'noun'],
  ['universe', '우주', 'space', 2, 'noun'],
  ['astronaut', '우주비행사', 'space', 2, 'noun'],
  ['spacewalk', '우주유영', 'space', 3, 'noun'],
  ['launch pad', '발사대', 'space', 3, 'noun'],
  ['mission', '임무', 'space', 2, 'noun'],
  ['space station', '우주정거장', 'space', 3, 'noun'],

  // ── history / social studies ──
  ['ancient', '고대의', 'history', 3, 'adjective'],
  ['battle', '전투', 'history', 2, 'noun'],
  ['castle', '성', 'history', 2, 'noun'],
  ['century', '세기', 'history', 3, 'noun'],
  ['civilization', '문명', 'history', 3, 'noun'],
  ['colony', '식민지', 'history', 3, 'noun'],
  ['conquer', '정복하다', 'history', 3, 'verb'],
  ['decade', '10년', 'history', 3, 'noun'],
  ['dynasty', '왕조', 'history', 3, 'noun'],
  ['emperor', '황제', 'history', 3, 'noun'],
  ['empire', '제국', 'history', 2, 'noun'],
  ['era', '시대', 'history', 3, 'noun'],
  ['expedition', '탐험대', 'history', 3, 'noun'],
  ['freedom', '자유', 'history', 2, 'noun'],
  ['independence', '독립', 'history', 3, 'noun'],
  ['invasion', '침략', 'history', 3, 'noun'],
  ['kingdom', '왕국', 'history', 2, 'noun'],
  ['knight', '기사', 'history', 2, 'noun'],
  ['medieval', '중세의', 'history', 3, 'adjective'],
  ['monarch', '군주', 'history', 3, 'noun'],
  ['pioneer', '개척자', 'history', 2, 'noun'],
  ['prince', '왕자', 'history', 2, 'noun'],
  ['princess', '공주', 'history', 2, 'noun'],
  ['queen', '여왕', 'history', 2, 'noun'],
  ['rebellion', '반란', 'history', 3, 'noun'],
  ['revolution', '혁명', 'history', 3, 'noun'],
  ['slavery', '노예제', 'history', 3, 'noun'],
  ['treaty', '조약', 'history', 3, 'noun'],
  ['tribe', '부족', 'history', 2, 'noun'],
  ['warrior', '전사', 'history', 2, 'noun'],
];

export const extraGrade4Words: WordData[] = expand(DATA, 1);
