import { WordData } from '@/shared/types/game';

export const grade5Words: WordData[] = [
  {
    id: 'g5_001',
    english: 'environment',
    korean: '환경',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a environment.',
    exampleKorean: '나는 환경을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_002',
    english: 'pollution',
    korean: '오염',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a pollution.',
    exampleKorean: '나는 오염을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_003',
    english: 'climate',
    korean: '기후',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a climate.',
    exampleKorean: '나는 기후을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_004',
    english: 'recycle',
    korean: '재활용하다',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a recycle.',
    exampleKorean: '나는 재활용하다을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_005',
    english: 'endangered',
    korean: '멸종위기의',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a endangered.',
    exampleKorean: '나는 멸종위기의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_006',
    english: 'extinct',
    korean: '멸종된',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a extinct.',
    exampleKorean: '나는 멸종된을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_007',
    english: 'habitat',
    korean: '서식지',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a habitat.',
    exampleKorean: '나는 서식지을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_008',
    english: 'ecosystem',
    korean: '생태계',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ecosystem.',
    exampleKorean: '나는 생태계을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_009',
    english: 'conservation',
    korean: '보존',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a conservation.',
    exampleKorean: '나는 보존을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_010',
    english: 'renewable',
    korean: '재생가능한',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a renewable.',
    exampleKorean: '나는 재생가능한을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_011',
    english: 'solar',
    korean: '태양의',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a solar.',
    exampleKorean: '나는 태양의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_012',
    english: 'rainforest',
    korean: '열대우림',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a rainforest.',
    exampleKorean: '나는 열대우림을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_013',
    english: 'jungle',
    korean: '정글',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a jungle.',
    exampleKorean: '나는 정글을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_014',
    english: 'tundra',
    korean: '동토',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a tundra.',
    exampleKorean: '나는 동토을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_015',
    english: 'valley',
    korean: '계곡',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a valley.',
    exampleKorean: '나는 계곡을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_016',
    english: 'canyon',
    korean: '협곡',
    grade: 5 as const,
    category: 'environment',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a canyon.',
    exampleKorean: '나는 협곡을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_017',
    english: 'volcano',
    korean: '화산',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a volcano.',
    exampleKorean: '나는 화산을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_018',
    english: 'earthquake',
    korean: '지진',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a earthquake.',
    exampleKorean: '나는 지진을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_019',
    english: 'tsunami',
    korean: '쓰나미',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a tsunami.',
    exampleKorean: '나는 쓰나미을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_020',
    english: 'hurricane',
    korean: '허리케인',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a hurricane.',
    exampleKorean: '나는 허리케인을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_021',
    english: 'tornado',
    korean: '토네이도',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a tornado.',
    exampleKorean: '나는 토네이도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_022',
    english: 'flood',
    korean: '홍수',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a flood.',
    exampleKorean: '나는 홍수을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_023',
    english: 'drought',
    korean: '가뭄',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a drought.',
    exampleKorean: '나는 가뭄을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_024',
    english: 'glacier',
    korean: '빙하',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a glacier.',
    exampleKorean: '나는 빙하을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_025',
    english: 'continent',
    korean: '대륙',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a continent.',
    exampleKorean: '나는 대륙을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_026',
    english: 'country',
    korean: '나라',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a country.',
    exampleKorean: '나는 나라을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_027',
    english: 'capital',
    korean: '수도',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a capital.',
    exampleKorean: '나는 수도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_028',
    english: 'border',
    korean: '국경',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a border.',
    exampleKorean: '나는 국경을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_029',
    english: 'population',
    korean: '인구',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a population.',
    exampleKorean: '나는 인구을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_030',
    english: 'region',
    korean: '지역',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a region.',
    exampleKorean: '나는 지역을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_031',
    english: 'peninsula',
    korean: '반도',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a peninsula.',
    exampleKorean: '나는 반도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_032',
    english: 'coast',
    korean: '해안',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a coast.',
    exampleKorean: '나는 해안을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_033',
    english: 'cliff',
    korean: '절벽',
    grade: 5 as const,
    category: 'environment',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a cliff.',
    exampleKorean: '나는 절벽을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_034',
    english: 'cave',
    korean: '동굴',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a cave.',
    exampleKorean: '나는 동굴을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_035',
    english: 'waterfall',
    korean: '폭포',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a waterfall.',
    exampleKorean: '나는 폭포을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_036',
    english: 'swamp',
    korean: '늪',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a swamp.',
    exampleKorean: '나는 늪을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_037',
    english: 'oasis',
    korean: '오아시스',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a oasis.',
    exampleKorean: '나는 오아시스을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_038',
    english: 'reef',
    korean: '암초',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a reef.',
    exampleKorean: '나는 암초을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_039',
    english: 'plateau',
    korean: '고원',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a plateau.',
    exampleKorean: '나는 고원을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_040',
    english: 'erosion',
    korean: '침식',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a erosion.',
    exampleKorean: '나는 침식을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_041',
    english: 'prairie',
    korean: '대초원',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a prairie.',
    exampleKorean: '나는 대초원을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_042',
    english: 'delta',
    korean: '삼각주',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a delta.',
    exampleKorean: '나는 삼각주을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_043',
    english: 'dune',
    korean: '모래언덕',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a dune.',
    exampleKorean: '나는 모래언덕을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_044',
    english: 'geyser',
    korean: '간헐천',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a geyser.',
    exampleKorean: '나는 간헐천을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_045',
    english: 'landslide',
    korean: '산사태',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a landslide.',
    exampleKorean: '나는 산사태을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_046',
    english: 'avalanche',
    korean: '눈사태',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a avalanche.',
    exampleKorean: '나는 눈사태을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_047',
    english: 'iceberg',
    korean: '빙산',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a iceberg.',
    exampleKorean: '나는 빙산을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_048',
    english: 'strait',
    korean: '해협',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a strait.',
    exampleKorean: '나는 해협을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_049',
    english: 'bay',
    korean: '만',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a bay.',
    exampleKorean: '나는 만을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_050',
    english: 'harbor',
    korean: '항구',
    grade: 5 as const,
    category: 'environment',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a harbor.',
    exampleKorean: '나는 항구을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_051',
    english: 'history',
    korean: '역사',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a history.',
    exampleKorean: '나는 역사을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_052',
    english: 'ancient',
    korean: '고대의',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ancient.',
    exampleKorean: '나는 고대의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_053',
    english: 'modern',
    korean: '현대의',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a modern.',
    exampleKorean: '나는 현대의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_054',
    english: 'century',
    korean: '세기',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a century.',
    exampleKorean: '나는 세기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_055',
    english: 'civilization',
    korean: '문명',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a civilization.',
    exampleKorean: '나는 문명을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_056',
    english: 'empire',
    korean: '제국',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a empire.',
    exampleKorean: '나는 제국을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_057',
    english: 'kingdom',
    korean: '왕국',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a kingdom.',
    exampleKorean: '나는 왕국을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_058',
    english: 'revolution',
    korean: '혁명',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a revolution.',
    exampleKorean: '나는 혁명을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_059',
    english: 'independence',
    korean: '독립',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a independence.',
    exampleKorean: '나는 독립을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_060',
    english: 'democracy',
    korean: '민주주의',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a democracy.',
    exampleKorean: '나는 민주주의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_061',
    english: 'government',
    korean: '정부',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a government.',
    exampleKorean: '나는 정부을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_062',
    english: 'president',
    korean: '대통령',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a president.',
    exampleKorean: '나는 대통령을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_063',
    english: 'constitution',
    korean: '헌법',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a constitution.',
    exampleKorean: '나는 헌법을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_064',
    english: 'law',
    korean: '법',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a law.',
    exampleKorean: '나는 법을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_065',
    english: 'freedom',
    korean: '자유',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a freedom.',
    exampleKorean: '나는 자유을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_066',
    english: 'peace',
    korean: '평화',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a peace.',
    exampleKorean: '나는 평화을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_067',
    english: 'war',
    korean: '전쟁',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a war.',
    exampleKorean: '나는 전쟁을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_068',
    english: 'battle',
    korean: '전투',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a battle.',
    exampleKorean: '나는 전투을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_069',
    english: 'army',
    korean: '군대',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a army.',
    exampleKorean: '나는 군대을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_070',
    english: 'weapon',
    korean: '무기',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a weapon.',
    exampleKorean: '나는 무기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_071',
    english: 'shield',
    korean: '방패',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a shield.',
    exampleKorean: '나는 방패을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_072',
    english: 'sword',
    korean: '검',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a sword.',
    exampleKorean: '나는 검을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_073',
    english: 'castle',
    korean: '성',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a castle.',
    exampleKorean: '나는 성을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_074',
    english: 'throne',
    korean: '왕좌',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a throne.',
    exampleKorean: '나는 왕좌을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_075',
    english: 'crown',
    korean: '왕관',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a crown.',
    exampleKorean: '나는 왕관을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_076',
    english: 'flag',
    korean: '국기',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a flag.',
    exampleKorean: '나는 국기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_077',
    english: 'nation',
    korean: '국가',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a nation.',
    exampleKorean: '나는 국가을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_078',
    english: 'citizen',
    korean: '시민',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a citizen.',
    exampleKorean: '나는 시민을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_079',
    english: 'culture',
    korean: '문화',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a culture.',
    exampleKorean: '나는 문화을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_080',
    english: 'tradition',
    korean: '전통',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a tradition.',
    exampleKorean: '나는 전통을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_081',
    english: 'festival',
    korean: '축제',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a festival.',
    exampleKorean: '나는 축제을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_082',
    english: 'ceremony',
    korean: '의식',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ceremony.',
    exampleKorean: '나는 의식을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_083',
    english: 'heritage',
    korean: '유산',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a heritage.',
    exampleKorean: '나는 유산을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_084',
    english: 'monument',
    korean: '기념비',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a monument.',
    exampleKorean: '나는 기념비을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_085',
    english: 'museum',
    korean: '박물관',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a museum.',
    exampleKorean: '나는 박물관을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_086',
    english: 'treaty',
    korean: '조약',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a treaty.',
    exampleKorean: '나는 조약을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_087',
    english: 'alliance',
    korean: '동맹',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a alliance.',
    exampleKorean: '나는 동맹을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_088',
    english: 'trade',
    korean: '무역',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a trade.',
    exampleKorean: '나는 무역을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_089',
    english: 'economy',
    korean: '경제',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a economy.',
    exampleKorean: '나는 경제을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_090',
    english: 'currency',
    korean: '화폐',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a currency.',
    exampleKorean: '나는 화폐을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_091',
    english: 'invention',
    korean: '발명',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a invention.',
    exampleKorean: '나는 발명을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_092',
    english: 'colony',
    korean: '식민지',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a colony.',
    exampleKorean: '나는 식민지을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_093',
    english: 'armor',
    korean: '갑옷',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a armor.',
    exampleKorean: '나는 갑옷을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_094',
    english: 'document',
    korean: '문서',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a document.',
    exampleKorean: '나는 문서을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_095',
    english: 'artifact',
    korean: '유물',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a artifact.',
    exampleKorean: '나는 유물을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_096',
    english: 'conquest',
    korean: '정복',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a conquest.',
    exampleKorean: '나는 정복을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_097',
    english: 'dynasty',
    korean: '왕조',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a dynasty.',
    exampleKorean: '나는 왕조을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_098',
    english: 'medieval',
    korean: '중세의',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a medieval.',
    exampleKorean: '나는 중세의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_099',
    english: 'renaissance',
    korean: '르네상스',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a renaissance.',
    exampleKorean: '나는 르네상스을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_100',
    english: 'slavery',
    korean: '노예제도',
    grade: 5 as const,
    category: 'history',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a slavery.',
    exampleKorean: '나는 노예제도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_101',
    english: 'technology',
    korean: '기술',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a technology.',
    exampleKorean: '나는 기술을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_102',
    english: 'robot',
    korean: '로봇',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a robot.',
    exampleKorean: '나는 로봇을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_103',
    english: 'drone',
    korean: '드론',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a drone.',
    exampleKorean: '나는 드론을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_104',
    english: 'smartphone',
    korean: '스마트폰',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a smartphone.',
    exampleKorean: '나는 스마트폰을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_105',
    english: 'tablet',
    korean: '태블릿',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a tablet.',
    exampleKorean: '나는 태블릿을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_106',
    english: 'laptop',
    korean: '노트북',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a laptop.',
    exampleKorean: '나는 노트북을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_107',
    english: 'software',
    korean: '소프트웨어',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a software.',
    exampleKorean: '나는 소프트웨어을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_108',
    english: 'hardware',
    korean: '하드웨어',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a hardware.',
    exampleKorean: '나는 하드웨어을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_109',
    english: 'application',
    korean: '앱',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a application.',
    exampleKorean: '나는 앱을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_110',
    english: 'download',
    korean: '다운로드',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a download.',
    exampleKorean: '나는 다운로드을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_111',
    english: 'website',
    korean: '웹사이트',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a website.',
    exampleKorean: '나는 웹사이트을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_112',
    english: 'cloud',
    korean: '클라우드',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a cloud.',
    exampleKorean: '나는 클라우드을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_113',
    english: 'server',
    korean: '서버',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a server.',
    exampleKorean: '나는 서버을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_114',
    english: 'database',
    korean: '데이터베이스',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a database.',
    exampleKorean: '나는 데이터베이스을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_115',
    english: 'algorithm',
    korean: '알고리즘',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a algorithm.',
    exampleKorean: '나는 알고리즘을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_116',
    english: 'coding',
    korean: '코딩',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a coding.',
    exampleKorean: '나는 코딩을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_117',
    english: 'programming',
    korean: '프로그래밍',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a programming.',
    exampleKorean: '나는 프로그래밍을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_118',
    english: 'network',
    korean: '네트워크',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a network.',
    exampleKorean: '나는 네트워크을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_119',
    english: 'wireless',
    korean: '무선',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a wireless.',
    exampleKorean: '나는 무선을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_120',
    english: 'GPS',
    korean: 'GPS',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a GPS.',
    exampleKorean: '나는 GPS을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_121',
    english: 'sensor',
    korean: '센서',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a sensor.',
    exampleKorean: '나는 센서을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_122',
    english: 'automation',
    korean: '자동화',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a automation.',
    exampleKorean: '나는 자동화을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_123',
    english: 'password',
    korean: '비밀번호',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a password.',
    exampleKorean: '나는 비밀번호을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_124',
    english: 'digital',
    korean: '디지털',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a digital.',
    exampleKorean: '나는 디지털을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_125',
    english: 'pixel',
    korean: '픽셀',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a pixel.',
    exampleKorean: '나는 픽셀을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_126',
    english: 'streaming',
    korean: '스트리밍',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a streaming.',
    exampleKorean: '나는 스트리밍을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_127',
    english: 'podcast',
    korean: '팟캐스트',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a podcast.',
    exampleKorean: '나는 팟캐스트을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_128',
    english: 'blog',
    korean: '블로그',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a blog.',
    exampleKorean: '나는 블로그을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_129',
    english: 'notification',
    korean: '알림',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a notification.',
    exampleKorean: '나는 알림을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_130',
    english: 'update',
    korean: '업데이트',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a update.',
    exampleKorean: '나는 업데이트을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_131',
    english: 'virtual reality',
    korean: '가상현실',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a virtual reality.',
    exampleKorean: '나는 가상현실을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_132',
    english: 'artificial intelligence',
    korean: '인공지능',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a artificial intelligence.',
    exampleKorean: '나는 인공지능을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_133',
    english: '3D printing',
    korean: '3D프린팅',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a 3D printing.',
    exampleKorean: '나는 3D프린팅을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_134',
    english: 'cybersecurity',
    korean: '사이버보안',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a cybersecurity.',
    exampleKorean: '나는 사이버보안을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_135',
    english: 'encryption',
    korean: '암호화',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a encryption.',
    exampleKorean: '나는 암호화을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_136',
    english: 'upload',
    korean: '업로드',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a upload.',
    exampleKorean: '나는 업로드을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_137',
    english: 'storage',
    korean: '저장장치',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a storage.',
    exampleKorean: '나는 저장장치을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_138',
    english: 'memory',
    korean: '메모리',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a memory.',
    exampleKorean: '나는 메모리을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_139',
    english: 'processor',
    korean: '프로세서',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a processor.',
    exampleKorean: '나는 프로세서을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_140',
    english: 'screen',
    korean: '화면',
    grade: 5 as const,
    category: 'technology',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a screen.',
    exampleKorean: '나는 화면을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_141',
    english: 'health',
    korean: '건강',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a health.',
    exampleKorean: '나는 건강을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_142',
    english: 'disease',
    korean: '질병',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a disease.',
    exampleKorean: '나는 질병을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_143',
    english: 'symptom',
    korean: '증상',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a symptom.',
    exampleKorean: '나는 증상을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_144',
    english: 'medicine',
    korean: '약',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a medicine.',
    exampleKorean: '나는 약을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_145',
    english: 'vaccine',
    korean: '백신',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a vaccine.',
    exampleKorean: '나는 백신을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_146',
    english: 'surgery',
    korean: '수술',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a surgery.',
    exampleKorean: '나는 수술을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_147',
    english: 'hospital',
    korean: '병원',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a hospital.',
    exampleKorean: '나는 병원을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_148',
    english: 'emergency',
    korean: '응급',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a emergency.',
    exampleKorean: '나는 응급을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_149',
    english: 'ambulance',
    korean: '구급차',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ambulance.',
    exampleKorean: '나는 구급차을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_150',
    english: 'bandage',
    korean: '붕대',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a bandage.',
    exampleKorean: '나는 붕대을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_151',
    english: 'therapy',
    korean: '치료',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a therapy.',
    exampleKorean: '나는 치료을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_152',
    english: 'diet',
    korean: '식단',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a diet.',
    exampleKorean: '나는 식단을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_153',
    english: 'nutrition',
    korean: '영양',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a nutrition.',
    exampleKorean: '나는 영양을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_154',
    english: 'vitamin',
    korean: '비타민',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a vitamin.',
    exampleKorean: '나는 비타민을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_155',
    english: 'protein',
    korean: '단백질',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a protein.',
    exampleKorean: '나는 단백질을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_156',
    english: 'calorie',
    korean: '칼로리',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a calorie.',
    exampleKorean: '나는 칼로리을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_157',
    english: 'exercise',
    korean: '운동',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a exercise.',
    exampleKorean: '나는 운동을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_158',
    english: 'fitness',
    korean: '체력',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a fitness.',
    exampleKorean: '나는 체력을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_159',
    english: 'allergy',
    korean: '알레르기',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a allergy.',
    exampleKorean: '나는 알레르기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_160',
    english: 'fever',
    korean: '열',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a fever.',
    exampleKorean: '나는 열을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_161',
    english: 'infection',
    korean: '감염',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a infection.',
    exampleKorean: '나는 감염을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_162',
    english: 'virus',
    korean: '바이러스',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a virus.',
    exampleKorean: '나는 바이러스을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_163',
    english: 'bacteria',
    korean: '세균',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a bacteria.',
    exampleKorean: '나는 세균을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_164',
    english: 'immune',
    korean: '면역의',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a immune.',
    exampleKorean: '나는 면역의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_165',
    english: 'diagnosis',
    korean: '진단',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a diagnosis.',
    exampleKorean: '나는 진단을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_166',
    english: 'treatment',
    korean: '치료',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a treatment.',
    exampleKorean: '나는 치료을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_167',
    english: 'cure',
    korean: '치료법',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a cure.',
    exampleKorean: '나는 치료법을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_168',
    english: 'recovery',
    korean: '회복',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a recovery.',
    exampleKorean: '나는 회복을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_169',
    english: 'stress',
    korean: '스트레스',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a stress.',
    exampleKorean: '나는 스트레스을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_170',
    english: 'hygiene',
    korean: '위생',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a hygiene.',
    exampleKorean: '나는 위생을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_171',
    english: 'mental health',
    korean: '정신건강',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a mental health.',
    exampleKorean: '나는 정신건강을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_172',
    english: 'anxiety',
    korean: '불안',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a anxiety.',
    exampleKorean: '나는 불안을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_173',
    english: 'depression',
    korean: '우울증',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a depression.',
    exampleKorean: '나는 우울증을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_174',
    english: 'meditation',
    korean: '명상',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a meditation.',
    exampleKorean: '나는 명상을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_175',
    english: 'first aid',
    korean: '응급처치',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a first aid.',
    exampleKorean: '나는 응급처치을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_176',
    english: 'injection',
    korean: '주사',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a injection.',
    exampleKorean: '나는 주사을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_177',
    english: 'prescription',
    korean: '처방전',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a prescription.',
    exampleKorean: '나는 처방전을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_178',
    english: 'pharmacy',
    korean: '약국',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a pharmacy.',
    exampleKorean: '나는 약국을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_179',
    english: 'checkup',
    korean: '검진',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a checkup.',
    exampleKorean: '나는 검진을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_180',
    english: 'blood pressure',
    korean: '혈압',
    grade: 5 as const,
    category: 'health',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a blood pressure.',
    exampleKorean: '나는 혈압을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_181',
    english: 'absorb',
    korean: '흡수하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to absorb.',
    exampleKorean: '나는 흡수하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_182',
    english: 'accomplish',
    korean: '달성하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to accomplish.',
    exampleKorean: '나는 달성하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_183',
    english: 'achieve',
    korean: '이루다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to achieve.',
    exampleKorean: '나는 이루다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_184',
    english: 'acquire',
    korean: '획득하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to acquire.',
    exampleKorean: '나는 획득하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_185',
    english: 'adapt',
    korean: '적응하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to adapt.',
    exampleKorean: '나는 적응하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_186',
    english: 'adjust',
    korean: '조정하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to adjust.',
    exampleKorean: '나는 조정하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_187',
    english: 'admire',
    korean: '존경하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to admire.',
    exampleKorean: '나는 존경하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_188',
    english: 'adopt',
    korean: '채택하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to adopt.',
    exampleKorean: '나는 채택하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_189',
    english: 'advance',
    korean: '전진하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to advance.',
    exampleKorean: '나는 전진하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_190',
    english: 'advertise',
    korean: '광고하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to advertise.',
    exampleKorean: '나는 광고하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_191',
    english: 'affect',
    korean: '영향주다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to affect.',
    exampleKorean: '나는 영향주다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_192',
    english: 'afford',
    korean: '여유가있다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to afford.',
    exampleKorean: '나는 여유가있다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_193',
    english: 'analyze',
    korean: '분석하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to analyze.',
    exampleKorean: '나는 분석하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_194',
    english: 'announce',
    korean: '발표하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to announce.',
    exampleKorean: '나는 발표하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_195',
    english: 'anticipate',
    korean: '예상하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to anticipate.',
    exampleKorean: '나는 예상하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_196',
    english: 'apologize',
    korean: '사과하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to apologize.',
    exampleKorean: '나는 사과하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_197',
    english: 'appreciate',
    korean: '감사하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to appreciate.',
    exampleKorean: '나는 감사하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_198',
    english: 'approach',
    korean: '접근하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to approach.',
    exampleKorean: '나는 접근하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_199',
    english: 'approve',
    korean: '승인하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to approve.',
    exampleKorean: '나는 승인하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_200',
    english: 'arrange',
    korean: '배열하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to arrange.',
    exampleKorean: '나는 배열하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_201',
    english: 'assist',
    korean: '돕다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to assist.',
    exampleKorean: '나는 돕다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_202',
    english: 'assume',
    korean: '가정하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to assume.',
    exampleKorean: '나는 가정하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_203',
    english: 'attempt',
    korean: '시도하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to attempt.',
    exampleKorean: '나는 시도하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_204',
    english: 'attract',
    korean: '끌다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to attract.',
    exampleKorean: '나는 끌다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_205',
    english: 'avoid',
    korean: '피하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to avoid.',
    exampleKorean: '나는 피하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_206',
    english: 'balance',
    korean: '균형잡다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to balance.',
    exampleKorean: '나는 균형잡다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_207',
    english: 'behave',
    korean: '행동하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to behave.',
    exampleKorean: '나는 행동하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_208',
    english: 'benefit',
    korean: '이익을주다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to benefit.',
    exampleKorean: '나는 이익을주다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_209',
    english: 'blame',
    korean: '비난하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to blame.',
    exampleKorean: '나는 비난하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_210',
    english: 'boost',
    korean: '높이다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to boost.',
    exampleKorean: '나는 높이다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_211',
    english: 'calculate',
    korean: '계산하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to calculate.',
    exampleKorean: '나는 계산하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_212',
    english: 'capture',
    korean: '포착하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to capture.',
    exampleKorean: '나는 포착하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_213',
    english: 'challenge',
    korean: '도전하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to challenge.',
    exampleKorean: '나는 도전하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_214',
    english: 'claim',
    korean: '주장하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to claim.',
    exampleKorean: '나는 주장하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_215',
    english: 'clarify',
    korean: '명확히하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to clarify.',
    exampleKorean: '나는 명확히하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_216',
    english: 'classify',
    korean: '분류하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to classify.',
    exampleKorean: '나는 분류하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_217',
    english: 'collapse',
    korean: '무너지다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to collapse.',
    exampleKorean: '나는 무너지다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_218',
    english: 'combine',
    korean: '결합하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to combine.',
    exampleKorean: '나는 결합하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_219',
    english: 'commit',
    korean: '헌신하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to commit.',
    exampleKorean: '나는 헌신하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_220',
    english: 'communicate',
    korean: '소통하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to communicate.',
    exampleKorean: '나는 소통하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_221',
    english: 'concentrate',
    korean: '집중하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to concentrate.',
    exampleKorean: '나는 집중하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_222',
    english: 'conclude',
    korean: '결론짓다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to conclude.',
    exampleKorean: '나는 결론짓다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_223',
    english: 'conduct',
    korean: '수행하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to conduct.',
    exampleKorean: '나는 수행하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_224',
    english: 'confirm',
    korean: '확인하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to confirm.',
    exampleKorean: '나는 확인하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_225',
    english: 'confuse',
    korean: '혼동하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to confuse.',
    exampleKorean: '나는 혼동하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_226',
    english: 'consider',
    korean: '고려하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to consider.',
    exampleKorean: '나는 고려하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_227',
    english: 'consist',
    korean: '구성되다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to consist.',
    exampleKorean: '나는 구성되다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_228',
    english: 'construct',
    korean: '건설하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to construct.',
    exampleKorean: '나는 건설하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_229',
    english: 'consume',
    korean: '소비하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to consume.',
    exampleKorean: '나는 소비하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_230',
    english: 'contain',
    korean: '포함하다',
    grade: 5 as const,
    category: 'advanced verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to contain.',
    exampleKorean: '나는 포함하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_231',
    english: 'ability',
    korean: '능력',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ability.',
    exampleKorean: '나는 능력을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_232',
    english: 'absence',
    korean: '부재',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a absence.',
    exampleKorean: '나는 부재을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_233',
    english: 'access',
    korean: '접근',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a access.',
    exampleKorean: '나는 접근을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_234',
    english: 'achievement',
    korean: '성취',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a achievement.',
    exampleKorean: '나는 성취을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_235',
    english: 'action',
    korean: '행동',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a action.',
    exampleKorean: '나는 행동을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_236',
    english: 'addition',
    korean: '추가',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a addition.',
    exampleKorean: '나는 추가을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_237',
    english: 'administration',
    korean: '관리',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a administration.',
    exampleKorean: '나는 관리을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_238',
    english: 'advantage',
    korean: '장점',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a advantage.',
    exampleKorean: '나는 장점을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_239',
    english: 'adventure',
    korean: '모험',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a adventure.',
    exampleKorean: '나는 모험을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_240',
    english: 'advice',
    korean: '조언',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a advice.',
    exampleKorean: '나는 조언을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_241',
    english: 'agreement',
    korean: '동의',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a agreement.',
    exampleKorean: '나는 동의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_242',
    english: 'agriculture',
    korean: '농업',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a agriculture.',
    exampleKorean: '나는 농업을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_243',
    english: 'alternative',
    korean: '대안',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a alternative.',
    exampleKorean: '나는 대안을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_244',
    english: 'amount',
    korean: '양',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a amount.',
    exampleKorean: '나는 양을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_245',
    english: 'analysis',
    korean: '분석',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a analysis.',
    exampleKorean: '나는 분석을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_246',
    english: 'anniversary',
    korean: '기념일',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a anniversary.',
    exampleKorean: '나는 기념일을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_247',
    english: 'announcement',
    korean: '발표',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a announcement.',
    exampleKorean: '나는 발표을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_248',
    english: 'anxiety',
    korean: '불안',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a anxiety.',
    exampleKorean: '나는 불안을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_249',
    english: 'appearance',
    korean: '외모',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a appearance.',
    exampleKorean: '나는 외모을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_250',
    english: 'application',
    korean: '적용',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a application.',
    exampleKorean: '나는 적용을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_251',
    english: 'appreciation',
    korean: '감사',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a appreciation.',
    exampleKorean: '나는 감사을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_252',
    english: 'approach',
    korean: '접근법',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a approach.',
    exampleKorean: '나는 접근법을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_253',
    english: 'approval',
    korean: '승인',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a approval.',
    exampleKorean: '나는 승인을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_254',
    english: 'argument',
    korean: '논쟁',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a argument.',
    exampleKorean: '나는 논쟁을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_255',
    english: 'arrangement',
    korean: '배치',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a arrangement.',
    exampleKorean: '나는 배치을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_256',
    english: 'aspect',
    korean: '측면',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a aspect.',
    exampleKorean: '나는 측면을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_257',
    english: 'assessment',
    korean: '평가',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a assessment.',
    exampleKorean: '나는 평가을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_258',
    english: 'assistance',
    korean: '지원',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a assistance.',
    exampleKorean: '나는 지원을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_259',
    english: 'association',
    korean: '연합',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a association.',
    exampleKorean: '나는 연합을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_260',
    english: 'assumption',
    korean: '가정',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a assumption.',
    exampleKorean: '나는 가정을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_261',
    english: 'atmosphere',
    korean: '분위기',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a atmosphere.',
    exampleKorean: '나는 분위기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_262',
    english: 'attempt',
    korean: '시도',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a attempt.',
    exampleKorean: '나는 시도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_263',
    english: 'attention',
    korean: '주의',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a attention.',
    exampleKorean: '나는 주의을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_264',
    english: 'attitude',
    korean: '태도',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a attitude.',
    exampleKorean: '나는 태도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_265',
    english: 'authority',
    korean: '권위',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a authority.',
    exampleKorean: '나는 권위을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_266',
    english: 'awareness',
    korean: '인식',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a awareness.',
    exampleKorean: '나는 인식을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_267',
    english: 'background',
    korean: '배경',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a background.',
    exampleKorean: '나는 배경을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_268',
    english: 'balance',
    korean: '균형',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a balance.',
    exampleKorean: '나는 균형을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_269',
    english: 'barrier',
    korean: '장벽',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a barrier.',
    exampleKorean: '나는 장벽을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_270',
    english: 'basis',
    korean: '기초',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a basis.',
    exampleKorean: '나는 기초을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_271',
    english: 'behavior',
    korean: '행동',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a behavior.',
    exampleKorean: '나는 행동을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_272',
    english: 'belief',
    korean: '믿음',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a belief.',
    exampleKorean: '나는 믿음을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_273',
    english: 'benefit',
    korean: '이익',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a benefit.',
    exampleKorean: '나는 이익을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_274',
    english: 'biography',
    korean: '전기',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a biography.',
    exampleKorean: '나는 전기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_275',
    english: 'boundary',
    korean: '경계',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a boundary.',
    exampleKorean: '나는 경계을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_276',
    english: 'budget',
    korean: '예산',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a budget.',
    exampleKorean: '나는 예산을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_277',
    english: 'burden',
    korean: '짐',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a burden.',
    exampleKorean: '나는 짐을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_278',
    english: 'campaign',
    korean: '캠페인',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a campaign.',
    exampleKorean: '나는 캠페인을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_279',
    english: 'capacity',
    korean: '용량',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a capacity.',
    exampleKorean: '나는 용량을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g5_280',
    english: 'category',
    korean: '범주',
    grade: 5 as const,
    category: 'advanced nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a category.',
    exampleKorean: '나는 범주을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  }
];
