import { WordData } from '@/shared/types/game';

export const grade6Words: WordData[] = [
  {
    id: 'g6_001',
    english: 'literature',
    korean: '문학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a literature.',
    exampleKorean: '나는 문학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_002',
    english: 'mathematics',
    korean: '수학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a mathematics.',
    exampleKorean: '나는 수학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_003',
    english: 'geometry',
    korean: '기하학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a geometry.',
    exampleKorean: '나는 기하학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_004',
    english: 'algebra',
    korean: '대수학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a algebra.',
    exampleKorean: '나는 대수학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_005',
    english: 'statistics',
    korean: '통계학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a statistics.',
    exampleKorean: '나는 통계학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_006',
    english: 'biology',
    korean: '생물학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a biology.',
    exampleKorean: '나는 생물학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_007',
    english: 'chemistry',
    korean: '화학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a chemistry.',
    exampleKorean: '나는 화학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_008',
    english: 'physics',
    korean: '물리학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a physics.',
    exampleKorean: '나는 물리학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_009',
    english: 'astronomy',
    korean: '천문학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a astronomy.',
    exampleKorean: '나는 천문학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_010',
    english: 'geology',
    korean: '지질학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a geology.',
    exampleKorean: '나는 지질학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_011',
    english: 'psychology',
    korean: '심리학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a psychology.',
    exampleKorean: '나는 심리학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_012',
    english: 'philosophy',
    korean: '철학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a philosophy.',
    exampleKorean: '나는 철학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_013',
    english: 'sociology',
    korean: '사회학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 3 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a sociology.',
    exampleKorean: '나는 사회학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_014',
    english: 'economics',
    korean: '경제학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a economics.',
    exampleKorean: '나는 경제학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_015',
    english: 'politics',
    korean: '정치학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a politics.',
    exampleKorean: '나는 정치학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_016',
    english: 'anthropology',
    korean: '인류학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a anthropology.',
    exampleKorean: '나는 인류학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_017',
    english: 'archaeology',
    korean: '고고학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a archaeology.',
    exampleKorean: '나는 고고학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_018',
    english: 'linguistics',
    korean: '언어학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a linguistics.',
    exampleKorean: '나는 언어학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_019',
    english: 'architecture',
    korean: '건축학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a architecture.',
    exampleKorean: '나는 건축학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_020',
    english: 'engineering',
    korean: '공학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a engineering.',
    exampleKorean: '나는 공학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_021',
    english: 'medicine',
    korean: '의학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a medicine.',
    exampleKorean: '나는 의학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_022',
    english: 'ecology',
    korean: '생태학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ecology.',
    exampleKorean: '나는 생태학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_023',
    english: 'meteorology',
    korean: '기상학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a meteorology.',
    exampleKorean: '나는 기상학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_024',
    english: 'oceanography',
    korean: '해양학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a oceanography.',
    exampleKorean: '나는 해양학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_025',
    english: 'genetics',
    korean: '유전학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a genetics.',
    exampleKorean: '나는 유전학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_026',
    english: 'robotics',
    korean: '로봇공학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 4 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a robotics.',
    exampleKorean: '나는 로봇공학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_027',
    english: 'biotechnology',
    korean: '생명공학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a biotechnology.',
    exampleKorean: '나는 생명공학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_028',
    english: 'forensics',
    korean: '법의학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a forensics.',
    exampleKorean: '나는 법의학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_029',
    english: 'cartography',
    korean: '지도학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a cartography.',
    exampleKorean: '나는 지도학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_030',
    english: 'etymology',
    korean: '어원학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a etymology.',
    exampleKorean: '나는 어원학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_031',
    english: 'immunology',
    korean: '면역학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a immunology.',
    exampleKorean: '나는 면역학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_032',
    english: 'neuroscience',
    korean: '신경과학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a neuroscience.',
    exampleKorean: '나는 신경과학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_033',
    english: 'pharmacology',
    korean: '약리학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a pharmacology.',
    exampleKorean: '나는 약리학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_034',
    english: 'physiology',
    korean: '생리학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a physiology.',
    exampleKorean: '나는 생리학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_035',
    english: 'taxonomy',
    korean: '분류학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a taxonomy.',
    exampleKorean: '나는 분류학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_036',
    english: 'zoology',
    korean: '동물학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a zoology.',
    exampleKorean: '나는 동물학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_037',
    english: 'botany',
    korean: '식물학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a botany.',
    exampleKorean: '나는 식물학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_038',
    english: 'microbiology',
    korean: '미생물학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a microbiology.',
    exampleKorean: '나는 미생물학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_039',
    english: 'acoustics',
    korean: '음향학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a acoustics.',
    exampleKorean: '나는 음향학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_040',
    english: 'thermodynamics',
    korean: '열역학',
    grade: 6 as const,
    category: 'academic',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a thermodynamics.',
    exampleKorean: '나는 열역학을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_041',
    english: 'achievement',
    korean: '성취',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a achievement.',
    exampleKorean: '나는 성취을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_042',
    english: 'advantage',
    korean: '장점',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a advantage.',
    exampleKorean: '나는 장점을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_043',
    english: 'ambition',
    korean: '야망',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a ambition.',
    exampleKorean: '나는 야망을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_044',
    english: 'analysis',
    korean: '분석',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a analysis.',
    exampleKorean: '나는 분석을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_045',
    english: 'appearance',
    korean: '외관',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a appearance.',
    exampleKorean: '나는 외관을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_046',
    english: 'appreciation',
    korean: '감상',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a appreciation.',
    exampleKorean: '나는 감상을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_047',
    english: 'approach',
    korean: '접근',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a approach.',
    exampleKorean: '나는 접근을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_048',
    english: 'argument',
    korean: '논쟁',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a argument.',
    exampleKorean: '나는 논쟁을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_049',
    english: 'assumption',
    korean: '가정',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a assumption.',
    exampleKorean: '나는 가정을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_050',
    english: 'atmosphere',
    korean: '분위기',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a atmosphere.',
    exampleKorean: '나는 분위기을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_051',
    english: 'attitude',
    korean: '태도',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a attitude.',
    exampleKorean: '나는 태도을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_052',
    english: 'authority',
    korean: '권위',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a authority.',
    exampleKorean: '나는 권위을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_053',
    english: 'awareness',
    korean: '인식',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a awareness.',
    exampleKorean: '나는 인식을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_054',
    english: 'behavior',
    korean: '행동',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a behavior.',
    exampleKorean: '나는 행동을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_055',
    english: 'belief',
    korean: '신념',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a belief.',
    exampleKorean: '나는 신념을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_056',
    english: 'benefit',
    korean: '혜택',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a benefit.',
    exampleKorean: '나는 혜택을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_057',
    english: 'boundary',
    korean: '경계',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a boundary.',
    exampleKorean: '나는 경계을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_058',
    english: 'career',
    korean: '진로',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a career.',
    exampleKorean: '나는 진로을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_059',
    english: 'category',
    korean: '범주',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a category.',
    exampleKorean: '나는 범주을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_060',
    english: 'celebration',
    korean: '축하',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a celebration.',
    exampleKorean: '나는 축하을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_061',
    english: 'challenge',
    korean: '도전',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a challenge.',
    exampleKorean: '나는 도전을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_062',
    english: 'characteristic',
    korean: '특성',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a characteristic.',
    exampleKorean: '나는 특성을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_063',
    english: 'circumstance',
    korean: '상황',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a circumstance.',
    exampleKorean: '나는 상황을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_064',
    english: 'civilization',
    korean: '문명',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a civilization.',
    exampleKorean: '나는 문명을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_065',
    english: 'combination',
    korean: '조합',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a combination.',
    exampleKorean: '나는 조합을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_066',
    english: 'communication',
    korean: '소통',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a communication.',
    exampleKorean: '나는 소통을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_067',
    english: 'community',
    korean: '공동체',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a community.',
    exampleKorean: '나는 공동체을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_068',
    english: 'comparison',
    korean: '비교',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a comparison.',
    exampleKorean: '나는 비교을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_069',
    english: 'competition',
    korean: '경쟁',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a competition.',
    exampleKorean: '나는 경쟁을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_070',
    english: 'concept',
    korean: '개념',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a concept.',
    exampleKorean: '나는 개념을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_071',
    english: 'conclusion',
    korean: '결론',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a conclusion.',
    exampleKorean: '나는 결론을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_072',
    english: 'condition',
    korean: '조건',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a condition.',
    exampleKorean: '나는 조건을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_073',
    english: 'confidence',
    korean: '자신감',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a confidence.',
    exampleKorean: '나는 자신감을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_074',
    english: 'conflict',
    korean: '갈등',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a conflict.',
    exampleKorean: '나는 갈등을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_075',
    english: 'connection',
    korean: '연결',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a connection.',
    exampleKorean: '나는 연결을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_076',
    english: 'conscience',
    korean: '양심',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a conscience.',
    exampleKorean: '나는 양심을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_077',
    english: 'consequence',
    korean: '결과',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a consequence.',
    exampleKorean: '나는 결과을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_078',
    english: 'consideration',
    korean: '고려',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a consideration.',
    exampleKorean: '나는 고려을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_079',
    english: 'construction',
    korean: '건설',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a construction.',
    exampleKorean: '나는 건설을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_080',
    english: 'contribution',
    korean: '기여',
    grade: 6 as const,
    category: 'abstract nouns',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'noun',
    exampleSentence: 'I can see a contribution.',
    exampleKorean: '나는 기여을(를) 볼 수 있어요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_081',
    english: 'however',
    korean: '그러나',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks however.',
    exampleKorean: '그녀는 그러나 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_082',
    english: 'therefore',
    korean: '그러므로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks therefore.',
    exampleKorean: '그녀는 그러므로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_083',
    english: 'moreover',
    korean: '게다가',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks moreover.',
    exampleKorean: '그녀는 게다가 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_084',
    english: 'furthermore',
    korean: '더나아가',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks furthermore.',
    exampleKorean: '그녀는 더나아가 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_085',
    english: 'meanwhile',
    korean: '한편',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks meanwhile.',
    exampleKorean: '그녀는 한편 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_086',
    english: 'nevertheless',
    korean: '그럼에도불구하고',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks nevertheless.',
    exampleKorean: '그녀는 그럼에도불구하고 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_087',
    english: 'otherwise',
    korean: '그렇지않으면',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks otherwise.',
    exampleKorean: '그녀는 그렇지않으면 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_088',
    english: 'instead',
    korean: '대신에',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks instead.',
    exampleKorean: '그녀는 대신에 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_089',
    english: 'indeed',
    korean: '사실',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks indeed.',
    exampleKorean: '그녀는 사실 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_090',
    english: 'besides',
    korean: '게다가',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks besides.',
    exampleKorean: '그녀는 게다가 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_091',
    english: 'consequently',
    korean: '결과적으로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks consequently.',
    exampleKorean: '그녀는 결과적으로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_092',
    english: 'accordingly',
    korean: '따라서',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks accordingly.',
    exampleKorean: '그녀는 따라서 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_093',
    english: 'similarly',
    korean: '비슷하게',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks similarly.',
    exampleKorean: '그녀는 비슷하게 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_094',
    english: 'likewise',
    korean: '마찬가지로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks likewise.',
    exampleKorean: '그녀는 마찬가지로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_095',
    english: 'conversely',
    korean: '반대로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks conversely.',
    exampleKorean: '그녀는 반대로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_096',
    english: 'alternatively',
    korean: '또는',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks alternatively.',
    exampleKorean: '그녀는 또는 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_097',
    english: 'subsequently',
    korean: '그후에',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks subsequently.',
    exampleKorean: '그녀는 그후에 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_098',
    english: 'eventually',
    korean: '결국',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks eventually.',
    exampleKorean: '그녀는 결국 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_099',
    english: 'ultimately',
    korean: '궁극적으로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks ultimately.',
    exampleKorean: '그녀는 궁극적으로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_100',
    english: 'apparently',
    korean: '분명히',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks apparently.',
    exampleKorean: '그녀는 분명히 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_101',
    english: 'approximately',
    korean: '대략',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks approximately.',
    exampleKorean: '그녀는 대략 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_102',
    english: 'considerably',
    korean: '상당히',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks considerably.',
    exampleKorean: '그녀는 상당히 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_103',
    english: 'frequently',
    korean: '자주',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks frequently.',
    exampleKorean: '그녀는 자주 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_104',
    english: 'gradually',
    korean: '점차',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks gradually.',
    exampleKorean: '그녀는 점차 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_105',
    english: 'increasingly',
    korean: '점점더',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks increasingly.',
    exampleKorean: '그녀는 점점더 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_106',
    english: 'occasionally',
    korean: '가끔',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks occasionally.',
    exampleKorean: '그녀는 가끔 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_107',
    english: 'particularly',
    korean: '특히',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks particularly.',
    exampleKorean: '그녀는 특히 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_108',
    english: 'potentially',
    korean: '잠재적으로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks potentially.',
    exampleKorean: '그녀는 잠재적으로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_109',
    english: 'primarily',
    korean: '주로',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks primarily.',
    exampleKorean: '그녀는 주로 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_110',
    english: 'significantly',
    korean: '상당히',
    grade: 6 as const,
    category: 'connectors',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'adverb',
    exampleSentence: 'She speaks significantly.',
    exampleKorean: '그녀는 상당히 말해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_111',
    english: 'break down',
    korean: '고장나다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to break down.',
    exampleKorean: '나는 고장나다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_112',
    english: 'break up',
    korean: '헤어지다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to break up.',
    exampleKorean: '나는 헤어지다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_113',
    english: 'bring up',
    korean: '키우다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to bring up.',
    exampleKorean: '나는 키우다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_114',
    english: 'call off',
    korean: '취소하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to call off.',
    exampleKorean: '나는 취소하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_115',
    english: 'carry on',
    korean: '계속하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to carry on.',
    exampleKorean: '나는 계속하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_116',
    english: 'catch up',
    korean: '따라잡다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to catch up.',
    exampleKorean: '나는 따라잡다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_117',
    english: 'check in',
    korean: '체크인하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to check in.',
    exampleKorean: '나는 체크인하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_118',
    english: 'come across',
    korean: '우연히만나다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to come across.',
    exampleKorean: '나는 우연히만나다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_119',
    english: 'come up with',
    korean: '생각해내다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to come up with.',
    exampleKorean: '나는 생각해내다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_120',
    english: 'cut down',
    korean: '줄이다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to cut down.',
    exampleKorean: '나는 줄이다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_121',
    english: 'deal with',
    korean: '다루다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to deal with.',
    exampleKorean: '나는 다루다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_122',
    english: 'drop off',
    korean: '내려주다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to drop off.',
    exampleKorean: '나는 내려주다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_123',
    english: 'end up',
    korean: '결국~하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to end up.',
    exampleKorean: '나는 결국~하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_124',
    english: 'fall apart',
    korean: '무너지다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to fall apart.',
    exampleKorean: '나는 무너지다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_125',
    english: 'figure out',
    korean: '알아내다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to figure out.',
    exampleKorean: '나는 알아내다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_126',
    english: 'fill in',
    korean: '채워넣다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to fill in.',
    exampleKorean: '나는 채워넣다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_127',
    english: 'find out',
    korean: '발견하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to find out.',
    exampleKorean: '나는 발견하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_128',
    english: 'get along',
    korean: '잘지내다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to get along.',
    exampleKorean: '나는 잘지내다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_129',
    english: 'get over',
    korean: '극복하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to get over.',
    exampleKorean: '나는 극복하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_130',
    english: 'get rid of',
    korean: '없애다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to get rid of.',
    exampleKorean: '나는 없애다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_131',
    english: 'give up',
    korean: '포기하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to give up.',
    exampleKorean: '나는 포기하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_132',
    english: 'go ahead',
    korean: '진행하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to go ahead.',
    exampleKorean: '나는 진행하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_133',
    english: 'grow up',
    korean: '자라다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to grow up.',
    exampleKorean: '나는 자라다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_134',
    english: 'hand in',
    korean: '제출하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to hand in.',
    exampleKorean: '나는 제출하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_135',
    english: 'hang out',
    korean: '어울리다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to hang out.',
    exampleKorean: '나는 어울리다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_136',
    english: 'hold on',
    korean: '기다리다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to hold on.',
    exampleKorean: '나는 기다리다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_137',
    english: 'keep up',
    korean: '유지하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to keep up.',
    exampleKorean: '나는 유지하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_138',
    english: 'let down',
    korean: '실망시키다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to let down.',
    exampleKorean: '나는 실망시키다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_139',
    english: 'look after',
    korean: '돌보다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to look after.',
    exampleKorean: '나는 돌보다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_140',
    english: 'look forward to',
    korean: '기대하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to look forward to.',
    exampleKorean: '나는 기대하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_141',
    english: 'look up',
    korean: '찾아보다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to look up.',
    exampleKorean: '나는 찾아보다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_142',
    english: 'make up',
    korean: '화해하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to make up.',
    exampleKorean: '나는 화해하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_143',
    english: 'move on',
    korean: '넘어가다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to move on.',
    exampleKorean: '나는 넘어가다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_144',
    english: 'pick up',
    korean: '줍다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to pick up.',
    exampleKorean: '나는 줍다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_145',
    english: 'point out',
    korean: '지적하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to point out.',
    exampleKorean: '나는 지적하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_146',
    english: 'put off',
    korean: '연기하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to put off.',
    exampleKorean: '나는 연기하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_147',
    english: 'put on',
    korean: '입다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to put on.',
    exampleKorean: '나는 입다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_148',
    english: 'run out of',
    korean: '다쓰다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to run out of.',
    exampleKorean: '나는 다쓰다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_149',
    english: 'set up',
    korean: '설치하다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to set up.',
    exampleKorean: '나는 설치하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_150',
    english: 'show up',
    korean: '나타나다',
    grade: 6 as const,
    category: 'phrasal verbs',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to show up.',
    exampleKorean: '나는 나타나다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_151',
    english: 'abandon',
    korean: '버리다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to abandon.',
    exampleKorean: '나는 버리다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_152',
    english: 'abolish',
    korean: '폐지하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to abolish.',
    exampleKorean: '나는 폐지하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_153',
    english: 'accelerate',
    korean: '가속하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to accelerate.',
    exampleKorean: '나는 가속하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_154',
    english: 'accommodate',
    korean: '수용하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to accommodate.',
    exampleKorean: '나는 수용하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_155',
    english: 'accumulate',
    korean: '축적하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to accumulate.',
    exampleKorean: '나는 축적하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_156',
    english: 'acknowledge',
    korean: '인정하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to acknowledge.',
    exampleKorean: '나는 인정하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_157',
    english: 'activate',
    korean: '활성화하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to activate.',
    exampleKorean: '나는 활성화하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_158',
    english: 'administer',
    korean: '관리하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to administer.',
    exampleKorean: '나는 관리하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_159',
    english: 'advocate',
    korean: '옹호하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to advocate.',
    exampleKorean: '나는 옹호하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_160',
    english: 'allocate',
    korean: '배분하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to allocate.',
    exampleKorean: '나는 배분하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_161',
    english: 'alter',
    korean: '변경하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to alter.',
    exampleKorean: '나는 변경하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_162',
    english: 'amend',
    korean: '수정하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to amend.',
    exampleKorean: '나는 수정하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_163',
    english: 'anticipate',
    korean: '예상하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to anticipate.',
    exampleKorean: '나는 예상하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_164',
    english: 'appeal',
    korean: '호소하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to appeal.',
    exampleKorean: '나는 호소하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_165',
    english: 'appoint',
    korean: '임명하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to appoint.',
    exampleKorean: '나는 임명하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_166',
    english: 'assign',
    korean: '배정하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to assign.',
    exampleKorean: '나는 배정하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_167',
    english: 'authorize',
    korean: '권한부여하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to authorize.',
    exampleKorean: '나는 권한부여하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_168',
    english: 'ban',
    korean: '금지하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to ban.',
    exampleKorean: '나는 금지하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_169',
    english: 'broaden',
    korean: '넓히다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to broaden.',
    exampleKorean: '나는 넓히다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_170',
    english: 'categorize',
    korean: '분류하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to categorize.',
    exampleKorean: '나는 분류하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_171',
    english: 'cease',
    korean: '중단하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to cease.',
    exampleKorean: '나는 중단하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_172',
    english: 'certify',
    korean: '인증하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to certify.',
    exampleKorean: '나는 인증하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_173',
    english: 'characterize',
    korean: '특징짓다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to characterize.',
    exampleKorean: '나는 특징짓다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_174',
    english: 'circulate',
    korean: '순환하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to circulate.',
    exampleKorean: '나는 순환하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_175',
    english: 'cite',
    korean: '인용하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to cite.',
    exampleKorean: '나는 인용하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_176',
    english: 'clarify',
    korean: '명확히하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to clarify.',
    exampleKorean: '나는 명확히하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_177',
    english: 'coincide',
    korean: '일치하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to coincide.',
    exampleKorean: '나는 일치하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_178',
    english: 'collaborate',
    korean: '협력하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to collaborate.',
    exampleKorean: '나는 협력하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_179',
    english: 'commence',
    korean: '시작하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to commence.',
    exampleKorean: '나는 시작하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_180',
    english: 'compensate',
    korean: '보상하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to compensate.',
    exampleKorean: '나는 보상하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_181',
    english: 'compile',
    korean: '편집하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to compile.',
    exampleKorean: '나는 편집하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_182',
    english: 'comply',
    korean: '준수하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to comply.',
    exampleKorean: '나는 준수하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_183',
    english: 'comprise',
    korean: '구성하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to comprise.',
    exampleKorean: '나는 구성하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_184',
    english: 'conceive',
    korean: '생각해내다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to conceive.',
    exampleKorean: '나는 생각해내다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_185',
    english: 'confine',
    korean: '제한하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to confine.',
    exampleKorean: '나는 제한하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_186',
    english: 'confront',
    korean: '맞서다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to confront.',
    exampleKorean: '나는 맞서다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_187',
    english: 'consolidate',
    korean: '통합하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to consolidate.',
    exampleKorean: '나는 통합하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_188',
    english: 'constitute',
    korean: '구성하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to constitute.',
    exampleKorean: '나는 구성하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_189',
    english: 'constrain',
    korean: '제약하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to constrain.',
    exampleKorean: '나는 제약하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_190',
    english: 'contemplate',
    korean: '숙고하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to contemplate.',
    exampleKorean: '나는 숙고하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_191',
    english: 'contradict',
    korean: '모순되다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to contradict.',
    exampleKorean: '나는 모순되다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_192',
    english: 'convert',
    korean: '전환하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to convert.',
    exampleKorean: '나는 전환하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_193',
    english: 'cultivate',
    korean: '재배하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to cultivate.',
    exampleKorean: '나는 재배하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_194',
    english: 'deceive',
    korean: '속이다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to deceive.',
    exampleKorean: '나는 속이다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_195',
    english: 'dedicate',
    korean: '헌신하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to dedicate.',
    exampleKorean: '나는 헌신하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_196',
    english: 'delegate',
    korean: '위임하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to delegate.',
    exampleKorean: '나는 위임하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_197',
    english: 'deliberate',
    korean: '숙고하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to deliberate.',
    exampleKorean: '나는 숙고하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_198',
    english: 'demolish',
    korean: '철거하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to demolish.',
    exampleKorean: '나는 철거하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_199',
    english: 'depict',
    korean: '묘사하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to depict.',
    exampleKorean: '나는 묘사하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_200',
    english: 'deploy',
    korean: '배치하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to deploy.',
    exampleKorean: '나는 배치하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_201',
    english: 'derive',
    korean: '유래하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to derive.',
    exampleKorean: '나는 유래하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_202',
    english: 'designate',
    korean: '지정하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to designate.',
    exampleKorean: '나는 지정하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_203',
    english: 'deteriorate',
    korean: '악화하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to deteriorate.',
    exampleKorean: '나는 악화하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_204',
    english: 'devise',
    korean: '고안하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to devise.',
    exampleKorean: '나는 고안하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_205',
    english: 'differentiate',
    korean: '구별하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to differentiate.',
    exampleKorean: '나는 구별하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_206',
    english: 'diminish',
    korean: '줄이다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to diminish.',
    exampleKorean: '나는 줄이다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_207',
    english: 'disclose',
    korean: '공개하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to disclose.',
    exampleKorean: '나는 공개하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_208',
    english: 'discriminate',
    korean: '차별하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to discriminate.',
    exampleKorean: '나는 차별하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_209',
    english: 'displace',
    korean: '대체하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to displace.',
    exampleKorean: '나는 대체하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  },
  {
    id: 'g6_210',
    english: 'dispose',
    korean: '처리하다',
    grade: 6 as const,
    category: 'advanced verbs6',
    difficulty: 5 as 1 | 2 | 3 | 4 | 5,
    phonetic: '',
    partOfSpeech: 'verb',
    exampleSentence: 'I like to dispose.',
    exampleKorean: '나는 처리하다을(를) 좋아해요.',
    synonyms: [],
    antonyms: [],
    relatedWords: [],
  }
];
